/**
 * refresh-core/build.mjs —— 刷新核心的编译脚本（#720 落地）
 *
 * 只转译不打包：用仓库现成的 esbuild 把 refresh-core/src/ 下每个 TS 文件一对一转成
 * src/shared/refresh/ 下的同名 JS；另跑 tsc --noEmit 只做类型检查。生成的 JS 提交进 git；
 * 改了 TS 没重新生成，tests/verify-refresh-freshness.js 会变红。
 *
 * 与 update-core/build.mjs 的差别，都是这份形态的要求，不是随手改的
 * （依据：docs/adr/20260913-builtin-ts-shape.md §2.4 点名要补的那个缺口）：
 * 1. 本文件导出 transpileUnit、runTypeCheck、buildAll 三个函数。update-core 的脚本只导出了
 *    transpileUnit，转译入口是文件内的私有函数、外面调不到；这里要让 scripts/build.mjs 在一条
 *    命令里把类型检查与转译都带上，所以三个都导出。
 * 2. 类型检查与转译是两步，调用方按顺序各调一次：本文件末尾的命令行入口与 scripts/build.mjs
 *    都是「先 runTypeCheck()，再 buildAll()」。为什么不照 label-color-core 那样把类型检查写在
 *    buildAll 里面：接线要求正是「runTypeCheck() 与 buildAll() 各调用一次」，写在里面会让一次
 *    主构建跑两遍 tsc，白等一秒；所以这里把两件事拆开，buildAll 只管判断源码树在不在、再把
 *    文件逐份转出来。谁要单独用 buildAll，记得自己先调 runTypeCheck。
 * 3. 两个函数都先判断源码目录与 tsconfig 在不在，不在就打印一行提示、跳过自己这一步，
 *    绝不中断整个构建。原因：npm 发布包里没有这棵源码树（package/package.json 的 files
 *    白名单只有 lib、shared、cordis.patch.yml、bundled-skills、scripts/），在那种子树里
 *    跑构建时这两步本来就做不了。
 * 4. 转译结果要把 esbuild 收在文件末尾的 `export { ... };` 改写成声明前的行首 export
 *    （见下面 inlineExportDeclarations 的说明）。这样产物形态与两份先例一致；将来真要把某个
 *    产物拼进客户端闭包时，拼接那套「去掉行首 export」的做法直接就能用，不必再改这个脚本。
 *
 * 用法：node refresh-core/build.mjs（在仓库根目录；日常更常用 node scripts/build.mjs，
 * 那条命令会把本脚本的这两步一起带上，不必手动补跑）。
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import * as esbuild from 'esbuild'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC_DIR = resolve(ROOT, 'refresh-core/src')
const OUT_DIR = resolve(ROOT, 'src/shared/refresh')
const TSCONFIG = resolve(ROOT, 'refresh-core/tsconfig.json')

const UNITS = [
  { ts: 'ports.ts', js: 'ports.js' },
  { ts: 'budget.ts', js: 'budget.js' },
  // #711 加的第三份：创建幂等锚的构造与回查判据。三个后端房间都 import 它的产物
  //（见 tests/verify-no-cross-import.js 白名单里的 src/shared/refresh/）。
  { ts: 'idempotency.ts', js: 'idempotency.js' },
  // #706（T2）加的第四份：闸的裁决纯函数。宿主侧 src/host/refresh/gate.js 每放行一笔就调它一次，
  // 数字由 gate.js 从 budget.js 取好注入（policy.ts 自己不 import 任何产物，免得踩同层互引）。
  { ts: 'policy.ts', js: 'policy.js' },
  // #707（T3）加的第五份：视野模型的纯逻辑（活跃集合的名额与淘汰、同一工作区根只占一个名额、
  // 90 秒无信号的收摊判定、每个活跃根该按什么间隔探测）。宿主侧 src/host/refresh/attention.js
  // 拿它当薄壳，数字同样由那一边从 budget.js 取好注入。
  { ts: 'attention.ts', js: 'attention.js' },
  // #710（T6）加的第六份：写事件的判定表（纯函数）。宿主侧 src/host/refresh/writeEvents.js 每收到一条
  // 成功的工具调用就喂它一次，返回「三档 + 票号或未知」；参数只在这一层做瞬时匹配，返回值里不带命令原文。
  { ts: 'write-detect.ts', js: 'write-detect.js' },
  // #709（T5）加的第七份：「下一次什么时候再查」的纯函数 —— 退避序列（8 秒 → 30 秒 → 2 分钟 → 5 分钟）、
  // 有进展立刻回快档、全绿缓存 30 分钟、环境预检寿命 10 分钟、失败后允许立刻重试几次。
  // 数字由调用方从 budget.js 取好注入（backoff.ts 自己不 import 任何产物，免得踩同层互引）。
  { ts: 'backoff.ts', js: 'backoff.js' },
  // #714（T10）加的第八份：会话↔票 处理链的纯逻辑（链的键构造、按会话分格的去重与留存、
  // 「只记写不记读」的过滤判定、落盘形状与隐私自检）。宿主侧 src/host/refresh/sessionTickets.js
  // 拿它当薄壳：内存表与落盘在那一边，时间由那一边传进来。
  { ts: 'chain.ts', js: 'chain.js' },
  // #708（T4）加的第九份：行级增量刷新的纯逻辑 —— 差分与合并规则、水印推进的判定（只在变化真正并进
  // 列表之后才推进）、世代号的新旧比较、派生值该重算还是标「待确认」、旧结构的判定。
  // 宿主侧 src/host/refresh/patch.js 每一步都调它；索引与时间都由那一边传进来，本文件一个都不自己取。
  { ts: 'delta.ts', js: 'delta.js' },
  // #713（T9）加的第十份：AI 工具的「调用前算账」（预估点数、预估出站请求数、是否超单次顶、
  // 建议分几片）。额度常量仍然只有一处物理真源（budget.ts），由宿主侧取好传进来 ——
  // 产物之间不许互相 import（tests/verify-no-same-layer-import.js 与新鲜度门禁的「产物零相对引用」），
  // 所以本文件只放算式与形状，做法与 policy.ts / backoff.ts 一致。
  { ts: 'tool-cost.ts', js: 'tool-cost.js' },
  // #722（T18）加的第十一份：GitLab 建票那一次写请求的结果判据（四档结论 + 许不许再发一次）。
  // 宿主侧 src/host/tracker/backends/gitlab/create-write.js 拿它判每一次 glab 调用，判据只此一处；
  // 「确定没发出去」才允许重发一次，其余（含超时）一律不再写，免得远端多出一张票。
  { ts: 'create-write.ts', js: 'create-write.js' },
  // #719（T15）加的第十二份：一次整池重建按「翻了几页」算价钱的算式（实测算用的页数与
  // 最坏用量用的页数上界分开）。宿主侧 src/host/refresh/ledger.js 记每个仓库的实测页数，
  // 每页单价由那一边从 budget.js 取好传进来 —— 本文件自己不 import 任何产物。
  { ts: 'page-budget.ts', js: 'page-budget.js' },
  // #719（T15）加的第十三份：每个后端的额度桶形状与「按后端算价」（GitHub 两桶 / GitLab 只按
  // 请求数（数值待实测）/ 本地 Markdown 不出站不计费）。本文件不写任何额度数值，只写形状与判定。
  { ts: 'backend-quota.ts', js: 'backend-quota.js' },
]

function headerFor(tsName) {
  return `// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/${tsName}\n`
}

/** 源码树不在时那句提示。两个函数共用一份，免得两处措辞慢慢走岔。 */
function skipNotice(step) {
  return (
    '[refresh-core] 没找到源码目录或 tsconfig（' + SRC_DIR + ' / ' + TSCONFIG + '），本次跳过' + step +
    '。发布包与 package/ 子树里本来就没有这棵源码树，这是预期情况；要重新生成产物请在仓库根目录跑 node scripts/build.mjs。'
  )
}

/**
 * 把 esbuild 收在文件末尾的导出块改写成声明前的行首 export。
 *
 * 为什么必须改写：esbuild 的转译结果不是 `export const X = 1` 这种行首形式，而是把声明照常写在
 * 前面、末尾收一个 `export { X, Y };` 块。将来某个产物要拼进客户端闭包时，拼接的做法是去掉每行
 * 行首的 `export `（见 scripts/build.mjs 的 extractModuleBlock）；那种末尾块去掉行首 export 之后
 * 只剩一个 `{ X, Y };` 语句块，名字虽然还在（函数声明与 const 都在同一作用域里），形态却与仓库里
 * 其它拼进闭包的共享文件完全不一样，读代码的人会看不懂。所以这里统一改回行首形式。
 *
 * 只认「名字能在同一份文件里找到 function / const / let / var / class 声明」这一种情形；
 * 找不到就抛错，绝不静默产出一个少了一个导出的产物。
 */
function inlineExportDeclarations(code) {
  const clause = /(^|\n)export \{\n([\s\S]*?)\n\};\n?$/.exec(code)
  if (!clause) {
    if (/(^|\n)export \{/.test(code)) {
      throw new Error('[refresh-core] 转译结果里出现了没有预料到的导出块写法，拒绝改写：\n' + code.slice(-300))
    }
    return code
  }
  const names = clause[2]
    .split(',')
    .map((s) => s.trim())
    .filter((s) => s !== '')
  let body = code.slice(0, clause.index) + (clause[1] === '\n' ? '\n' : '')
  for (const name of names) {
    if (!/^[A-Za-z_$][\w$]*$/.test(name)) {
      throw new Error(`[refresh-core] 导出块里有改不了名的条目「${name}」：本脚本只支持原样导出，不支持 as 改名`)
    }
    const decl = new RegExp('^(?:async )?function ' + name + '\\b|^(?:const|let|var) ' + name + '\\b|^class ' + name + '\\b', 'm')
    const hit = decl.exec(body)
    if (!hit) {
      throw new Error(`[refresh-core] 导出块里的名字「${name}」在这份文件里找不到声明，拒绝生成少一个导出的产物`)
    }
    body = body.slice(0, hit.index) + 'export ' + body.slice(hit.index)
  }
  return body
}

/** 与新鲜度门禁同一口径：转译加包头，换行归一，末尾恰好一个换行。 */
export function transpileUnit(tsName) {
  const tsPath = resolve(SRC_DIR, tsName)
  const source = readFileSync(tsPath, 'utf8')
  const out = esbuild.transformSync(source, {
    loader: 'ts',
    format: 'esm',
    // 保守目标：Node 宿主与浏览器闭包两边都跑得动。
    target: 'es2020',
  })
  const normalized = out.code.replace(/\r\n/g, '\n').replace(/\s+$/, '') + '\n'
  return headerFor(tsName) + inlineExportDeclarations(normalized)
}

/**
 * 跑一次 `tsc --noEmit`。typescript 没装（没跑过 pnpm install）时明确报错，不静默跳过。
 * 源码树或 tsconfig 不在时跳过并打印一行提示（见文件头的第 3 条差别）。
 * 返回 { skipped }，调用方据此知道这一步做了没有。
 */
export function runTypeCheck() {
  if (!existsSync(SRC_DIR) || !existsSync(TSCONFIG)) {
    console.log(skipNotice('类型检查'))
    return { skipped: true }
  }
  const require = createRequire(resolve(ROOT, 'package.json'))
  let tscBin
  try {
    tscBin = resolve(dirname(require.resolve('typescript/package.json')), 'bin/tsc')
  } catch {
    throw new Error('[refresh-core] 找不到 typescript：请先运行 pnpm install（devDependencies 含 typescript）')
  }
  const r = spawnSync(process.execPath, [tscBin, '-p', TSCONFIG], { encoding: 'utf8' })
  if (r.status !== 0) {
    throw new Error(`[refresh-core] tsc --noEmit 未通过：\n${r.stdout || ''}${r.stderr || ''}`)
  }
  console.log('[refresh-core] tsc --noEmit 通过')
  return { skipped: false }
}

/**
 * 把每个 TS 文件逐份转译进 src/shared/refresh/。类型检查不在这里，由调用方先调 runTypeCheck。
 * 源码目录或 tsconfig 不在时跳过：发布包与 package/ 子树里本来就没有这棵源码树，
 * 那种情况下构建立刻中断会挡住别的步骤，而这里要的只是「这一步没法做，跳过它」。
 * 返回 { skipped, files }，调用方（scripts/build.mjs）可以据此打印自己的日志。
 */
export function buildAll() {
  if (!existsSync(SRC_DIR) || !existsSync(TSCONFIG)) {
    console.log(skipNotice('转译'))
    return { skipped: true, files: [] }
  }
  mkdirSync(OUT_DIR, { recursive: true })
  const files = []
  for (const u of UNITS) {
    const text = transpileUnit(u.ts)
    const outPath = resolve(OUT_DIR, u.js)
    writeFileSync(outPath, text, 'utf8')
    console.log(`[refresh-core] ${u.ts} -> src/shared/refresh/${u.js}（${text.split('\n').length} 行）`)
    files.push('src/shared/refresh/' + u.js)
  }
  return { skipped: false, files }
}

const invoked = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (invoked) {
  try {
    runTypeCheck()
    buildAll()
  } catch (e) {
    console.error((e && e.message) || e)
    process.exit(1)
  }
}
