/**
 * packages/dsh-log/build.mjs —— 日志包的编译脚本（沿 update-core/build.mjs 同口径）
 *
 * 只转译不打包：用仓库现成的 esbuild 把 packages/dsh-log/src/ 下每个 TS 文件
 * 一对一转成 packages/dsh-log/dist/ 下的同名 JS；另跑 tsc --noEmit 只做类型检查。
 * 生成的 JS 不提交到 git（发布前跑 build:dsh-log 本地生成）；改了 TS 没重新生成，测试直接引用 dist 会过期，由单测兜住。
 *
 * 用法：node packages/dsh-log/build.mjs（在仓库根目录或包目录均可）
 * 或：npm run build --workspace=dsh-log（需先接好 workspace，见 pnpm-workspace.yaml）
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import * as esbuild from 'esbuild'

const PKG_DIR = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(PKG_DIR, '..', '..')
const SRC_DIR = resolve(PKG_DIR, 'src')
const OUT_DIR = resolve(PKG_DIR, 'dist')

const UNITS = [{ ts: 'config.ts', js: 'config.js' }, { ts: 'store.ts', js: 'store.js' }, { ts: 'phones.ts', js: 'phones.js' }, { ts: 'host.ts', js: 'host.js' }, { ts: 'client.ts', js: 'client.js' }, { ts: 'node.ts', js: 'node.js' }]

function headerFor(tsName) {
  return `// AUTO-GENERATED by node packages/dsh-log/build.mjs — DO NOT EDIT. Source: packages/dsh-log/src/${tsName}\n`
}

/** 与门禁同一口径：转译加包头，换行归一，末尾恰好一个换行。 */
export function transpileUnit(tsName) {
  const tsPath = resolve(SRC_DIR, tsName)
  const source = readFileSync(tsPath, 'utf8')
  const out = esbuild.transformSync(source, {
    loader: 'ts',
    format: 'esm',
    // 保守目标：Node 宿主与浏览器闭包两边都跑得动。
    target: 'es2020'
  })
  const body = out.code.replace(/\r\n/g, '\n').replace(/\s+$/, '') + '\n'
  return headerFor(tsName) + body
}

function runTypeCheck() {
  const require = createRequire(resolve(ROOT, 'package.json'))
  let tscBin
  try {
    tscBin = resolve(dirname(require.resolve('typescript/package.json')), 'bin/tsc')
  } catch {
    throw new Error('[dsh-log] 找不到 typescript：请先运行 pnpm install（根 devDependencies 含 typescript）')
  }
  const r = spawnSync(process.execPath, [tscBin, '-p', resolve(PKG_DIR, 'tsconfig.json')], {
    encoding: 'utf8'
  })
  if (r.status !== 0) {
    throw new Error(`[dsh-log] tsc --noEmit 未通过：\n${r.stdout || ''}${r.stderr || ''}`)
  }
  console.log('[dsh-log] tsc --noEmit 通过')
}

function main() {
  runTypeCheck()
  mkdirSync(OUT_DIR, { recursive: true })
  for (const u of UNITS) {
    const text = transpileUnit(u.ts)
    const outPath = resolve(OUT_DIR, u.js)
    writeFileSync(outPath, text, 'utf8')
    console.log(`[dsh-log] ${u.ts} -> dist/${u.js}（${text.split('\n').length} 行）`)
  }
}

const invoked = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (invoked) {
  try {
    main()
  } catch (e) {
    console.error((e && e.message) || e)
    process.exit(1)
  }
}
