#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# 这个向导做的事：把 dsh-log 发到 npm 官方源（registry.npmjs.org）。
# 一次发布走六段：体检 → 网页登录（扫码）→ 升版本 → 构建与干跑 → 真发布 → 发布后验证。
#
# Windows 上跑法（不要用 WSL 的 bash，路径会对不上）：
#   "C:\Program Files\Git\bin\bash.exe" packages/dsh-log/publish-wizard.sh

REGISTRY="https://registry.npmjs.org/"
DRILL_FILE="notes-publish-drill.md"

# 脚本放在包目录里，但可能在仓库根或包目录下被调起，这里自己找准包目录。
_here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
if [[ -f "$_here/package.json" ]]; then
  PKG_DIR="$_here"
elif [[ -f "$_here/packages/dsh-log/package.json" ]]; then
  PKG_DIR="$_here/packages/dsh-log"
else
  printf '%s\n' '找不到日志包目录（package.json），请在仓库根或 packages/dsh-log 下运行。'
  exit 1
fi
ROOT_DIR=$(cd "$PKG_DIR/../.." && pwd)

_pkg_field() {
  # 从包清单里取一个顶层字段的字符串值，不引第三方工具。
  local key="$1"
  sed -n "s/^[[:space:]]*\"$key\":[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$PKG_DIR/package.json" | head -n1
}

TOTAL_STAGES=6

banner "发布 dsh-log 到 npm 官方源"

# ── 第一段：发布前体检（只读，什么都不改） ────────────────────────────────
stage "发布前体检（只读）"
CUR_VERSION=$(_pkg_field version)
PKG_NAME=$(_pkg_field name)
TARGET_REGISTRY=$(sed -n 's/.*"registry":[[:space:]]*"\([^"]*\)".*/\1/p' "$PKG_DIR/package.json" | head -n1)
say "包名：$PKG_NAME"
say "当前版本：$CUR_VERSION"
say "发布目标：${TARGET_REGISTRY:-（包清单里没写，会落到本机默认源，危险）}"
if [[ "$TARGET_REGISTRY" != "$REGISTRY" ]]; then
  warn "包清单里的发布目标不是官方源，先停下来改 publishConfig，别发到镜像上去"
  exit 1
fi
step "官方源上这个名字有没有被占："
if npm view "$PKG_NAME" version --registry="$REGISTRY" >/dev/null 2>&1; then
  OCCUPIED=$(npm view "$PKG_NAME" version --registry="$REGISTRY" 2>/dev/null | tail -n1)
  warn "已被占用，官方源上现有版本：$OCCUPIED —— 换名字，或确认这是你自己的包"
else
  say "未被占用（404），可以用这个名字"
fi

# ── 第二段：网页登录（你在浏览器里扫码） ──────────────────────────────────
stage "登录 npm（扫码在浏览器那一步完成）"
say "现在要重新登录：本机原有的令牌对官方源已经失效（401），发布必须现登一次。"
open_url "https://www.npmjs.com/"
note "网页登录的二维码就在那个页面；官方源的最新提醒也说了，能绕过双因素的旧令牌正在被限制。"
note "接着这条登录命令由向导自己跑：它会打印一个登录链接，并在你按回车后打开浏览器。"
note "你在浏览器里扫码登录、确认授权；命令返回后向导会自动往下走。"
pause "准备好了就按回车，我开始跑登录命令"
npm login --auth-type=web --registry="$REGISTRY"
step "验证身份（只显示账号名）："
ME=$(npm whoami --registry="$REGISTRY" 2>/dev/null || true)
if [[ -z "$ME" ]]; then
  warn "没验到身份：登录没完成或令牌没写进 ~/.npmrc"
  note "重跑：npm login --auth-type=web --registry=$REGISTRY"
  exit 1
fi
printf '  %s✓ 当前身份：%s%s\n' "$GREEN" "$ME" "$RESET"
note "确认这个账号就是要把包发出去的账号（发出去撤不回来）。"
pause "账号没问题就按回车"

# ── 第三段：把版本号升到要发布的版本 ─────────────────────────────────────
stage "升版本号"
say "新版本号按 README 第 10 节的版本策略定：只改文档或修缺陷动补丁位，加能力动次版本位，破坏性变更才动更早的位。"
NEXT_PATCH=$(printf '%s' "$CUR_VERSION" | awk -F. '{ if (NF == 3) printf "%d.%d.%d", $1, $2, $3 + 1; else print $0 }')
ask PUBLISH_VERSION "要发布的版本号（直接回车用 $NEXT_PATCH）：" 
PUBLISH_VERSION=${PUBLISH_VERSION:-$NEXT_PATCH}
if [[ ! "$PUBLISH_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  warn "版本号要写成 X.Y.Z 三段数字（收到：$PUBLISH_VERSION）"
  exit 1
fi
if [[ "$PUBLISH_VERSION" == "$CUR_VERSION" ]]; then
  warn "版本号跟当前一样（还是 $CUR_VERSION）：换一个新号再跑"
  exit 1
fi
if npm view "$PKG_NAME@$PUBLISH_VERSION" version --registry="$REGISTRY" >/dev/null 2>&1; then
  warn "官方源上已经有 $PKG_NAME@$PUBLISH_VERSION：发过的号不能再发，换一个新号"
  exit 1
fi
say "将把 $CUR_VERSION 改成 $PUBLISH_VERSION（包清单与 README 各一处）。"
if ! confirm "确认升版本？"; then
  warn "已取消，什么都没改"
  exit 1
fi
(cd "$PKG_DIR" && node -e "
const fs = require('fs')
const p = 'package.json'
const j = JSON.parse(fs.readFileSync(p, 'utf8'))
j.version = process.argv[1]
fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n')
" "$PUBLISH_VERSION")
if grep -q '当前版本 `'"$CUR_VERSION"'`' "$PKG_DIR/README.md"; then
  sed "s/当前版本 \`$CUR_VERSION\`/当前版本 \`$PUBLISH_VERSION\`/" "$PKG_DIR/README.md" > "$PKG_DIR/README.md.tmp"
  mv "$PKG_DIR/README.md.tmp" "$PKG_DIR/README.md"
fi
NEW_VERSION=$(_pkg_field version)
printf '  %s✓ 包清单版本：%s%s\n' "$GREEN" "$NEW_VERSION" "$RESET"
say "README 里的版本行：$(grep -n '当前版本' "$PKG_DIR/README.md" | head -n1)"
pause "看一眼，没问题按回车"

# ── 第四段：构建 + 干跑打包 ───────────────────────────────────────────────
stage "构建与干跑（不发布）"
say "先把编译产物重新生成，再干跑一次打包看清单。"
node "$PKG_DIR/build.mjs"
say "编译产物："
ls -1 "$PKG_DIR/dist"
[[ -f "$PKG_DIR/dist/node.js" ]] || { warn "dist/node.js 没生成，先解决构建问题"; exit 1; }
say "干跑打包清单（重点看有没有 dist/node.js，以及共几个文件）："
(cd "$PKG_DIR" && npm publish --dry-run --registry="$REGISTRY" 2>&1 | sed -n '1,40p') || true
note "清单里应含 dist/node.js、共 11 个文件、发布目标为官方源。"
pause "看清楚了按回车"

# ── 第五段：真正发布 ─────────────────────────────────────────────────────
stage "正式发布（不可逆）"
say "要发的是：$PKG_NAME@$NEW_VERSION → $REGISTRY"
warn "npm 发布之后不能撤销（只能弃用），所以这一步只走一次。"
if ! confirm "现在真的发布？"; then
  warn "已取消，什么都没发"
  exit 1
fi
note "若 npm 要求一次性动态码（6 位数字），把它粘贴到这里再按回车；不需要就直接按回车。"
ask_secret OTP "一次性动态码（可留空）："
cd "$PKG_DIR"
if [[ -n "${OTP:-}" ]]; then
  npm publish --registry="$REGISTRY" --otp="$OTP"
else
  npm publish --registry="$REGISTRY"
fi
printf '  %s✓ 发布命令已返回%s\n' "$GREEN" "$RESET"

# ── 第六段：发布后验证 ───────────────────────────────────────────────────
stage "发布后验证"
PUBLISHED=$(npm view "$PKG_NAME" version --registry="$REGISTRY" 2>/dev/null | tail -n1 || true)
say "官方源上现在的最新版本：${PUBLISHED:-（查不到）}"
[[ "$PUBLISHED" == "$NEW_VERSION" ]] || warn "源上的版本与本次要发的不一致，自己看一眼"
PROBE=$(mktemp -d)
( cd "$PROBE" \
  && npm init -y >/dev/null 2>&1 \
  && npm install "$PKG_NAME@$PUBLISHED" --registry="$REGISTRY" >/dev/null 2>&1 \
  && node -e "
const { createNodeHostLog } = require('$PKG_NAME/node')
console.log('从官方源装包后，入口可用：', typeof createNodeHostLog === 'function')
" )
rm -rf "$PROBE"
if [[ -f "$PKG_DIR/$DRILL_FILE" ]]; then
  if grep -q '包名：dsh-log' "$PKG_DIR/$DRILL_FILE" 2>/dev/null; then
    sed "s/  - 版本：0\.1\.0/  - 版本：$NEW_VERSION/" "$PKG_DIR/$DRILL_FILE" > "$PKG_DIR/$DRILL_FILE.tmp"
    mv "$PKG_DIR/$DRILL_FILE.tmp" "$PKG_DIR/$DRILL_FILE"
    say "发布演练记录里的版本号已同步为 $NEW_VERSION"
  fi
fi
say "还差一步（发布真实证据刚拿到）：把 npm publish 的原始输出补进 $DRILL_FILE 的引用块里。"
pause "全部结束，按回车收尾"

finish
