// AUTO-GENERATED by node version-control-core/build.mjs — DO NOT EDIT. Source: version-control-core/src/capabilities.ts
export const VERSION_FLOOR = { major: 2, minor: 11, patch: 0 };
export const LOCK_PRUNABLE_FLOOR = { major: 2, minor: 31, patch: 0 };
export function parseVersion(text) {
  const m = /(\d+)\.(\d+)(?:\.(\d+))?/.exec(String(text || ""));
  if (!m) return null;
  return { major: Number(m[1]), minor: Number(m[2]), patch: m[3] === void 0 ? 0 : Number(m[3]) };
}
function atLeast(v, floor) {
  if (v.major !== floor.major) return v.major > floor.major;
  if (v.minor !== floor.minor) return v.minor > floor.minor;
  return v.patch >= floor.patch;
}
export function tierFor(v) {
  if (!v) return "unsupported";
  if (!atLeast(v, VERSION_FLOOR)) return "unsupported";
  if (!atLeast(v, LOCK_PRUNABLE_FLOOR)) return "degraded";
  return "full";
}
export const CAPABILITIES_SOURCE = "version-control-core/src/capabilities.ts";
