// AUTO-GENERATED by node version-control-core/build.mjs — DO NOT EDIT. Source: version-control-core/src/commands.ts
export const COLLECTION_KEYS = ["status", "worktrees", "refs", "log", "diffFiles", "patch"];
export const FIRST_SCREEN_KEYS = ["status", "worktrees", "refs", "log", "diffFiles"];
export const RUNNING_MARKER_PATHS = [
  "MERGE_HEAD",
  "CHERRY_PICK_HEAD",
  "REVERT_HEAD",
  "rebase-merge",
  "rebase-apply"
];
export function fixedPrefix() {
  return [
    "--no-optional-locks",
    "-c",
    "core.quotepath=false",
    "-c",
    "color.ui=false",
    "-c",
    "i18n.logOutputEncoding=UTF-8"
  ];
}
export function stepZeroArgs() {
  return ["rev-parse", "--absolute-git-dir", "--is-inside-work-tree", "--is-bare-repository"];
}
export const REV_PATTERN = /^[0-9a-fA-F]{4,64}$/;
export function commandFor(key, opts) {
  switch (key) {
    case "status":
      return { key, subcommand: "status", args: ["status", "--porcelain=v2", "--branch", "-z", "--untracked-files=all", "--find-renames"] };
    case "worktrees":
      if (opts.useNulWorktrees === false) return { key, subcommand: "worktree", args: ["worktree", "list", "--porcelain"] };
      return { key, subcommand: "worktree", args: ["worktree", "list", "--porcelain", "-z"] };
    case "refs":
      return { key, subcommand: "for-each-ref", args: ["for-each-ref", "--format=%(refname)%00%(refname:short)%00%(objectname)%00%(upstream:short)%00%(upstream:track)%00%(HEAD)%00%(committerdate:iso-strict)", "refs/heads/"] };
    case "log": {
      const n = opts.logCount === void 0 ? 50 : opts.logCount;
      const skip = opts.logSkip === void 0 ? 0 : opts.logSkip;
      return { key, subcommand: "log", args: ["log", "--no-decorate", "-z", "--format=%H%x00%h%x00%an%x00%ae%x00%aI%x00%cI%x00%s%x00%P%x00", "-n", String(n), "--skip=" + String(skip)] };
    }
    case "diffFiles":
      if (opts.rev !== void 0) return { key, subcommand: "show", args: ["show", "--numstat", "-z", "--no-ext-diff", "--find-renames", "--format=", opts.rev] };
      return { key, subcommand: "diff", args: ["diff", "--numstat", "-z", "--no-ext-diff", "--find-renames", "HEAD"] };
    case "patch": {
      const p = opts.patchPath === void 0 ? "" : opts.patchPath;
      if (opts.rev !== void 0) return { key, subcommand: "show", args: ["show", "--unified=3", "--no-color", "--no-ext-diff", "--no-prefix", "--find-renames", "--format=", opts.rev, "--", p] };
      return { key, subcommand: "diff", args: ["diff", "--unified=3", "--no-color", "--no-ext-diff", "--no-prefix", "--find-renames", "HEAD", "--", p] };
    }
  }
}
export function autocrlfArgs() {
  return ["config", "--get", "core.autocrlf"];
}
export const COMMANDS_SOURCE = "version-control-core/src/commands.ts";
