// AUTO-GENERATED by node version-control-core/build.mjs — DO NOT EDIT. Source: version-control-core/src/parse-refs.ts
function fail(detail) {
  return { ok: false, error: "refs-malformed", detail };
}
function parseTrack(track) {
  if (track === "") return { gone: false, ahead: 0, behind: 0 };
  if (track === "[gone]") return { gone: true, ahead: 0, behind: 0 };
  let m = /^\[ahead (\d+)\]$/.exec(track);
  if (m) return { gone: false, ahead: Number(m[1]), behind: 0 };
  m = /^\[behind (\d+)\]$/.exec(track);
  if (m) return { gone: false, ahead: 0, behind: Number(m[1]) };
  m = /^\[ahead (\d+), behind (\d+)\]$/.exec(track);
  if (m) return { gone: false, ahead: Number(m[1]), behind: Number(m[2]) };
  return null;
}
export function parseRefs(stdout) {
  const text = String(stdout);
  if (text === "") return { ok: true, refs: [] };
  const lines = text.split("\n");
  if (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  const out = [];
  for (const ln of lines) {
    const parts = ln.split("\0");
    if (parts.length !== 7) return fail("\u5B57\u6BB5\u6570\u4E0D\u662F 7");
    const [ref, short, oid, upstreamShort, trackRaw, headMark, dateRaw] = parts;
    if (!ref.startsWith("refs/heads/")) return fail("refname \u4E0D\u5728 refs/heads \u4E0B");
    if (!short) return fail("short \u4E3A\u7A7A");
    if (!/^[0-9a-f]{40}$/.test(oid) && !/^[0-9a-f]{64}$/.test(oid)) return fail("objectname \u975E\u54C8\u5E0C");
    const track = parseTrack(trackRaw);
    if (!track) return fail("upstream:track \u53D6\u503C\u672A\u77E5");
    const head = headMark.trim();
    if (head !== "" && head !== "*") return fail("HEAD \u5B57\u6BB5\u4E0D\u662F\u661F\u53F7\u6216\u7A7A");
    const ms = Date.parse(dateRaw);
    if (Number.isNaN(ms)) return fail("committerdate \u975E ISO \u65E5\u671F");
    out.push({
      ref,
      short,
      oid,
      upstream: upstreamShort === "" ? null : upstreamShort,
      upstreamGone: track.gone,
      ahead: track.ahead,
      behind: track.behind,
      current: head === "*",
      commitDateMs: ms
    });
  }
  return { ok: true, refs: out };
}
export const PARSE_REFS_SOURCE = "version-control-core/src/parse-refs.ts";
