// AUTO-GENERATED by node version-control-core/build.mjs — DO NOT EDIT. Source: version-control-core/src/parse-status.ts
const HEX = /^[0-9a-f]+$/;
function fail(detail) {
  return { ok: false, error: "status-malformed", detail };
}
function splitFixedFields(record, fixedCount) {
  const parts = [];
  let start = 0;
  for (let k = 0; k < fixedCount; k += 1) {
    const sp = record.indexOf(" ", start);
    if (sp < 0) return null;
    parts.push(record.slice(start, sp));
    start = sp + 1;
  }
  parts.push(record.slice(start));
  return parts;
}
export function parseStatus(stdout) {
  const fields = String(stdout).split("\0");
  if (fields.length > 0 && fields[fields.length - 1] === "") fields.pop();
  const branch = { head: "", detached: false, oid: null, upstream: null, ahead: 0, behind: 0 };
  let sawHead = false;
  const entries = [];
  let i = 0;
  while (i < fields.length) {
    const f = fields[i];
    i += 1;
    if (f === "") return fail("\u7A7A\u8BB0\u5F55");
    if (f.charAt(0) === "#") {
      const line = f;
      if (line.startsWith("# branch.head ")) {
        sawHead = true;
        const v = line.slice("# branch.head ".length);
        if (v === "(detached)") {
          branch.head = "(detached)";
          branch.detached = true;
        } else {
          branch.head = v;
        }
      } else if (line.startsWith("# branch.oid ")) {
        const v = line.slice("# branch.oid ".length);
        branch.oid = v === "(initial)" ? null : v;
        if (branch.oid !== null && !HEX.test(branch.oid)) return fail("branch.oid \u975E\u5341\u516D\u8FDB\u5236");
      } else if (line.startsWith("# branch.upstream ")) {
        branch.upstream = line.slice("# branch.upstream ".length) || null;
      } else if (line.startsWith("# branch.ab ")) {
        const m = /^# branch\.ab \+(\d+) -(\d+)$/.exec(line);
        if (!m) return fail("branch.ab \u5F62\u72B6\u4E0D\u5BF9");
        branch.ahead = Number(m[1]);
        branch.behind = Number(m[2]);
      }
      continue;
    }
    const tag = f.charAt(0);
    if (tag === "1") {
      const parts = splitFixedFields(f, 8);
      if (!parts) return fail("1 \u8BB0\u5F55\u56FA\u5B9A\u5B57\u6BB5\u4E0D\u8DB3 8 \u9879");
      const xy = parts[1];
      if (!/^[.MTAUDRC]{2}$/.test(xy)) return fail("1 \u8BB0\u5F55 XY \u975E\u6CD5");
      if (parts[8] === "") return fail("1 \u8BB0\u5F55\u8DEF\u5F84\u4E3A\u7A7A");
      entries.push({ kind: "ordinary", x: xy.charAt(0), y: xy.charAt(1), path: parts[8], origPath: null });
    } else if (tag === "2") {
      const parts = splitFixedFields(f, 9);
      if (!parts) return fail("2 \u8BB0\u5F55\u56FA\u5B9A\u5B57\u6BB5\u4E0D\u8DB3 9 \u9879");
      const xy = parts[1];
      if (!/^[.MTAUDRC]{2}$/.test(xy)) return fail("2 \u8BB0\u5F55 XY \u975E\u6CD5");
      if (parts[9] === "") return fail("2 \u8BB0\u5F55\u8DEF\u5F84\u4E3A\u7A7A");
      if (i >= fields.length) return fail("2 \u8BB0\u5F55\u7F3A\u539F\u8DEF\u5F84\u5B57\u6BB5");
      const orig = fields[i];
      i += 1;
      if (orig === "") return fail("2 \u8BB0\u5F55\u539F\u8DEF\u5F84\u4E3A\u7A7A");
      entries.push({ kind: "renamed", x: xy.charAt(0), y: xy.charAt(1), path: parts[9], origPath: orig });
    } else if (tag === "u") {
      const parts = splitFixedFields(f, 10);
      if (!parts) return fail("u \u8BB0\u5F55\u56FA\u5B9A\u5B57\u6BB5\u4E0D\u8DB3 10 \u9879");
      const xy = parts[1];
      if (xy.length !== 2) return fail("u \u8BB0\u5F55 XY \u975E\u6CD5");
      if (parts[10] === "") return fail("u \u8BB0\u5F55\u8DEF\u5F84\u4E3A\u7A7A");
      entries.push({ kind: "unmerged", x: xy.charAt(0), y: xy.charAt(1), path: parts[10], origPath: null });
    } else if (tag === "?") {
      if (f.charAt(1) !== " ") return fail("? \u8BB0\u5F55\u7F3A\u5C11\u7A7A\u683C");
      entries.push({ kind: "untracked", x: "?", y: "?", path: f.slice(2), origPath: null });
    } else if (tag === "!") {
      if (f.charAt(1) !== " ") return fail("! \u8BB0\u5F55\u7F3A\u5C11\u7A7A\u683C");
      entries.push({ kind: "ignored", x: "!", y: "!", path: f.slice(2), origPath: null });
    } else {
      return fail("\u672A\u77E5\u884C\u9996\u5B57\u7B26 " + JSON.stringify(tag));
    }
  }
  if (!sawHead) return fail("\u7F3A # branch.head \u884C");
  return { ok: true, branch, entries };
}
export const PARSE_STATUS_SOURCE = "version-control-core/src/parse-status.ts";
