// AUTO-GENERATED by node version-control-core/build.mjs — DO NOT EDIT. Source: version-control-core/src/parse-patch.ts
const HEADER_PREFIXES = [
  "diff --git ",
  "index ",
  "--- ",
  "+++ ",
  "new file mode ",
  "deleted file mode ",
  "old mode ",
  "new mode ",
  "similarity index ",
  "rename from ",
  "rename to ",
  "Binary files "
];
export function parsePatch(stdout) {
  const text = String(stdout);
  const raw = text.split("\n");
  if (raw.length > 0 && raw[raw.length - 1] === "") raw.pop();
  const out = [];
  for (const ln of raw) {
    if (ln.startsWith("@@")) out.push({ kind: "hunk", text: ln });
    else if (HEADER_PREFIXES.some((p) => ln.startsWith(p))) out.push({ kind: "filehead", text: ln });
    else if (ln.startsWith("\\ ")) out.push({ kind: "no-newline", text: ln });
    else if (ln.startsWith("+")) out.push({ kind: "add", text: ln });
    else if (ln.startsWith("-")) out.push({ kind: "del", text: ln });
    else if (ln.startsWith(" ") || ln === "") out.push({ kind: "context", text: ln });
    else return { ok: false, error: "patch-malformed", detail: "\u672A\u77E5\u5DEE\u5F02\u884C\u9996\u5B57\u7B26" };
  }
  return { ok: true, lines: out };
}
export const PARSE_PATCH_SOURCE = "version-control-core/src/parse-patch.ts";
