// AUTO-GENERATED by node version-control-core/build.mjs — DO NOT EDIT. Source: version-control-core/src/parse-log.ts
function fail(detail) {
  return { ok: false, error: "log-malformed", detail };
}
export function parseLog(stdout) {
  const text = String(stdout);
  if (text === "") return { ok: true, commits: [] };
  const fields = text.split("\0");
  if (fields.length > 0 && fields[fields.length - 1] === "") fields.pop();
  let stride = 8;
  if (fields.length % 9 === 0 && fields.every((f, idx) => idx % 9 !== 8 || f === "")) {
    stride = 9;
  } else if (fields.length % 8 !== 0) {
    return fail("\u5B57\u6BB5\u603B\u6570\u4E0D\u662F 8 \u6216 9 \u7684\u500D\u6570");
  }
  const out = [];
  for (let i = 0; i < fields.length; i += stride) {
    const [oid, short, author, email, aI, cI, subject, parentsRaw] = fields.slice(i, i + 8);
    if (!/^[0-9a-f]{40}$/.test(oid) && !/^[0-9a-f]{64}$/.test(oid)) return fail("H \u975E\u54C8\u5E0C");
    if (!short) return fail("h \u4E3A\u7A7A");
    const aMs = Date.parse(aI);
    const cMs = Date.parse(cI);
    if (Number.isNaN(aMs) || Number.isNaN(cMs)) return fail("\u65E5\u671F\u975E ISO");
    const parents = parentsRaw === "" ? [] : parentsRaw.split(" ");
    for (const p of parents) {
      if (!/^[0-9a-f]{40}$/.test(p) && !/^[0-9a-f]{64}$/.test(p)) return fail("\u7236\u63D0\u4EA4\u975E\u54C8\u5E0C");
    }
    out.push({ oid, short, author, email, authorDateMs: aMs, commitDateMs: cMs, subject, parents });
  }
  return { ok: true, commits: out };
}
export const PARSE_LOG_SOURCE = "version-control-core/src/parse-log.ts";
