// AUTO-GENERATED by node version-control-core/build.mjs — DO NOT EDIT. Source: version-control-core/src/push-plan.ts
const REMOTE_PATTERN = /^(?!-)[A-Za-z0-9._/-]+$/;
const BRANCH_PATTERN = /^(?![-+])[^\s\u0000:\\]+$/;
export function pushPlanOf(input) {
  const branch = String(input.branch || "");
  const remotes = (Array.isArray(input.remotes) ? input.remotes : []).map((x) => String(x)).filter((x) => x !== "");
  const upstream = input.upstream ? String(input.upstream) : "";
  if (branch === "" || !BRANCH_PATTERN.test(branch)) return { ok: false, reason: "bad-target" };
  if (remotes.length === 0) return { ok: false, reason: "no-remote" };
  if (upstream !== "" && input.upstreamGone !== true) {
    let best = "";
    for (const r of remotes) {
      if (upstream.length > r.length + 1 && upstream.slice(0, r.length) === r && upstream.charAt(r.length) === "/") {
        if (r.length > best.length) best = r;
      }
    }
    if (best !== "") {
      const targetBranch = upstream.slice(best.length + 1);
      if (!BRANCH_PATTERN.test(targetBranch)) return { ok: false, reason: "bad-target" };
      return { ok: true, plan: { mode: "existing", setUpstream: false, remote: best, branch: targetBranch, localBranch: branch } };
    }
  }
  if (upstream !== "" && input.upstreamGone === true) {
    let best = "";
    for (const r of remotes) {
      if (upstream.length > r.length + 1 && upstream.slice(0, r.length) === r && upstream.charAt(r.length) === "/") {
        if (r.length > best.length) best = r;
      }
    }
    if (best !== "") {
      const targetBranch = upstream.slice(best.length + 1);
      if (!BRANCH_PATTERN.test(targetBranch)) return { ok: false, reason: "bad-target" };
      return { ok: true, plan: { mode: "recreate", setUpstream: true, remote: best, branch: targetBranch, localBranch: branch } };
    }
  }
  const wanted = input.requestedRemote ? String(input.requestedRemote) : "";
  if (wanted !== "") {
    if (!REMOTE_PATTERN.test(wanted) || remotes.indexOf(wanted) < 0) return { ok: false, reason: "bad-target" };
    return { ok: true, plan: { mode: "set-upstream", setUpstream: true, remote: wanted, branch, localBranch: branch } };
  }
  if (remotes.length === 1) return { ok: true, plan: { mode: "set-upstream", setUpstream: true, remote: remotes[0], branch, localBranch: branch } };
  return { ok: false, reason: "need-remote-choice", candidates: remotes.slice() };
}
export const PUSH_PLAN_SOURCE = "version-control-core/src/push-plan.ts";
