// AUTO-GENERATED by node version-control-core/build.mjs — DO NOT EDIT. Source: version-control-core/src/rules.ts
export const REASONS = {
  "ok": "ok",
  "nothing-to-stage": "nothing-to-stage",
  "nothing-staged": "nothing-staged",
  "no-upstream": "no-upstream",
  "upstream-gone": "upstream-gone",
  "detached-head": "detached-head",
  "conflicts-unresolved": "conflicts-unresolved",
  "mid-merge": "mid-merge",
  "mid-rebase": "mid-rebase",
  "mid-cherry-revert": "mid-cherry-revert",
  "dirty-tree": "dirty-tree",
  "behind-remote": "behind-remote",
  "basis-unknown": "basis-unknown",
  "bare-repo": "bare-repo",
  "unknown-operation": "unknown-operation"
};
function midReasons(s) {
  const out = [];
  if (s.repo.merging) out.push("mid-merge");
  if (s.repo.rebasing) out.push("mid-rebase");
  if (s.repo.cherryPicking || s.repo.reverting) out.push("mid-cherry-revert");
  return out;
}
function judgeStage(s) {
  if (s.repo.bare) return { verdict: "block", reasons: ["bare-repo"] };
  if (s.unstagedCount === 0) return { verdict: "block", reasons: ["nothing-to-stage"] };
  const mid = midReasons(s);
  if (mid.length > 0) return { verdict: "warn", reasons: mid };
  return { verdict: "allow", reasons: ["ok"] };
}
function judgeCommit(s) {
  if (s.repo.bare) return { verdict: "block", reasons: ["bare-repo"] };
  if (s.conflictCount > 0) return { verdict: "block", reasons: ["conflicts-unresolved"] };
  if (s.stagedCount === 0) return { verdict: "block", reasons: ["nothing-staged"] };
  const mid = midReasons(s);
  if (s.identity.detached) return { verdict: "warn", reasons: ["detached-head"].concat(mid) };
  if (mid.length > 0) return { verdict: "warn", reasons: mid };
  return { verdict: "allow", reasons: ["ok"] };
}
function judgePull(s) {
  if (s.repo.bare) return { verdict: "block", reasons: ["bare-repo"] };
  if (s.identity.detached) return { verdict: "block", reasons: ["detached-head"] };
  if (s.identity.sync === "no-upstream") return { verdict: "block", reasons: ["no-upstream"] };
  if (s.identity.sync === "upstream-gone") return { verdict: "block", reasons: ["upstream-gone"] };
  if (s.conflictCount > 0) return { verdict: "block", reasons: ["conflicts-unresolved"] };
  const mid = midReasons(s);
  if (mid.length > 0) return { verdict: "block", reasons: mid };
  if (s.stagedCount > 0 || s.unstagedCount > 0) return { verdict: "block", reasons: ["dirty-tree"] };
  if (s.identity.basisMs === null) return { verdict: "warn", reasons: ["basis-unknown"] };
  return { verdict: "allow", reasons: ["ok"] };
}
function judgePush(s) {
  if (s.repo.bare) return { verdict: "block", reasons: ["bare-repo"] };
  if (s.identity.detached) return { verdict: "block", reasons: ["detached-head"] };
  if (s.identity.sync === "no-upstream") return { verdict: "block", reasons: ["no-upstream"] };
  if (s.identity.sync === "upstream-gone") return { verdict: "block", reasons: ["upstream-gone"] };
  if (s.conflictCount > 0) return { verdict: "block", reasons: ["conflicts-unresolved"] };
  const mid = midReasons(s);
  if (mid.length > 0) return { verdict: "block", reasons: mid };
  if (s.identity.behind > 0) return { verdict: "block", reasons: ["behind-remote"] };
  if (s.identity.basisMs === null) return { verdict: "warn", reasons: ["basis-unknown"] };
  return { verdict: "allow", reasons: ["ok"] };
}
function judgeFetch(s) {
  if (s.repo.bare) return { verdict: "block", reasons: ["bare-repo"] };
  return { verdict: "allow", reasons: ["ok"] };
}
export function judge(screen, op) {
  switch (op) {
    case "stage":
      return judgeStage(screen);
    case "commit":
      return judgeCommit(screen);
    case "pull":
      return judgePull(screen);
    case "push":
      return judgePush(screen);
    case "fetch":
      return judgeFetch(screen);
    default:
      return { verdict: "block", reasons: ["unknown-operation"] };
  }
}
export const RULES_SOURCE = "version-control-core/src/rules.ts";
