// AUTO-GENERATED by node version-control-core/build.mjs — DO NOT EDIT. Source: version-control-core/src/state.ts
function fail(detail) {
  return { ok: false, error: "state-assemble-failed", detail };
}
export function shortestUniqueSuffix(paths) {
  const segs = paths.map((p) => String(p).split("/").filter((s) => s !== ""));
  return segs.map((s, i) => {
    for (let n = 1; n <= s.length; n += 1) {
      const tail = s.slice(-n).join("/");
      let clash = false;
      for (let j = 0; j < segs.length; j += 1) {
        if (j === i) continue;
        if (segs[j].slice(-n).join("/") === tail) {
          clash = true;
          break;
        }
      }
      if (!clash) return n;
    }
    return s.length;
  });
}
function sameWorktreePath(a, b) {
  const norm = (p) => String(p).replace(/\/+$/, "");
  return norm(a) === norm(b);
}
export function displayFor(path, keep) {
  const segs = String(path).split("/").filter((s) => s !== "");
  return segs.slice(-Math.max(1, keep)).join("/");
}
export function foldMiddle(path, maxLen) {
  const p = String(path);
  if (p.length <= maxLen || maxLen < 10) return p;
  const keep = maxLen - 1;
  const headLen = Math.ceil(keep * 0.4);
  return p.slice(0, headLen) + "\u2026" + p.slice(p.length - (keep - headLen));
}
export function describeTime(nowMs, tMs) {
  const diff = nowMs - tMs;
  if (diff >= 0 && diff < 7 * 24 * 3600 * 1e3) return { style: "relative", minutes: Math.max(0, Math.floor(diff / 6e4)) };
  return { style: "absolute", ms: tMs };
}
function toChange(e) {
  if (e.kind === "untracked") return { change: "untracked", conflict: false };
  if (e.kind === "unmerged") return { change: "modified", conflict: true };
  if (e.kind === "renamed") return { change: "renamed", conflict: false };
  if (e.kind === "ignored") return { change: "modified", conflict: false };
  if (e.x === "A" || e.y === "A") return { change: "added", conflict: false };
  if (e.x === "D" || e.y === "D") return { change: "deleted", conflict: false };
  if (e.x === "T" || e.y === "T") return { change: "typechange", conflict: false };
  return { change: "modified", conflict: false };
}
function rankFor(f) {
  if (f.staged) return 0;
  if (f.conflict) return 1;
  return 2;
}
export function assemble(input) {
  if (input.bare) {
    const repo2 = { merging: false, rebasing: false, cherryPicking: false, reverting: false, hasCommits: input.commits.length > 0, bare: true, tier: input.tier, autocrlf: input.autocrlf };
    const identity2 = { worktreeDisplay: "", worktreePath: input.repoRoot, branch: null, detached: false, oid: null, sync: "detached", ahead: 0, behind: 0, basisMs: null };
    return { ok: true, screen: { identity: identity2, staged: [], unstaged: [], stagedCount: 0, unstagedCount: 0, conflictCount: 0, otherWorktrees: [], branches: [], commits: [], repo: repo2 } };
  }
  const counts = /* @__PURE__ */ new Map();
  for (const d of input.diffFiles) counts.set(d.path, d);
  const files = [];
  for (const e of input.statusEntries) {
    if (e.kind === "ignored") continue;
    const { change, conflict } = toChange(e);
    const c = counts.get(e.path);
    files.push({
      path: e.path,
      origPath: e.origPath,
      staged: e.x !== "." && e.x !== "?" && e.x !== "!",
      unstaged: e.y !== "." && e.y !== "?" && e.y !== "!",
      change,
      conflict,
      addedLines: c ? c.added : null,
      deletedLines: c ? c.deleted : null
    });
  }
  files.sort((a, b) => rankFor(a) - rankFor(b) || (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  const staged = files.filter((f) => f.staged);
  const unstaged = files.filter((f) => f.unstaged || f.change === "untracked");
  const allPaths = input.worktrees.map((w) => w.path);
  const keeps = shortestUniqueSuffix(allPaths.length > 0 ? allPaths : [input.repoRoot]);
  let currentPath = input.repoRoot;
  const byPath = input.worktrees.find((w) => sameWorktreePath(w.path, input.repoRoot));
  if (byPath) currentPath = byPath.path;
  else if (!input.statusDetached && input.statusHead) {
    const hit = input.worktrees.find((w) => w.branch === input.statusHead);
    if (hit) currentPath = hit.path;
  } else if (input.statusDetached && input.statusOid) {
    const hit = input.worktrees.find((w) => w.head === input.statusOid);
    if (hit) currentPath = hit.path;
  }
  let sync = "no-upstream";
  if (input.statusDetached) sync = "detached";
  else if (!input.statusUpstream) sync = "no-upstream";
  else {
    const ref = input.refs.find((r) => r.short === input.statusHead);
    if (ref && ref.upstreamGone) sync = "upstream-gone";
    else if (input.basisMs === null) sync = "tracked-stale";
    else sync = "tracked-fresh";
  }
  const identity = {
    worktreeDisplay: displayFor(currentPath, keeps[Math.max(0, allPaths.indexOf(currentPath))] || 1),
    worktreePath: currentPath,
    branch: input.statusDetached ? null : input.statusHead,
    detached: input.statusDetached,
    oid: input.statusOid,
    sync,
    ahead: input.statusAhead,
    behind: input.statusBehind,
    basisMs: input.basisMs
  };
  const others = input.worktrees.filter((w) => w.path !== currentPath).map((w) => ({
    path: w.path,
    display: displayFor(w.path, keeps[Math.max(0, allPaths.indexOf(w.path))] || 1),
    head: w.head || "",
    branch: w.branch,
    bare: w.bare,
    current: false,
    locked: w.locked,
    lockReason: w.lockReason,
    lockUnknown: input.tier !== "full" && !w.locked,
    prunable: w.prunable
  }));
  const commits = input.commits.map((c) => ({
    oid: c.oid,
    short: c.short,
    author: c.author,
    email: c.email,
    authorDateMs: c.authorDateMs,
    commitDateMs: c.commitDateMs,
    subject: c.subject,
    parents: c.parents
  }));
  const branches = input.refs.map((r) => ({
    short: r.short,
    oid: r.oid,
    upstream: r.upstream,
    upstreamGone: r.upstreamGone,
    ahead: r.ahead,
    behind: r.behind,
    current: r.short === input.statusHead && !input.statusDetached
  }));
  const repo = {
    merging: input.merging,
    rebasing: input.rebasing,
    cherryPicking: input.cherryPicking,
    reverting: input.reverting,
    hasCommits: input.statusOid !== null || commits.length > 0,
    bare: false,
    tier: input.tier,
    autocrlf: input.autocrlf
  };
  return {
    ok: true,
    screen: {
      identity,
      staged,
      unstaged,
      stagedCount: staged.length,
      unstagedCount: unstaged.length,
      conflictCount: files.filter((f) => f.conflict).length,
      otherWorktrees: others,
      branches,
      commits,
      repo
    }
  };
}
export function classifyStepZero(exitCode, stdout, stderr) {
  if (exitCode !== 0) {
    if (/not a git repository/.test(stderr)) return { ok: true, kind: "not-repo" };
    return { ok: false, error: "step-zero-failed", detail: "exit " + exitCode };
  }
  const lines = String(stdout).split("\n").filter((l) => l !== "");
  if (lines.length < 3) return { ok: false, error: "step-zero-failed", detail: "\u884C\u6570\u4E0D\u8DB3 3" };
  const gitDir = lines[0];
  const inside = lines[1];
  const bare = lines[2];
  if (inside !== "true" && inside !== "false" || bare !== "true" && bare !== "false") {
    return { ok: false, error: "step-zero-failed", detail: "\u5E03\u5C14\u884C\u975E\u6CD5" };
  }
  if (bare === "true") return { ok: true, kind: "bare", gitDir };
  if (inside === "true") return { ok: true, kind: "worktree", gitDir };
  return { ok: false, error: "step-zero-failed", detail: "\u65E2\u4E0D\u5728\u5DE5\u4F5C\u6811\u4E5F\u4E0D\u662F\u88F8\u4ED3\u5E93" };
}
export const STATE_SOURCE = "version-control-core/src/state.ts";
