// 派生文件（#586）：由 packages/dsh-plugin-update/dist/config.js 原样复制，内容与更新包 0.1.1 一致，人手不改。
// 旧实现（src/host/update.js、updateReader.js、updateStore.js）原地只读留存；运行时走本目录经 updateFromPackage.js 接线。
// 共存关系：旧文件只读、新文件派生，真搬迁或真删除旧文件另开票。重新生成：node scripts/derive-update-from-package.mjs。
// AUTO-GENERATED by node packages/dsh-plugin-update/build.mjs — DO NOT EDIT. Source: packages/dsh-plugin-update/src/config.ts
const DEFAULT_PREFIX = "wf";
const PHONE_ACTIONS = ["updateStatus", "updateCheck", "updateInstall"];
const DEFAULT_TARGET_PACKAGE = "dsh-mattpocock-skills-deck";
const DEFAULT_REGISTRY = "https://registry.npmjs.org/";
const LEGACY_PLUGIN_ID = "dsh-mattpocock-skills-deck";
const LEGACY_DIR_SEGMENT = "updates";
const STATE_FILE = "state.json";
const LOCK_FILE = "install.lock";
const BACKUP_FILE = "before.json";
const DEFAULT_CHECK_TIMEOUT_MS = 1e4;
const DEFAULT_CONFIRMATION_TTL_MS = 10 * 6e4;
const DEFAULT_INSTALL_TIMEOUT_MS = 15 * 6e4;
const DEFAULT_PANEL_POLL_MS = 1e3;
const RECHECK_WINDOW_MS = 2e3;
const MIN_PANEL_POLL_MS = 250;
function assertPluginId(value) {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error("[dsh-plugin-update] \u63D2\u4EF6\u6807\u8BC6 pluginId \u5FC5\u586B\uFF1A\u987B\u4E3A\u975E\u7A7A\u5B57\u7B26\u4E32\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  if (value.includes("/") || value.includes("\\") || value.includes("\0")) {
    throw new Error("[dsh-plugin-update] \u63D2\u4EF6\u6807\u8BC6 pluginId \u975E\u6CD5\uFF1A\u4E0D\u5F97\u542B\u6709\u8DEF\u5F84\u5206\u9694\u7B26\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  return value;
}
function assertPrefix(value, role) {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error("[dsh-plugin-update] " + role + " \u975E\u6CD5\uFF1A\u987B\u4E3A\u975E\u7A7A\u5B57\u7B26\u4E32\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  if (value.includes(".") || value.includes("/") || value.includes("\\") || /\s/.test(value)) {
    throw new Error("[dsh-plugin-update] " + role + " \u975E\u6CD5\uFF1A\u4E0D\u5F97\u542B\u6709\u70B9\u3001\u8DEF\u5F84\u5206\u9694\u7B26\u6216\u7A7A\u767D\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  return value;
}
function assertPositiveFinite(value, role) {
  if (typeof value !== "number" || !Number.isFinite(value) || value <= 0) {
    throw new Error("[dsh-plugin-update] " + role + " \u975E\u6CD5\uFF1A\u987B\u4E3A\u6709\u9650\u5927\u4E8E 0 \u7684\u6570\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09");
  }
  return value;
}
function resolveUpdateConfig(input) {
  if (!input || typeof input !== "object") {
    throw new Error("[dsh-plugin-update] \u5EFA\u66F4\u65B0\u80FD\u529B\u7F3A\u5C11\u914D\u7F6E\uFF1A\u63D2\u4EF6\u6807\u8BC6 pluginId \u5FC5\u586B");
  }
  const pluginId = assertPluginId(input.pluginId);
  const prefix = input.prefix === void 0 ? DEFAULT_PREFIX : assertPrefix(input.prefix, "\u7535\u8BDD\u540D\u524D\u7F00 prefix");
  const targetPackageName = input.targetPackageName === void 0 ? DEFAULT_TARGET_PACKAGE : String(input.targetPackageName);
  if (!targetPackageName) {
    throw new Error("[dsh-plugin-update] \u76EE\u6807\u5305\u540D targetPackageName \u975E\u6CD5\uFF1A\u987B\u4E3A\u975E\u7A7A\u5B57\u7B26\u4E32");
  }
  const registryUrl = input.registryUrl === void 0 ? DEFAULT_REGISTRY : String(input.registryUrl);
  if (!registryUrl) {
    throw new Error("[dsh-plugin-update] \u5B98\u65B9\u6E90 registryUrl \u975E\u6CD5\uFF1A\u987B\u4E3A\u975E\u7A7A\u5B57\u7B26\u4E32");
  }
  const homeDir = input.homeDir === void 0 ? null : String(input.homeDir);
  const checkTimeoutMs = input.checkTimeoutMs === void 0 ? DEFAULT_CHECK_TIMEOUT_MS : assertPositiveFinite(input.checkTimeoutMs, "\u8054\u7F51\u8D85\u65F6 checkTimeoutMs");
  const confirmationTtlMs = input.confirmationTtlMs === void 0 ? DEFAULT_CONFIRMATION_TTL_MS : assertPositiveFinite(input.confirmationTtlMs, "\u51ED\u8BC1\u6709\u6548\u671F confirmationTtlMs");
  const installTimeoutMs = input.installTimeoutMs === void 0 ? DEFAULT_INSTALL_TIMEOUT_MS : assertPositiveFinite(input.installTimeoutMs, "\u5B89\u88C5\u65F6\u9650 installTimeoutMs");
  const panelPollMs = input.panelPollMs === void 0 ? DEFAULT_PANEL_POLL_MS : assertPositiveFinite(input.panelPollMs, "\u9762\u677F\u8F6E\u8BE2 panelPollMs");
  if (panelPollMs < MIN_PANEL_POLL_MS) {
    throw new Error("[dsh-plugin-update] \u9762\u677F\u8F6E\u8BE2 panelPollMs \u975E\u6CD5\uFF1A\u4E0D\u5F97\u5C0F\u4E8E 250 \u6BEB\u79D2\uFF08\u6536\u5230 " + JSON.stringify(input.panelPollMs) + "\uFF09");
  }
  return { pluginId, prefix, targetPackageName, registryUrl, homeDir, checkTimeoutMs, confirmationTtlMs, installTimeoutMs, panelPollMs };
}
function buildPhoneNames(prefix) {
  const checked = assertPrefix(prefix, "\u7535\u8BDD\u540D\u524D\u7F00 prefix");
  return {
    updateStatus: checked + ".updateStatus",
    updateCheck: checked + ".updateCheck",
    updateInstall: checked + ".updateInstall"
  };
}
function buildPhoneName(prefix, action) {
  return buildPhoneNames(prefix)[action];
}
export {
  BACKUP_FILE,
  DEFAULT_CHECK_TIMEOUT_MS,
  DEFAULT_CONFIRMATION_TTL_MS,
  DEFAULT_INSTALL_TIMEOUT_MS,
  DEFAULT_PANEL_POLL_MS,
  DEFAULT_PREFIX,
  DEFAULT_REGISTRY,
  DEFAULT_TARGET_PACKAGE,
  LEGACY_DIR_SEGMENT,
  LEGACY_PLUGIN_ID,
  LOCK_FILE,
  MIN_PANEL_POLL_MS,
  PHONE_ACTIONS,
  RECHECK_WINDOW_MS,
  STATE_FILE,
  assertPluginId,
  assertPrefix,
  buildPhoneName,
  buildPhoneNames,
  resolveUpdateConfig
};
