// 派生文件（#586）：由 packages/dsh-plugin-update/dist/gate.js 原样复制，内容与更新包 0.1.1 一致，人手不改。
// 旧实现（src/host/update.js、updateReader.js、updateStore.js）原地只读留存；运行时走本目录经 updateFromPackage.js 接线。
// 共存关系：旧文件只读、新文件派生，真搬迁或真删除旧文件另开票。重新生成：node scripts/derive-update-from-package.mjs。
// AUTO-GENERATED by node packages/dsh-plugin-update/build.mjs — DO NOT EDIT. Source: packages/dsh-plugin-update/src/gate.ts
import { assertPluginId } from "./config.js";
const EVENT_LEVELS = ["error", "warn", "info", "debug"];
const EVENT_KINDS = ["resident", "ondemand", "selfmon"];
function isNonEmptyString(value) {
  return typeof value === "string" && value.length > 0;
}
function assertStringArray(value, what) {
  if (!Array.isArray(value)) throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A" + what + " \u5FC5\u987B\u662F\u5B57\u7B26\u4E32\u6570\u7EC4");
  const seen = [];
  for (const item of value) {
    if (!isNonEmptyString(item)) throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A" + what + " \u91CC\u6709\u7A7A\u5B57\u6BB5\u540D");
    if (seen.indexOf(item) >= 0) throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A" + what + " \u91CC\u5B57\u6BB5\u540D\u91CD\u590D\uFF1A" + item);
    seen.push(item);
  }
  return seen;
}
function parseEventListManifest(value) {
  if (typeof value === "string") {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u8DEF\u5F84\u5F62\u5F0F\u8BF7\u8C03\u7528\u65B9\u81EA\u5DF1\u8BFB\u6210\u5BF9\u8C61\u518D\u4F20\u5165\uFF0C\u66F4\u65B0\u5305\u4E0D\u8BFB\u76D8");
  }
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u53EA\u6536\u5BF9\u8C61\u5F62\u5F0F\uFF08\u7A7A\u6A21\u677F\u89C1\u5305\u5185\u7684 event-list.template.json\uFF09");
  }
  const input = value;
  if (input["version"] !== 1) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1Aversion \u73B0\u5728\u53EA\u8BA4 1\uFF08\u6536\u5230 " + JSON.stringify(input["version"]) + "\uFF09");
  }
  const pluginId = assertPluginId(input["pluginId"]);
  const countsRaw = input["counts"];
  if (!countsRaw || typeof countsRaw !== "object" || Array.isArray(countsRaw)) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1Acounts \u5FC5\u987B\u662F\u542B\u4E09\u7C7B\u8BA1\u6570\u7684\u5BF9\u8C61");
  }
  const countsRecord = countsRaw;
  const counts = { resident: 0, ondemand: 0, selfmon: 0 };
  for (const kind of EVENT_KINDS) {
    const n = countsRecord[kind];
    if (typeof n !== "number" || !isFinite(n) || Math.floor(n) !== n || n < 0) {
      throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1Acounts." + kind + " \u5FC5\u987B\u662F\u975E\u8D1F\u6574\u6570");
    }
    counts[kind] = n;
  }
  const eventsRaw = input["events"];
  if (!eventsRaw || typeof eventsRaw !== "object" || Array.isArray(eventsRaw)) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1Aevents \u5FC5\u987B\u662F\u4E8B\u4EF6\u540D\u5230\u6761\u76EE\u7684\u5BF9\u8C61");
  }
  const events = {};
  for (const name of Object.keys(eventsRaw)) {
    events[name] = parseEventEntry(name, eventsRaw[name]);
  }
  return { version: 1, pluginId, counts, events };
}
function parseEventEntry(name, value) {
  if (!isNonEmptyString(name)) throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6\u540D\u4E0D\u80FD\u4E3A\u7A7A");
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u5FC5\u987B\u662F\u5BF9\u8C61");
  }
  const input = value;
  if (EVENT_LEVELS.indexOf(input["level"]) < 0) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u7684 level \u53EA\u8BB8 error\u3001warn\u3001info\u3001debug");
  }
  if (EVENT_KINDS.indexOf(input["kind"]) < 0) {
    throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u7684 kind \u53EA\u8BB8 resident\u3001ondemand\u3001selfmon");
  }
  for (const key of Object.keys(input)) {
    if (["level", "kind", "fields", "codes", "rules", "guard"].indexOf(key) < 0) {
      throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u6709\u4E0D\u8BA4\u8BC6\u7684\u952E " + key);
    }
  }
  const entry = {
    level: input["level"],
    kind: input["kind"],
    fields: assertStringArray(input["fields"], "\u4E8B\u4EF6 " + name + " \u7684 fields")
  };
  if (input["codes"] !== void 0) entry.codes = assertStringArray(input["codes"], "\u4E8B\u4EF6 " + name + " \u7684 codes");
  if (input["rules"] !== void 0) entry.rules = assertStringArray(input["rules"], "\u4E8B\u4EF6 " + name + " \u7684 rules");
  if (input["guard"] !== void 0) {
    if (typeof input["guard"] !== "string") {
      throw new Error("[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u7684 guard \u5FC5\u987B\u662F\u5B57\u7B26\u4E32");
    }
    entry.guard = input["guard"];
  }
  return entry;
}
function checkEventFields(manifest, eventName, fieldNames) {
  const entry = manifest.events[eventName];
  if (!entry) return { ok: false, unknownEvent: true, unknownFields: [] };
  const allowed = new Set(entry.fields);
  const unknownFields = (Array.isArray(fieldNames) ? fieldNames : []).filter(
    (field) => !allowed.has(field)
  );
  return { ok: unknownFields.length === 0, unknownEvent: false, unknownFields };
}
function checkEventCounts(manifest) {
  const actual = { resident: 0, ondemand: 0, selfmon: 0 };
  for (const name of Object.keys(manifest.events)) {
    actual[manifest.events[name].kind] += 1;
  }
  const problems = [];
  for (const kind of EVENT_KINDS) {
    if (actual[kind] !== manifest.counts[kind]) {
      problems.push(
        "[dsh-plugin-update] \u4E8B\u4EF6\u6E05\u5355\u8BA1\u6570\u5BF9\u4E0D\u4E0A\uFF1A" + kind + " \u7C7B\u5B9E\u9645 " + actual[kind] + " \u6761\uFF0C\u6E05\u5355\u81EA\u62A5 " + manifest.counts[kind] + " \u6761"
      );
    }
  }
  return { ok: problems.length === 0, problems };
}
export {
  EVENT_KINDS,
  EVENT_LEVELS,
  checkEventCounts,
  checkEventFields,
  parseEventListManifest
};
