// 派生文件（#586）：由 packages/dsh-plugin-update/dist/ports.js 原样复制，内容与更新包 0.1.1 一致，人手不改。
// 旧实现（src/host/update.js、updateReader.js、updateStore.js）原地只读留存；运行时走本目录经 updateFromPackage.js 接线。
// 共存关系：旧文件只读、新文件派生，真搬迁或真删除旧文件另开票。重新生成：node scripts/derive-update-from-package.mjs。
// AUTO-GENERATED by node packages/dsh-plugin-update/build.mjs — DO NOT EDIT. Source: packages/dsh-plugin-update/src/ports.ts
const PORTS_SOURCE = "packages/dsh-plugin-update/src/ports.ts";
export {
  PORTS_SOURCE
};
