// 派生文件（#586）：由 packages/dsh-plugin-update/dist/reader.js 原样复制，内容与更新包 0.1.1 一致，人手不改。
// 旧实现（src/host/update.js、updateReader.js、updateStore.js）原地只读留存；运行时走本目录经 updateFromPackage.js 接线。
// 共存关系：旧文件只读、新文件派生，真搬迁或真删除旧文件另开票。重新生成：node scripts/derive-update-from-package.mjs。
// AUTO-GENERATED by node packages/dsh-plugin-update/build.mjs — DO NOT EDIT. Source: packages/dsh-plugin-update/src/reader.ts
import { createHash, randomUUID } from "node:crypto";
import { readFile, realpath, stat } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { assertPluginId } from "./config.js";
import { createUpdateCore, validVersion } from "./service.js";
const LOCK_FILES = ["pnpm-lock.yaml", "pnpm-workspace.yaml", "package-lock.json"];
function inside(directory, filename) {
  const suffix = relative(directory, filename);
  return suffix !== ".." && !suffix.startsWith(`..${sep}`) && !isAbsolute(suffix);
}
async function readOptional(filename) {
  try {
    return await readFile(filename, "utf8");
  } catch (error) {
    if (error && error.code === "ENOENT") return "";
    throw error;
  }
}
async function packageAt(directory) {
  const contents = await readFile(join(directory, "package.json"), "utf8");
  return { directory: await realpath(directory), manifest: JSON.parse(contents), contents };
}
async function containingPackage(filename, name) {
  let directory = dirname(await realpath(filename));
  while (true) {
    try {
      const found = await packageAt(directory);
      if (found.manifest && found.manifest.name === name) return found;
    } catch (error) {
      if (!error || error.code !== "ENOENT") throw error;
    }
    const parent = dirname(directory);
    if (parent === directory) return null;
    directory = parent;
  }
}
function profileNameValid(name) {
  return typeof name === "string" && name.length > 0 && Buffer.byteLength(name) <= 255 && !name.startsWith("-") && ![".", "..", "node_modules"].includes(name) && !/[\\/\x00-\x1f\x7f<>:"|?*]/u.test(name);
}
function registrySpec(spec) {
  return typeof spec === "string" && spec.trim().length > 0 && (validVersion(spec.trim()) || /^[~^>=< ]*[0-9x*][0-9x*./\-_ |~^>=<]*$/u.test(spec.trim()) || /^[A-Za-z][A-Za-z0-9._-]*$/u.test(spec.trim()));
}
async function validPackage(pkg, targetName) {
  if (!pkg || pkg.manifest?.name !== targetName || !validVersion(pkg.manifest.version)) return false;
  const main = pkg.manifest.main;
  const exportsField = pkg.manifest.exports;
  const dshField = pkg.manifest.dsh;
  const bundle = dshField?.bundle;
  const entries = [main, exportsField?.["./client"], bundle?.patch];
  for (const entry of entries) {
    if (typeof entry !== "string" || !entry || isAbsolute(entry) || entry.includes("\0")) return false;
    const filename = resolve(pkg.directory, entry);
    if (!inside(pkg.directory, filename)) return false;
    let target = filename;
    try {
      target = await realpath(filename);
    } catch {
      return false;
    }
    if (!inside(pkg.directory, target)) return false;
    try {
      if (!(await stat(target)).isFile()) return false;
    } catch {
      return false;
    }
  }
  return true;
}
function defaultHomeDir(env, osHome) {
  let selected = env && env.DSH_HOME && env.DSH_HOME.trim() ? env.DSH_HOME : join(osHome, ".dsh");
  if (selected === "~") selected = osHome;
  else if (/^~[\\/]/u.test(selected)) selected = join(osHome, selected.slice(2));
  return resolve(selected);
}
function createUpdateReader(options) {
  const runningVersion = options.runningVersion;
  if (typeof runningVersion !== "string" || !runningVersion) {
    throw new Error("[dsh-plugin-update] \u5EFA\u8BFB\u53D6\u5668\u5FC5\u987B\u7ED9\u8FD0\u884C\u7248\u672C runningVersion\uFF08\u8BFB\u5BBF\u4E3B\u81EA\u5E26\u6E05\u5355\uFF09");
  }
  const profileDirInput = options.profileDir;
  if (typeof profileDirInput !== "string" || !isAbsolute(profileDirInput)) {
    throw new Error("[dsh-plugin-update] \u5EFA\u8BFB\u53D6\u5668\u5FC5\u987B\u7ED9\u7EDD\u5BF9\u8DEF\u5F84\u7684\u4F7F\u7528\u8303\u56F4\u76EE\u5F55 profileDir");
  }
  const pluginId = assertPluginId(options.pluginId);
  const env = options.env ?? process.env;
  const osHome = options.osHome ?? homedir();
  const homeDirDefault = defaultHomeDir(env, osHome);
  const fallbackFetch = globalThis.fetch;
  if (!options.fetchImpl && !fallbackFetch) {
    throw new Error("[dsh-plugin-update] \u5EFA\u8BFB\u53D6\u5668\u5FC5\u987B\u7ED9\u7F51\u7EDC\u5B9E\u73B0 fetchImpl\uFF08\u672C\u673A\u6CA1\u6709\u5168\u5C40 fetch\uFF09");
  }
  const fetchImpl = options.fetchImpl ?? fallbackFetch;
  const now = options.now ?? Date.now;
  const randomId = options.randomId ?? randomUUID;
  const nodeVersion = options.nodeVersion ?? (typeof process !== "undefined" ? process.versions.node : "");
  const environmentKind = options.environmentKind ?? "cli";
  const targetPackageName = options.targetPackageName ?? "dsh-mattpocock-skills-deck";
  const registryUrl = options.registryUrl ?? "https://registry.npmjs.org/";
  const loadedPackage = containingPackage(fileURLToPath(import.meta.url), targetPackageName).catch(() => null);
  let boundIdentity;
  async function readInstalledReal() {
    const result = {
      profileName: null,
      environmentKind,
      homeDir: null,
      profileDir: null,
      installedVersion: null,
      packageValid: false,
      sourceInstall: false,
      blockedReason: null,
      installationKey: null,
      eligible: false
    };
    const profileName = options.profileName ?? basename(profileDirInput);
    result.profileName = profileName;
    if (!profileNameValid(profileName)) {
      result.blockedReason = "unknown-profile";
      return result;
    }
    let homeDir;
    let profileDir;
    try {
      homeDir = await realpath(options.homeDir ?? homeDirDefault);
      profileDir = await realpath(profileDirInput);
    } catch {
      result.blockedReason = "unknown-profile";
      return result;
    }
    result.homeDir = homeDir;
    result.profileDir = profileDir;
    let profile;
    let installed;
    try {
      profile = await packageAt(profileDir);
      installed = await packageAt(join(profileDir, "node_modules", targetPackageName));
    } catch {
      result.blockedReason = "invalid-installation";
      return result;
    }
    const deps = profile.manifest.dependencies ?? {};
    result.sourceInstall = !registrySpec(deps[targetPackageName]) || !inside(join(profileDir, "node_modules"), installed.directory);
    result.installedVersion = typeof installed.manifest.version === "string" ? installed.manifest.version : null;
    result.packageValid = await validPackage(installed, targetPackageName);
    const loaded = await loadedPackage;
    const identity = `${homeDir}\0${profileDir}\0${profileName}\0${pluginId}`;
    const sameLoadedPackage = loaded?.directory === installed.directory && loaded?.manifest.version === installed.manifest.version;
    if (boundIdentity === void 0 && sameLoadedPackage && result.packageValid) boundIdentity = identity;
    const stateFiles = await Promise.all(LOCK_FILES.map((name) => readOptional(join(profileDir, name))));
    try {
      result.installationKey = createHash("sha256").update(JSON.stringify([identity, profile.contents, installed.directory, installed.contents, ...stateFiles])).digest("hex");
    } catch {
      result.installationKey = null;
    }
    if (boundIdentity !== void 0 && boundIdentity !== identity) result.blockedReason = "installation-changed";
    else if (!sameLoadedPackage && boundIdentity === void 0) result.blockedReason = "installation-changed";
    else if (!result.packageValid) result.blockedReason = "invalid-installation";
    else if (result.sourceInstall) result.blockedReason = "source-install";
    else if (result.installedVersion !== runningVersion) result.blockedReason = "pending-restart";
    result.eligible = !result.blockedReason;
    result.blockedReason = result.blockedReason ?? null;
    return result;
  }
  const readInstalled = options.readInstalled ?? readInstalledReal;
  const core = createUpdateCore({
    readRunningVersion: () => runningVersion,
    readInstalled,
    fetchImpl,
    now,
    randomId,
    nodeVersion,
    checkTimeoutMs: options.checkTimeoutMs,
    confirmationTtlMs: options.confirmationTtlMs,
    targetPackageName,
    registryUrl,
    readJob: options.readJob,
    writeJob: options.writeJob,
    tryAcquireLock: options.tryAcquireLock,
    releaseLock: options.releaseLock,
    backupJob: options.backupJob,
    runInstall: options.runInstall
  });
  return Object.assign(core, { readEnv: readInstalled });
}
export {
  containingPackage,
  createUpdateReader,
  defaultHomeDir,
  profileNameValid,
  registrySpec
};
