// 派生文件（#586）：由 packages/dsh-plugin-update/dist/store.js 原样复制，内容与更新包 0.1.1 一致，人手不改。
// 旧实现（src/host/update.js、updateReader.js、updateStore.js）原地只读留存；运行时走本目录经 updateFromPackage.js 接线。
// 共存关系：旧文件只读、新文件派生，真搬迁或真删除旧文件另开票。重新生成：node scripts/derive-update-from-package.mjs。
// AUTO-GENERATED by node packages/dsh-plugin-update/build.mjs — DO NOT EDIT. Source: packages/dsh-plugin-update/src/store.ts
import { createHash, randomUUID } from "node:crypto";
import { mkdir, open, readFile, rename, realpath, stat, unlink, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { installRecipe } from "./commands.js";
import { BACKUP_FILE, LEGACY_PLUGIN_ID, LOCK_FILE, STATE_FILE } from "./config.js";
const LEGACY_SEGMENT = "updates";
const LEGACY_DIR_PLUGIN = LEGACY_PLUGIN_ID;
const JOB_STATES = ["installing", "verifying", "restart-required", "completed", "failed", "interrupted"];
const SNAPSHOT_FILES = ["package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml"];
function fail(code) {
  return Object.assign(new Error(code), { code });
}
function shortHash(text) {
  try {
    return createHash("sha256").update(String(text)).digest("hex").slice(0, 24);
  } catch {
    return "00000000";
  }
}
function pathsForUpdate(homeDir, pluginId, profileDir) {
  if (typeof homeDir !== "string" || !homeDir || typeof profileDir !== "string" || !profileDir) return null;
  if (typeof pluginId !== "string" || !pluginId) return null;
  const directory = join(homeDir, LEGACY_SEGMENT, pluginId, shortHash(profileDir));
  return { directory, state: join(directory, STATE_FILE), lock: join(directory, LOCK_FILE), backup: join(directory, BACKUP_FILE) };
}
function legacyPathsForUpdate(homeDir, profileDir) {
  if (typeof homeDir !== "string" || !homeDir || typeof profileDir !== "string" || !profileDir) return null;
  const directory = join(homeDir, LEGACY_SEGMENT, LEGACY_DIR_PLUGIN, shortHash(profileDir));
  return { directory, state: join(directory, STATE_FILE), lock: join(directory, LOCK_FILE), backup: join(directory, BACKUP_FILE) };
}
async function readJsonGuarded(filename, missing) {
  try {
    if ((await stat(filename)).size > 10 * 1024 * 1024) throw fail("install-failed");
    return JSON.parse(await readFile(filename, "utf8"));
  } catch (error) {
    if (error && error.code === "ENOENT") return missing;
    throw error && error.code ? error : fail("install-failed");
  }
}
async function writeJsonAtomic(filename, value) {
  const temporary = `${filename}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporary, `${JSON.stringify(value, null, 2)}
`, { mode: 384, flag: "wx" });
    await rename(temporary, filename);
  } catch {
    throw fail("install-failed");
  } finally {
    await unlink(temporary).catch(() => {
    });
  }
}
function normalizeJob(job) {
  return {
    id: typeof job.id === "string" ? job.id : "corrupt",
    state: JOB_STATES.includes(String(job.state)) ? job.state : "interrupted",
    targetVersion: typeof job.targetVersion === "string" ? job.targetVersion : null,
    message: typeof job.message === "string" ? job.message : null,
    requestId: typeof job.requestId === "string" ? job.requestId : null
  };
}
function createUpdateDiskPorts(homeDir, pluginId, profileDir, deps = {}) {
  const paths = pathsForUpdate(homeDir, pluginId, profileDir);
  const legacyPaths = pluginId === LEGACY_DIR_PLUGIN ? null : legacyPathsForUpdate(homeDir, profileDir);
  const readText = deps.readFileImpl ?? ((filename, encoding) => readFile(filename, encoding));
  const statFile = deps.statImpl ?? ((filename) => stat(filename));
  async function readAt(p) {
    if (!p) return null;
    try {
      if ((await statFile(p.state)).size > 10 * 1024 * 1024) throw fail("install-failed");
      return JSON.parse(await readText(p.state, "utf8"));
    } catch (error) {
      if (error && error.code === "ENOENT") return null;
      throw error && error.code ? error : fail("install-failed");
    }
  }
  async function readJob() {
    if (!paths) return null;
    const job = await readAt(paths);
    if (job) {
      if (!JOB_STATES.includes(String(job.state)) || typeof job.id !== "string") {
        return { id: "corrupt", state: "interrupted", message: "recovery-required", targetVersion: null, requestId: null };
      }
      return { requestId: null, message: null, ...job };
    }
    if (legacyPaths) {
      const legacyJob = await readAt(legacyPaths);
      if (legacyJob) {
        if (!JOB_STATES.includes(String(legacyJob.state)) || typeof legacyJob.id !== "string") {
          return { id: "corrupt", state: "interrupted", message: "recovery-required", targetVersion: null, requestId: null };
        }
        return { requestId: null, message: null, ...legacyJob };
      }
    }
    const lock = await readJsonGuarded(paths.lock, null);
    if (lock) return { id: "locked", state: "interrupted", message: "recovery-required", targetVersion: null, requestId: null };
    if (legacyPaths) {
      const legacyLock = await readJsonGuarded(legacyPaths.lock, null).catch(() => null);
      if (legacyLock) return { id: "locked", state: "interrupted", message: "recovery-required", targetVersion: null, requestId: null };
    }
    return null;
  }
  async function writeJob(job) {
    if (!paths) throw fail("install-failed");
    if (job === null) {
      await unlink(paths.state).catch((error) => {
        if (!error || error.code !== "ENOENT") throw fail("install-failed");
      });
      return;
    }
    await mkdir(paths.directory, { recursive: true, mode: 448 });
    await writeJsonAtomic(paths.state, job);
  }
  async function tryAcquireLock(lockId) {
    if (!paths) return false;
    try {
      await mkdir(paths.directory, { recursive: true, mode: 448 });
      const handle = await open(paths.lock, "wx", 384);
      try {
        await handle.writeFile(JSON.stringify({ id: lockId, pid: process.pid, startedAt: Date.now() }));
      } finally {
        await handle.close();
      }
      return true;
    } catch (error) {
      if (!error || error.code !== "EEXIST") return false;
      try {
        const current = await readJsonGuarded(paths.lock, null);
        const job = await readJsonGuarded(paths.state, null);
        if (!current || job && job.id === current.id) return false;
        await unlink(paths.lock).catch(() => {
        });
        const handle = await open(paths.lock, "wx", 384);
        try {
          await handle.writeFile(JSON.stringify({ id: lockId, pid: process.pid, startedAt: Date.now() }));
        } finally {
          await handle.close();
        }
        return true;
      } catch {
        return false;
      }
    }
  }
  async function releaseLock(lockId) {
    if (!paths) return;
    try {
      const current = await readJsonGuarded(paths.lock, null);
      if (current && current.id === lockId) await unlink(paths.lock).catch(() => {
      });
    } catch {
    }
  }
  async function backupJob(job) {
    if (!paths) throw fail("install-failed");
    const files = {};
    for (const name of SNAPSHOT_FILES) {
      try {
        const filename = join(profileDir, name);
        if ((await stat(filename)).size > 3 * 1024 * 1024) throw fail("install-failed");
        files[name] = await readFile(filename, "utf8");
      } catch (error) {
        if (!error || error.code !== "ENOENT") throw fail("install-failed");
      }
    }
    await mkdir(paths.directory, { recursive: true, mode: 448 });
    await writeJsonAtomic(paths.backup, {
      jobId: job.id,
      previousVersion: job.previousVersion ?? null,
      files
    });
  }
  return { paths, legacyPaths, readJob, writeJob, tryAcquireLock, releaseLock, backupJob };
}
const CLI_PACKAGE_NAME = "@deepseek-ai/dsh";
const INSTALL_STDIO = { stdin: "ignore", stdout: { maxBytes: 64 * 1024 }, stderr: { maxBytes: 64 * 1024 } };
const TERMINATION_GRACE_MS = 3e3;
function part(value) {
  return typeof value === "function" ? value() : value;
}
function withExit(error, exitCode) {
  if (typeof exitCode === "number") error.exitCode = exitCode;
  return error;
}
async function sameDir(a, b) {
  if (typeof a !== "string" || typeof b !== "string" || !a || !b) return false;
  try {
    if (resolve(a) === resolve(b)) return true;
  } catch {
    return false;
  }
  try {
    const pair = await Promise.all([realpath(a), realpath(b)]);
    return pair[0] === pair[1];
  } catch {
    return false;
  }
}
async function readManifestAt(directory) {
  try {
    return JSON.parse(await readFile(join(directory, "package.json"), "utf8"));
  } catch {
    return null;
  }
}
async function resolveCliEntry(argv1, deps = {}) {
  const readAt = typeof deps.readManifest === "function" ? deps.readManifest : readManifestAt;
  const realpathImpl = typeof deps.realpath === "function" ? deps.realpath : realpath;
  if (typeof argv1 !== "string" || !argv1 || argv1.includes("\0")) return null;
  let entry = "";
  try {
    entry = await realpathImpl(argv1);
  } catch {
    return null;
  }
  if (typeof entry !== "string" || !entry) return null;
  let directory = dirname(entry);
  while (true) {
    let manifest = null;
    try {
      manifest = await Promise.resolve().then(() => readAt(directory)).catch(() => null);
    } catch {
      manifest = null;
    }
    if (manifest && manifest.name === CLI_PACKAGE_NAME) {
      const bin = manifest.bin;
      const declared = typeof bin === "string" ? bin : bin && bin.dsh;
      if (typeof declared !== "string" || !declared || isAbsolute(declared) || declared.includes("\0")) return null;
      try {
        return await realpathImpl(resolve(directory, declared)) === entry ? entry : null;
      } catch {
        return null;
      }
    }
    const parent = dirname(directory);
    if (parent === directory) return null;
    directory = parent;
  }
}
async function awaitOutcome(handle, timeoutMs) {
  const settled = Promise.resolve(handle.done).then(
    (value) => ({ exitCode: value && typeof value.exitCode === "number" ? value.exitCode : null, timedOut: false }),
    () => ({ exitCode: null, timedOut: true })
  );
  if (!(typeof timeoutMs === "number" && timeoutMs > 0)) return await settled;
  let timer = null;
  const deadline = new Promise((settle) => {
    timer = setTimeout(() => {
      try {
        if (handle && typeof handle.terminate === "function") handle.terminate();
      } catch {
      }
      settle({ exitCode: null, timedOut: true });
    }, timeoutMs);
  });
  try {
    return await Promise.race([settled, deadline]);
  } finally {
    if (timer !== null) {
      try {
        clearTimeout(timer);
      } catch {
      }
    }
  }
}
function emitInstall(parts, recipe, ok, exitCode, durationMs) {
  const log = parts.log;
  if (typeof log !== "function") return;
  try {
    const pluginId = part(parts.pluginId ?? null);
    log("info", "update.install.exec", {
      route: recipe ? recipe.route : "none",
      ok: ok === true,
      exitCode: typeof exitCode === "number" ? exitCode : null,
      durationMs,
      pluginId: typeof pluginId === "string" ? pluginId : null
    });
  } catch {
  }
}
async function runDesktopService(recipe, parts) {
  const service = part(parts.desktopPnpm);
  if (!service || typeof service.runPlugin !== "function") throw fail("install-failed");
  const profiles = part(parts.desktopProfiles);
  const active = profiles && profiles.current ? profiles.current : null;
  const profileDir = part(parts.profileDir);
  if (!active || !active.dir || !profileDir || !await sameDir(active.dir, profileDir)) throw fail("install-failed");
  const handle = service.runPlugin(recipe.pluginArgs, profileDir, void 0);
  if (!handle || !handle.done || typeof handle.done.then !== "function") throw fail("install-failed");
  const outcome = await handle.done;
  const code = outcome && typeof outcome.exitCode === "number" ? outcome.exitCode : null;
  if (code !== 0) throw withExit(fail("install-failed"), code);
  return code;
}
async function runCliProcess(recipe, parts) {
  const executable = part(parts.runtimeExecutable) || (typeof process !== "undefined" ? process.execPath : "");
  const execArgs = part(parts.runtimeExecArgs) ?? (typeof process !== "undefined" && Array.isArray(process.execArgv) ? process.execArgv : []);
  const entry = part(parts.cliEntry) ?? await resolveCliEntry(typeof process !== "undefined" && process.argv ? process.argv[1] : "");
  if (!executable || !entry) throw fail("install-failed");
  const argv = [executable, ...execArgs, entry, "plugin", "--profile", recipe.profileName, ...recipe.pluginArgs];
  const subprocess = part(parts.subprocess);
  if (!subprocess || typeof subprocess.spawn !== "function") throw fail("install-failed");
  const handle = subprocess.spawn({
    argv,
    cwd: part(parts.profileDir) || void 0,
    stdio: INSTALL_STDIO,
    graceMs: TERMINATION_GRACE_MS
  });
  if (!handle || !handle.done || typeof handle.done.then !== "function") throw fail("install-failed");
  const outcome = await awaitOutcome(handle, recipe.timeoutMs);
  if (outcome.timedOut || outcome.exitCode !== 0) throw withExit(fail("install-failed"), outcome.exitCode);
  return outcome.exitCode;
}
function createUpdateExecutor(parts = {}) {
  return async function runInstall(args = {}) {
    const recipe = installRecipe({
      profileName: args.profileName ?? part(parts.profileName ?? null),
      version: String(args.version ?? ""),
      environmentKind: args.environmentKind ?? part(parts.environmentKind ?? "cli"),
      targetPackageName: parts.targetPackageName === void 0 ? void 0 : part(parts.targetPackageName),
      registryUrl: parts.registryUrl === void 0 ? void 0 : part(parts.registryUrl),
      timeoutMs: parts.installTimeoutMs === void 0 ? void 0 : part(parts.installTimeoutMs)
    });
    const startedAt = Date.now();
    let exitCode = null;
    try {
      if (!recipe) throw fail("install-failed");
      exitCode = recipe.route === "desktop-service" ? await runDesktopService(recipe, parts) : await runCliProcess(recipe, parts);
      emitInstall(parts, recipe, true, exitCode, Date.now() - startedAt);
    } catch (error) {
      emitInstall(parts, recipe, false, error?.exitCode ?? exitCode, Date.now() - startedAt);
      throw Object.assign(fail("install-failed"), { debug: String(error?.stack || error) });
    }
  };
}
const __executorInternals = { INSTALL_STDIO, TERMINATION_GRACE_MS, CLI_PACKAGE_NAME };
export {
  __executorInternals,
  createUpdateDiskPorts,
  createUpdateExecutor,
  legacyPathsForUpdate,
  pathsForUpdate,
  resolveCliEntry
};
