/**
 * version-control-core/build.mjs —— 版本管理核心的编译脚本（#816 落地）
 *
 * 只转译不打包：用仓库现成的 esbuild 把 version-control-core/src/ 下每个 TS 文件一对一转成
 * src/shared/version-control/ 下的同名 JS；另跑 tsc --noEmit 只做类型检查。生成的 JS 提交进 git；
 * 改了 TS 没重新生成产物，tests/verify-version-control-freshness.js 会变红。
 *
 * 与 refresh-core/build.mjs 同形（依据 docs/adr/20260913-builtin-ts-shape.md §2.4）：
 * 导出 transpileUnit、runTypeCheck、buildAll，外加 UNITS（新鲜度门禁直接从这里读清单，
 * 不许手抄 —— #822 与 #813 待后续的要求，教训是刷新核心的手抄清单漏过两个文件）。
 * 类型检查与转译是两步，调用方按顺序各调一次；buildAll 只管转译。
 * 源码树或 tsconfig 不在时跳过并打印提示（发布包里没有这棵源码树），绝不中断整个构建。
 * 转译结果把 esbuild 收在末尾的 export 块改写成行首 export（与两份先例一致）。
 *
 * 用法：node version-control-core/build.mjs（日常更常用 node scripts/build.mjs，
 * 那条命令会把本脚本的两步一起带上，不必手动补跑）。
 */
import '../scripts/require-macos-arm64.mjs'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import * as esbuild from 'esbuild'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC_DIR = resolve(ROOT, 'version-control-core/src')
const OUT_DIR = resolve(ROOT, 'src/shared/version-control')
const TSCONFIG = resolve(ROOT, 'version-control-core/tsconfig.json')

export const UNITS = [
  { ts: 'ports.ts', js: 'ports.js' },
  { ts: 'capabilities.ts', js: 'capabilities.js' },
  { ts: 'commands.ts', js: 'commands.js' },
  { ts: 'parse-status.ts', js: 'parse-status.js' },
  { ts: 'parse-worktrees.ts', js: 'parse-worktrees.js' },
  { ts: 'parse-refs.ts', js: 'parse-refs.js' },
  { ts: 'parse-log.ts', js: 'parse-log.js' },
  { ts: 'parse-diff-files.ts', js: 'parse-diff-files.js' },
  { ts: 'parse-patch.ts', js: 'parse-patch.js' },
  { ts: 'state.ts', js: 'state.js' },
  { ts: 'rules.ts', js: 'rules.js' },
  // #841 写操作那一族：失败种类与句子、票据与索引指纹、推送目标解析（都是纯函数）
  { ts: 'write-reasons.ts', js: 'write-reasons.js' },
  { ts: 'write-ticket.ts', js: 'write-ticket.js' },
  { ts: 'push-plan.ts', js: 'push-plan.js' },
]

function headerFor(tsName) {
  return `// AUTO-GENERATED by node version-control-core/build.mjs — DO NOT EDIT. Source: version-control-core/src/${tsName}\n`
}

function skipNotice(step) {
  return (
    '[version-control-core] 没找到源码目录或 tsconfig（' + SRC_DIR + ' / ' + TSCONFIG + '），本次跳过' + step +
    '。发布包与 package/ 子树里本来就没有这棵源码树，这是预期情况；要重新生成产物请在仓库根目录跑 node scripts/build.mjs。'
  )
}

function inlineExportDeclarations(code) {
  const clause = /(^|\n)export \{\n([\s\S]*?)\n\};\n?$/.exec(code)
  if (!clause) {
    if (/(^|\n)export \{/.test(code)) {
      throw new Error('[version-control-core] 转译结果里出现了没有预料到的导出块写法，拒绝改写：\n' + code.slice(-300))
    }
    return code
  }
  const names = clause[2]
    .split(',')
    .map((s) => s.trim())
    .filter((s) => s !== '')
  let body = code.slice(0, clause.index) + (clause[1] === '\n' ? '\n' : '')
  for (const name of names) {
    if (!/^[A-Za-z_$][\w$]*$/.test(name)) {
      throw new Error(`[version-control-core] 导出块里有改不了名的条目「${name}」：本脚本只支持原样导出，不支持 as 改名`)
    }
    const decl = new RegExp('^(?:async )?function ' + name + '\\b|^(?:const|let|var) ' + name + '\\b|^class ' + name + '\\b', 'm')
    const hit = decl.exec(body)
    if (!hit) {
      throw new Error(`[version-control-core] 导出块里的名字「${name}」在这份文件里找不到声明，拒绝生成少一个导出的产物`)
    }
    body = body.slice(0, hit.index) + 'export ' + body.slice(hit.index)
  }
  return body
}

export function transpileUnit(tsName) {
  const tsPath = resolve(SRC_DIR, tsName)
  const source = readFileSync(tsPath, 'utf8')
  const out = esbuild.transformSync(source, {
    loader: 'ts',
    format: 'esm',
    target: 'es2020',
  })
  const normalized = out.code.replace(/\r\n/g, '\n').replace(/\s+$/, '') + '\n'
  return headerFor(tsName) + inlineExportDeclarations(normalized)
}

export function runTypeCheck() {
  if (!existsSync(SRC_DIR) || !existsSync(TSCONFIG)) {
    console.log(skipNotice('类型检查'))
    return { skipped: true }
  }
  const require = createRequire(resolve(ROOT, 'package.json'))
  let tscBin
  try {
    tscBin = resolve(dirname(require.resolve('typescript/package.json')), 'bin/tsc')
  } catch {
    throw new Error('[version-control-core] 找不到 typescript：请先运行 pnpm install（devDependencies 含 typescript）')
  }
  const r = spawnSync(process.execPath, [tscBin, '-p', TSCONFIG], { encoding: 'utf8' })
  if (r.status !== 0) {
    throw new Error(`[version-control-core] tsc --noEmit 未通过：\n${r.stdout || ''}${r.stderr || ''}`)
  }
  console.log('[version-control-core] tsc --noEmit 通过')
  return { skipped: false }
}

export function buildAll() {
  if (!existsSync(SRC_DIR) || !existsSync(TSCONFIG)) {
    console.log(skipNotice('转译'))
    return { skipped: true, files: [] }
  }
  mkdirSync(OUT_DIR, { recursive: true })
  const files = []
  for (const u of UNITS) {
    const text = transpileUnit(u.ts)
    const outPath = resolve(OUT_DIR, u.js)
    writeFileSync(outPath, text, 'utf8')
    console.log(`[version-control-core] ${u.ts} -> src/shared/version-control/${u.js}（${text.split('\n').length} 行）`)
    files.push('src/shared/version-control/' + u.js)
  }
  return { skipped: false, files }
}

const invoked = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (invoked) {
  try {
    runTypeCheck()
    buildAll()
  } catch (e) {
    console.error((e && e.message) || e)
    process.exit(1)
  }
}
