// AUTO-GENERATED by node label-color-core/build.mjs — DO NOT EDIT. Source: label-color-core/src/colors.ts
function normalizeForCompare(value) {
  let text = typeof value === "string" ? value.trim() : "";
  if (text.startsWith("#")) text = text.slice(1);
  return text.trim().toLowerCase();
}
const COLOR_PATTERN = /^[0-9a-f]{6}$/;
export function normalizeColor(input) {
  const normalized = normalizeForCompare(input);
  return COLOR_PATTERN.test(normalized) ? normalized : null;
}
export function isColor(value) {
  return normalizeColor(value) !== null;
}
export function colorsDiffer(current, next) {
  return normalizeForCompare(current) !== normalizeForCompare(next);
}
export function pickChangedRows(baseline, draft) {
  const currentByName = /* @__PURE__ */ new Map();
  for (const row of baseline) currentByName.set(row.name, row.color);
  const changed = [];
  for (const name of Object.keys(draft)) {
    const next = draft[name];
    const current = currentByName.get(name) ?? "";
    if (!colorsDiffer(current, next)) continue;
    changed.push({ name, color: normalizeForCompare(next) });
  }
  return changed;
}
