// AUTO-GENERATED by node label-color-core/build.mjs — DO NOT EDIT. Source: label-color-core/src/prompt.ts
function formatColorCell(color) {
  let text = typeof color === "string" ? color.trim() : "";
  if (text.startsWith("#")) text = text.slice(1);
  return text.trim().toLowerCase();
}
export function buildPaletteTable(rows, columnNames) {
  const lines = [
    "| " + columnNames.name + " | " + columnNames.color + " |",
    "| --- | --- |"
  ];
  for (const row of rows) lines.push("| " + row.name + " | " + formatColorCell(row.color) + " |");
  return lines.join("\n");
}
export function buildPalettePrompt(input) {
  const parts = [input.texts.opening, buildPaletteTable(input.rows, input.texts.columnNames), input.texts.closing];
  return parts.filter((part) => typeof part === "string" && part.trim() !== "").join("\n\n");
}
