import { readFile, realpath, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { createHash } from 'node:crypto'

const root = new URL('../', import.meta.url)
// Reuse the pinned workspace toolchain; shipped plugins contain built JS.
const { build } = createRequire(await realpath(new URL('../deepseek-harness/node_modules/tsx/package.json', root)))('esbuild')
const manifest = JSON.parse(await readFile(new URL('upstream.json', root), 'utf8'))
for (const [file, expected] of Object.entries(manifest.files)) {
  const bytes = await readFile(new URL(file, new URL('../owner-workflow-plugin/vendor/dsh-approve-for-me/', root)))
  if (createHash('sha256').update(bytes).digest('hex') !== expected) throw new Error(`Pinned approval source changed: ${file}`)
}
const check = process.argv.includes('--check')
const entries = process.argv.includes('--host-only') ? ['index'] : ['index', 'client']
for (const entry of entries) {
  const browser = entry === 'client'
  const result = await build({
    entryPoints: [fileURLToPath(new URL(`src/${entry}.${browser ? 'jsx' : 'ts'}`, root))],
    bundle: true, write: false, platform: browser ? 'browser' : 'node',
    format: browser ? 'cjs' : 'esm', target: 'es2022',
    external: ['@deepseek-ai/*', 'react'], legalComments: 'inline',
    absWorkingDir: fileURLToPath(new URL('../', root)),
  })
  const code = result.outputFiles[0].text
  const output = browser
    ? `// Generated by scripts/build.mjs.\nwindow.__ModuleLoader__.load({ id: 'dsh-approve-for-me-workflow', factory(require) {\nconst module = { exports: {} }; const exports = module.exports;\n${code}\nreturn module.exports;\n} });\n`
    : `// Generated by scripts/build.mjs; includes pinned MIT policy core.\n${code}`
  const path = new URL(`${entry}.js`, root)
  if (check) {
    if (await readFile(path, 'utf8') !== output) throw new Error(`Stale approval build: ${entry}.js`)
  } else await writeFile(path, output)
}
