// AUTO-GENERATED by node update-core/build.mjs — DO NOT EDIT. Source: update-core/src/commands.ts
const PACKAGE_NAME = "dsh-mattpocock-skills-deck";
const NPM_REGISTRY = "https://registry.npmjs.org/";
const INSTALL_TIMEOUT_MS = 15 * 6e4;
function validVersion(v) {
  return typeof v === "string" && /^\d+\.\d+\.\d+$/.test(v);
}
function parseTriple(v) {
  const parts = String(v).split(".");
  if (parts.length > 3) return null;
  const nums = [];
  for (const p of parts) {
    if (!/^\d+$/.test(p)) return null;
    const n = Number(p);
    if (!Number.isSafeInteger(n)) return null;
    nums.push(n);
  }
  while (nums.length < 3) nums.push(0);
  return [nums[0], nums[1], nums[2]];
}
function compareVersions(a, b) {
  const pa = parseTriple(a);
  const pb = parseTriple(b);
  if (!pa || !pb) throw new Error("invalid-release");
  for (let i = 0; i < 3; i++) {
    if (pa[i] < pb[i]) return -1;
    if (pa[i] > pb[i]) return 1;
  }
  return 0;
}
function usableProfileName(raw) {
  const name = typeof raw === "string" ? raw.trim() : "";
  if (!name || name.length > 255 || name.startsWith("-")) return null;
  if ([".", "..", "node_modules"].includes(name)) return null;
  return name;
}
function installRecipe(input) {
  const name = usableProfileName(input?.profileName);
  const version = input?.version;
  if (!name || !validVersion(version)) return null;
  const kind = input?.environmentKind;
  if (kind !== "desktop" && kind !== "cli") return null;
  return {
    route: kind === "desktop" ? "desktop-service" : "cli-process",
    profileName: name,
    version,
    // 参数数组原样交给命令行工具：使用范围名不做引号包裹、不按空格拆分。
    pluginArgs: ["add", "--save-exact", `${PACKAGE_NAME}@${version}`, `--registry=${NPM_REGISTRY}`],
    timeoutMs: INSTALL_TIMEOUT_MS
  };
}
function manualCommand(input) {
  if (input.sourceInstall || input.blockedReason === "source-install" || input.blockedReason === "unknown-profile") return null;
  const name = usableProfileName(input.profileName);
  if (!name) return null;
  const arg = /^[A-Za-z0-9_.-]+$/.test(name) ? name : JSON.stringify(name);
  const picks = [input.latestVersion, input.jobTargetVersion, input.installedVersion].filter(validVersion);
  let version = picks.length > 0 ? picks[0] : "latest";
  try {
    const ranked = picks.filter((v) => compareVersions(v, input.runningVersion) >= 0);
    if (ranked.length > 0) {
      version = ranked[0];
      for (const v of ranked) if (compareVersions(v, version) === 1) version = v;
    }
  } catch {
  }
  return `dsh plugin --profile ${arg} add --save-exact ${PACKAGE_NAME}@${version} --registry=${NPM_REGISTRY}`;
}
export {
  INSTALL_TIMEOUT_MS,
  installRecipe,
  manualCommand
};
