// 派生文件（#564）：由 packages/dsh-log/dist/config.js 原样复制，内容与日志包 0.1.0 一致，人手不改。
// 旧实现（src/host/logStore.js、src/host/logPhones.js）原地只读留存；运行时走本目录经 logFromPackage.js 接线。
// 共存关系：旧文件只读、新文件派生，真搬迁或真删除旧文件另开票。重新生成：node scripts/derive-log-from-package.mjs。
// AUTO-GENERATED by node packages/dsh-log/build.mjs — DO NOT EDIT. Source: packages/dsh-log/src/config.ts
const LOG_DEBOUNCE_MS = 1e3;
const DEFAULT_MAX_QUEUE = 1e3;
const CLIENT_BATCH_MAX = 50;
const CLIENT_BATCH_INTERVAL_MS = 1e3;
const CLIENT_PACKET_BYTES = 128 * 1024;
const CLIENT_QUEUE_MAX = 100;
const LEGACY_LOG_DIR_NAME = "logs";
const LEGACY_SWITCH_FILE_NAME = "log-switch.json";
const PHONE_ACTIONS = ["logBatch", "logExport", "logClear", "logGetSwitch", "logSetSwitch"];
const ID_PATTERN = /^[a-z0-9-]{1,32}$/;
function assertPluginId(value, role) {
  if (typeof value !== "string" || !ID_PATTERN.test(value)) {
    throw new Error(
      "[dsh-log] " + role + " \u975E\u6CD5\uFF1A\u53EA\u80FD\u7528\u5C0F\u5199\u82F1\u6587\u5B57\u6BCD\u3001\u6570\u5B57\u3001\u4E2D\u6A2A\u7EBF\uFF0C\u957F\u5EA6 1 \u5230 32\uFF08\u6536\u5230 " + JSON.stringify(value) + "\uFF09"
    );
  }
  return value;
}
function resolveHostLogConfig(input) {
  if (!input || typeof input !== "object") throw new Error("[dsh-log] \u5EFA\u65E5\u5FD7\u5E93\u7F3A\u5C11\u914D\u7F6E\uFF1A\u63D2\u4EF6\u6807\u8BC6 pluginId \u5FC5\u586B");
  const pluginId = assertPluginId(input.pluginId, "\u63D2\u4EF6\u6807\u8BC6 pluginId");
  const prefix = input.prefix === void 0 ? pluginId : assertPluginId(input.prefix, "\u7535\u8BDD\u540D\u524D\u7F00 prefix");
  const logDirName = input.logDirName !== void 0 ? input.logDirName : pluginId === "wf" ? LEGACY_LOG_DIR_NAME : LEGACY_LOG_DIR_NAME + "-" + pluginId;
  const switchFileName = input.switchFileName !== void 0 ? input.switchFileName : pluginId === "wf" ? LEGACY_SWITCH_FILE_NAME : "log-switch-" + pluginId + ".json";
  const fileNamePolicy = input.fileNamePolicy === void 0 ? "daily" : input.fileNamePolicy;
  if (fileNamePolicy !== "daily" && fileNamePolicy !== "four-segment") {
    throw new Error("[dsh-log] \u6587\u4EF6\u540D\u7B56\u7565 fileNamePolicy \u975E\u6CD5\uFF1A\u53EA\u8BB8 daily \u6216 four-segment");
  }
  const maxQueue = input.maxQueue === void 0 ? DEFAULT_MAX_QUEUE : input.maxQueue;
  if (typeof maxQueue !== "number" || !isFinite(maxQueue) || maxQueue < 1) {
    throw new Error("[dsh-log] \u5185\u5B58\u961F\u5217\u4E0A\u9650 maxQueue \u975E\u6CD5\uFF1A\u5FC5\u987B\u662F\u4E0D\u5C0F\u4E8E 1 \u7684\u6570\u5B57");
  }
  const eventList = input.eventList === void 0 ? null : input.eventList;
  if (eventList !== null && typeof eventList === "object") {
    parseEventListManifest(eventList);
  }
  return {
    pluginId,
    prefix,
    logDirName,
    switchFileName,
    fileNamePolicy,
    maxQueue: Math.floor(maxQueue),
    eventList
  };
}
function buildPhoneName(prefix, action) {
  return assertPluginId(prefix, "\u7535\u8BDD\u540D\u524D\u7F00 prefix") + "." + action;
}
function buildPhoneNames(prefix) {
  const checked = assertPluginId(prefix, "\u7535\u8BDD\u540D\u524D\u7F00 prefix");
  const names = {};
  for (const action of PHONE_ACTIONS) names[action] = checked + "." + action;
  return names;
}
function formatDailyFileName(date) {
  const d = date instanceof Date ? date : new Date(date);
  const pad = (n) => String(n).padStart(2, "0");
  return d.getFullYear() + "-" + pad(d.getMonth() + 1) + "-" + pad(d.getDate()) + ".log";
}
function formatFourSegmentFileName(date, pluginId, pid, startedAt) {
  const d = date instanceof Date ? date : new Date(date);
  const pad = (n) => String(n).padStart(2, "0");
  const day = d.getFullYear() + "-" + pad(d.getMonth() + 1) + "-" + pad(d.getDate());
  const safeId = assertPluginId(pluginId, "\u63D2\u4EF6\u6807\u8BC6 pluginId");
  const safePid = typeof pid === "number" && isFinite(pid) && pid > 0 ? Math.floor(pid) : 0;
  const safeStartedAt = String(startedAt || "").replace(/[:/\\]/g, "-");
  return day + "." + safeId + "." + safePid + "." + safeStartedAt + ".log";
}
function resolveLogFileName(config, date, pid, startedAt) {
  if (config.fileNamePolicy === "four-segment") {
    return formatFourSegmentFileName(date, config.pluginId, pid, startedAt);
  }
  return formatDailyFileName(date);
}
function logFileNamePattern(config) {
  if (config.fileNamePolicy === "four-segment") {
    return /^\d{4}-\d{2}-\d{2}\.[a-z0-9-]{1,32}\.\d+\..+\.log$/;
  }
  return /^\d{4}-\d{2}-\d{2}\.log$/;
}
function matchExportFileName(config, candidates, wantDate, fallbackFileName) {
  if (config.fileNamePolicy !== "four-segment") {
    return /^\d{4}-\d{2}-\d{2}$/.test(wantDate) ? wantDate + ".log" : fallbackFileName;
  }
  const pattern = logFileNamePattern(config);
  const hits = (Array.isArray(candidates) ? candidates : []).filter((name) => typeof name === "string" && pattern.test(name) && name.indexOf(wantDate + ".") === 0).sort();
  return hits.length > 0 ? hits[0] : fallbackFileName;
}
const EVENT_LEVELS = ["error", "warn", "info", "debug"];
const EVENT_KINDS = ["resident", "ondemand", "selfmon"];
function isNonEmptyString(value) {
  return typeof value === "string" && value.length > 0;
}
function assertStringArray(value, what) {
  if (!Array.isArray(value)) throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A" + what + " \u5FC5\u987B\u662F\u5B57\u7B26\u4E32\u6570\u7EC4");
  const seen = [];
  for (const item of value) {
    if (!isNonEmptyString(item)) throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A" + what + " \u91CC\u6709\u7A7A\u5B57\u6BB5\u540D");
    if (seen.indexOf(item) >= 0) throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A" + what + " \u91CC\u5B57\u6BB5\u540D\u91CD\u590D\uFF1A" + item);
    seen.push(item);
  }
  return seen;
}
function parseEventListManifest(value) {
  if (typeof value === "string") {
    throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u8DEF\u5F84\u5F62\u5F0F\u8BF7\u8C03\u7528\u65B9\u81EA\u5DF1\u8BFB\u6210\u5BF9\u8C61\u518D\u4F20\u5165\uFF0C\u65E5\u5FD7\u5305\u4E0D\u8BFB\u76D8");
  }
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u53EA\u6536\u5BF9\u8C61\u5F62\u5F0F\uFF08\u7A7A\u6A21\u677F\u89C1\u5305\u5185\u7684 event-list.template.json\uFF09");
  }
  const input = value;
  if (input["version"] !== 1) {
    throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1Aversion \u73B0\u5728\u53EA\u8BA4 1\uFF08\u6536\u5230 " + JSON.stringify(input["version"]) + "\uFF09");
  }
  const pluginId = assertPluginId(input["pluginId"], "\u4E8B\u4EF6\u6E05\u5355 pluginId");
  const countsRaw = input["counts"];
  if (!countsRaw || typeof countsRaw !== "object" || Array.isArray(countsRaw)) {
    throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1Acounts \u5FC5\u987B\u662F\u542B\u4E09\u7C7B\u8BA1\u6570\u7684\u5BF9\u8C61");
  }
  const countsRecord = countsRaw;
  const counts = { resident: 0, ondemand: 0, selfmon: 0 };
  for (const kind of EVENT_KINDS) {
    const n = countsRecord[kind];
    if (typeof n !== "number" || !isFinite(n) || Math.floor(n) !== n || n < 0) {
      throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1Acounts." + kind + " \u5FC5\u987B\u662F\u975E\u8D1F\u6574\u6570");
    }
    counts[kind] = n;
  }
  const eventsRaw = input["events"];
  if (!eventsRaw || typeof eventsRaw !== "object" || Array.isArray(eventsRaw)) {
    throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1Aevents \u5FC5\u987B\u662F\u4E8B\u4EF6\u540D\u5230\u6761\u76EE\u7684\u5BF9\u8C61");
  }
  const events = {};
  for (const name of Object.keys(eventsRaw)) {
    events[name] = parseEventEntry(name, eventsRaw[name]);
  }
  return { version: 1, pluginId, counts, events };
}
function parseEventEntry(name, value) {
  if (!isNonEmptyString(name)) throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6\u540D\u4E0D\u80FD\u4E3A\u7A7A");
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u5FC5\u987B\u662F\u5BF9\u8C61");
  }
  const input = value;
  if (EVENT_LEVELS.indexOf(input["level"]) < 0) {
    throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u7684 level \u53EA\u8BB8 error\u3001warn\u3001info\u3001debug");
  }
  if (EVENT_KINDS.indexOf(input["kind"]) < 0) {
    throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u7684 kind \u53EA\u8BB8 resident\u3001ondemand\u3001selfmon");
  }
  for (const key of Object.keys(input)) {
    if (["level", "kind", "fields", "codes", "rules", "guard"].indexOf(key) < 0) {
      throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u6709\u4E0D\u8BA4\u8BC6\u7684\u952E " + key);
    }
  }
  const entry = {
    level: input["level"],
    kind: input["kind"],
    fields: assertStringArray(input["fields"], "\u4E8B\u4EF6 " + name + " \u7684 fields")
  };
  if (input["codes"] !== void 0) entry.codes = assertStringArray(input["codes"], "\u4E8B\u4EF6 " + name + " \u7684 codes");
  if (input["rules"] !== void 0) entry.rules = assertStringArray(input["rules"], "\u4E8B\u4EF6 " + name + " \u7684 rules");
  if (input["guard"] !== void 0) {
    if (typeof input["guard"] !== "string") {
      throw new Error("[dsh-log] \u4E8B\u4EF6\u6E05\u5355 eventList \u975E\u6CD5\uFF1A\u4E8B\u4EF6 " + name + " \u7684 guard \u5FC5\u987B\u662F\u5B57\u7B26\u4E32");
    }
    entry.guard = input["guard"];
  }
  return entry;
}
function checkEventFields(manifest, eventName, fieldNames) {
  const entry = manifest.events[eventName];
  if (!entry) return { ok: false, unknownEvent: true, unknownFields: [] };
  const allowed = new Set(entry.fields);
  const unknownFields = (Array.isArray(fieldNames) ? fieldNames : []).filter(
    (field) => !allowed.has(field)
  );
  return { ok: unknownFields.length === 0, unknownEvent: false, unknownFields };
}
function checkEventCounts(manifest) {
  const actual = { resident: 0, ondemand: 0, selfmon: 0 };
  for (const name of Object.keys(manifest.events)) {
    actual[manifest.events[name].kind] += 1;
  }
  const problems = [];
  for (const kind of EVENT_KINDS) {
    if (actual[kind] !== manifest.counts[kind]) {
      problems.push(
        "[dsh-log] \u4E8B\u4EF6\u6E05\u5355\u8BA1\u6570\u5BF9\u4E0D\u4E0A\uFF1A" + kind + " \u7C7B\u5B9E\u9645 " + actual[kind] + " \u6761\uFF0C\u6E05\u5355\u81EA\u62A5 " + manifest.counts[kind] + " \u6761"
      );
    }
  }
  return { ok: problems.length === 0, problems };
}
export {
  CLIENT_BATCH_INTERVAL_MS,
  CLIENT_BATCH_MAX,
  CLIENT_PACKET_BYTES,
  CLIENT_QUEUE_MAX,
  DEFAULT_MAX_QUEUE,
  EVENT_KINDS,
  EVENT_LEVELS,
  LEGACY_LOG_DIR_NAME,
  LEGACY_SWITCH_FILE_NAME,
  LOG_DEBOUNCE_MS,
  PHONE_ACTIONS,
  assertPluginId,
  buildPhoneName,
  buildPhoneNames,
  checkEventCounts,
  checkEventFields,
  formatDailyFileName,
  formatFourSegmentFileName,
  logFileNamePattern,
  matchExportFileName,
  parseEventListManifest,
  resolveHostLogConfig,
  resolveLogFileName
};
