// 派生文件（#564）：由 packages/dsh-log/dist/phones.js 原样复制，内容与日志包 0.1.0 一致，人手不改。
// 旧实现（src/host/logStore.js、src/host/logPhones.js）原地只读留存；运行时走本目录经 logFromPackage.js 接线。
// 共存关系：旧文件只读、新文件派生，真搬迁或真删除旧文件另开票。重新生成：node scripts/derive-log-from-package.mjs。
// AUTO-GENERATED by node packages/dsh-log/build.mjs — DO NOT EDIT. Source: packages/dsh-log/src/phones.ts
import {
  formatDailyFileName,
  resolveLogFileName,
  matchExportFileName,
  logFileNamePattern
} from "./config.js";
function hash8(s) {
  try {
    const t = String(s || "");
    let h = 5381;
    for (let i = 0; i < t.length; i++) h = (h << 5) + h + t.charCodeAt(i) >>> 0;
    return ("0000000" + h.toString(16)).slice(-8);
  } catch (e) {
    void e;
    return "00000000";
  }
}
function targetToPath(t, fb) {
  if (typeof t === "string") return t;
  if (t && typeof t === "object") {
    const c = t.displayPath || t.path;
    if (typeof c === "string" && c) return c;
  }
  return typeof fb === "string" && fb ? fb : "";
}
async function listFileNames(ctx, logDir) {
  const { fs, getPlatform, resolveTarget } = ctx;
  try {
    const platform = typeof getPlatform === "function" ? await getPlatform() : null;
    const listFn = platform && platform.fs && typeof platform.fs.listDir === "function" ? platform.fs.listDir.bind(platform.fs) : fs && typeof fs.listDir === "function" ? fs.listDir.bind(fs) : null;
    if (!listFn) return [];
    const dirTarget = await resolveTarget(logDir);
    const entries = await listFn(dirTarget);
    if (!Array.isArray(entries)) return [];
    return entries.map((x) => typeof x === "string" ? x : x && typeof x.name === "string" ? x.name : "");
  } catch (e) {
    void e;
    return [];
  }
}
function createLogPhones(ctx) {
  const config = ctx.config;
  const filePattern = logFileNamePattern(config);
  const pidOf = () => {
    try {
      if (typeof ctx.getPid === "function") return ctx.getPid();
      const header = typeof ctx.getHeaderInfo === "function" ? ctx.getHeaderInfo() : null;
      if (header && typeof header.pid === "number") return header.pid;
      const g = globalThis;
      return (g.process && typeof g.process.pid === "number" ? g.process.pid : 0) || 0;
    } catch (e) {
      void e;
      return 0;
    }
  };
  const startedAtOf = () => {
    try {
      if (typeof ctx.getStartedAt === "function") return ctx.getStartedAt();
      const header = typeof ctx.getHeaderInfo === "function" ? ctx.getHeaderInfo() : null;
      return header && header.startedAt || "";
    } catch (e) {
      void e;
      return "";
    }
  };
  async function handleLogExport(args) {
    const headerInfo = typeof ctx.getHeaderInfo === "function" ? ctx.getHeaderInfo() : null;
    const now = /* @__PURE__ */ new Date();
    const fallbackFileName = resolveLogFileName(config, now, pidOf(), startedAtOf());
    const want = args && args.date ? String(args.date) : formatDailyFileName(now).replace(/\.log$/, "");
    void (args && args.format);
    try {
      const dir = typeof ctx.getCacheDir === "function" ? await ctx.getCacheDir() : null;
      if (!dir) {
        try {
          ctx.log("warn", "host.call.fail", { method: config.prefix + ".logExport", kind: "export", errorHash: hash8("no-dir") });
        } catch (eL) {
          void eL;
        }
      }
      const baseDir = dir || headerInfo && headerInfo.dir || ctx.DEFAULT_CWD || "";
      const logDir = baseDir ? await ctx.joinLogPath(baseDir, config.logDirName) : "";
      let fileName = fallbackFileName;
      if (config.fileNamePolicy === "four-segment" && /^\d{4}-\d{2}-\d{2}$/.test(want) && logDir) {
        const candidates = await listFileNames(ctx, logDir);
        fileName = matchExportFileName(config, candidates, want, fallbackFileName);
      } else if (config.fileNamePolicy !== "four-segment") {
        fileName = /^\d{4}-\d{2}-\d{2}$/.test(want) ? want + ".log" : fallbackFileName;
      }
      let text = "";
      try {
        const target = await ctx.resolveTarget(await ctx.joinLogPath(logDir, fileName));
        text = await ctx.readTarget(target);
      } catch (e) {
        void e;
        text = "";
      }
      let osName = "";
      try {
        const platform = typeof ctx.getPlatform === "function" ? await ctx.getPlatform() : null;
        const g = globalThis;
        osName = platform && platform.os || (typeof g.process !== "undefined" ? String(g.process.platform) : "") || "";
      } catch (e2) {
        void e2;
      }
      let cwdNow = ctx.DEFAULT_CWD || "";
      try {
        const g = globalThis;
        cwdNow = g.process && g.process.cwd ? g.process.cwd() : ctx.DEFAULT_CWD || "";
      } catch (e3) {
        void e3;
      }
      const summary = {
        pluginVersion: "unknown",
        os: osName,
        cwd: cwdNow,
        logSwitch: ctx.getSwitchState(),
        header: headerInfo
      };
      let dirOut = logDir;
      let pathOut = "";
      try {
        dirOut = targetToPath(await ctx.resolveTarget(logDir), logDir);
        pathOut = targetToPath(await ctx.resolveTarget(await ctx.joinLogPath(logDir, fileName)), ctx.joinPath(logDir, fileName));
      } catch (e4) {
        void e4;
        try {
          pathOut = ctx.joinPath(logDir, fileName);
        } catch (e5) {
          void e5;
          pathOut = "";
        }
      }
      if (!dirOut && !pathOut && baseDir) {
        try {
          dirOut = ctx.joinPath(baseDir, config.logDirName);
          pathOut = ctx.joinPath(dirOut, fileName);
        } catch (e6) {
          void e6;
        }
      }
      return {
        ok: true,
        fileName,
        bytes: String(text || "").length,
        fallback: true,
        text: String(text || ""),
        summary,
        dir: dirOut,
        path: pathOut
      };
    } catch (e) {
      try {
        ctx.log("warn", "host.call.fail", {
          method: config.prefix + ".logExport",
          kind: "export",
          errorHash: hash8(String(e && e.message || e))
        });
      } catch (eL) {
        void eL;
      }
      return { ok: false, fileName: fallbackFileName, bytes: 0, fallback: true };
    }
  }
  async function handleLogClear(args) {
    const want = args && args.date ? String(args.date) : "";
    try {
      const dir = typeof ctx.getCacheDir === "function" ? await ctx.getCacheDir() : null;
      if (!dir) return { ok: true, removed: 0 };
      const logDir = await ctx.joinLogPath(dir, config.logDirName);
      if (want === "all") {
        let removedAll = 0;
        const names = await listFileNames(ctx, logDir);
        for (let i = 0; i < names.length; i++) {
          if (!filePattern.test(names[i])) continue;
          if (await deleteOneFile(logDir, names[i])) removedAll += 1;
        }
        return { ok: true, removed: removedAll };
      }
      if (!/^\d{4}-\d{2}-\d{2}$/.test(want)) {
        try {
          ctx.log("warn", "host.call.fail", { method: config.prefix + ".logClear", kind: "clear", errorHash: hash8("bad-date") });
        } catch (eL) {
          void eL;
        }
        return { ok: false, removed: 0 };
      }
      if (config.fileNamePolicy === "four-segment") {
        const names = await listFileNames(ctx, logDir);
        const hits = names.filter((name) => filePattern.test(name) && name.indexOf(want + ".") === 0).sort();
        let removed = 0;
        for (const name of hits) {
          if (await deleteOneFile(logDir, name)) removed += 1;
        }
        return { ok: true, removed };
      }
      const done = await deleteOneFile(logDir, want + ".log");
      return { ok: true, removed: done ? 1 : 0 };
    } catch (e) {
      try {
        ctx.log("warn", "host.call.fail", {
          method: config.prefix + ".logClear",
          kind: "clear",
          errorHash: hash8(String(e && e.message || e))
        });
      } catch (eL) {
        void eL;
      }
      return { ok: false, removed: 0 };
    }
  }
  async function deleteOneFile(logDir, name) {
    const { fs, getPlatform } = ctx;
    try {
      const target = await ctx.resolveTarget(await ctx.joinLogPath(logDir, name));
      try {
        if (fs && typeof fs.unlink === "function") {
          await fs.unlink(target);
          return true;
        }
      } catch (e) {
        void e;
      }
      try {
        const platform = typeof getPlatform === "function" ? await getPlatform() : null;
        if (platform && platform.fs && typeof platform.fs.unlink === "function") {
          await platform.fs.unlink(target);
          return true;
        }
      } catch (e2) {
        void e2;
      }
      try {
        await ctx.writeTarget(target, "");
        return true;
      } catch (e3) {
        void e3;
        return false;
      }
    } catch (e) {
      void e;
      return false;
    }
  }
  async function handleLogGetSwitch() {
    const state = await ctx.loadSwitch();
    return { ok: true, enabled: state.enabled, sampleRate: state.sampleRate };
  }
  async function handleLogSetSwitch(args) {
    const enabled = !!(args && args.enabled);
    const fallbackRate = typeof ctx.getSwitchState === "function" ? ctx.getSwitchState().sampleRate : void 0;
    const sampleRate = args && typeof args.sampleRate === "number" ? args.sampleRate : fallbackRate;
    const state = await ctx.setSwitch(enabled, sampleRate);
    return { ok: true, enabled: state.enabled };
  }
  return {
    handleLogExport,
    handleLogClear,
    handleLogGetSwitch,
    handleLogSetSwitch
  };
}
export {
  createLogPhones
};
