// 派生文件（#564）：由 packages/dsh-log/dist/store.js 原样复制，内容与日志包 0.1.0 一致，人手不改。
// 旧实现（src/host/logStore.js、src/host/logPhones.js）原地只读留存；运行时走本目录经 logFromPackage.js 接线。
// 共存关系：旧文件只读、新文件派生，真搬迁或真删除旧文件另开票。重新生成：node scripts/derive-log-from-package.mjs。
// AUTO-GENERATED by node packages/dsh-log/build.mjs — DO NOT EDIT. Source: packages/dsh-log/src/store.ts
import {
  LOG_DEBOUNCE_MS,
  LEGACY_LOG_DIR_NAME,
  LEGACY_SWITCH_FILE_NAME,
  resolveHostLogConfig,
  resolveLogFileName,
  formatDailyFileName
} from "./config.js";
import { createLogPhones } from "./phones.js";
const LOG_DIR_NAME = LEGACY_LOG_DIR_NAME;
const LOG_SWITCH_FILE = LEGACY_SWITCH_FILE_NAME;
const formatLogFileName = formatDailyFileName;
function hashText(text) {
  let h = 5381;
  const s = String(text || "");
  for (let i = 0; i < s.length; i++) h = (h << 5) + h + s.charCodeAt(i) >>> 0;
  return ("0000000" + h.toString(16)).slice(-8);
}
function createLogStore(deps, configInput) {
  const input = deps || {};
  const fs = input.fs;
  const timer = input.timer;
  const getCacheDir = input.getCacheDir;
  const getPlatform = input.getPlatform;
  const defaultCwd = input.DEFAULT_CWD || "";
  const config = resolveHostLogConfig(
    configInput === void 0 ? { pluginId: "wf" } : configInput
  );
  let queue = [];
  let dropped = 0;
  let switchEnabled = false;
  let switchSampleRate = 1;
  let switchLoaded = false;
  let flushTimer = null;
  let flushing = false;
  let flushQueued = false;
  let pendingPersistFail = null;
  let persistFailOutstanding = false;
  function notePersistFail(op, reason, dir) {
    if (!pendingPersistFail) pendingPersistFail = { op, reason, dir: String(dir || "") };
    try {
      scheduleFlush(false);
    } catch (e) {
      void e;
    }
  }
  let headerInfo = null;
  function currentPid() {
    try {
      const g = globalThis;
      return (g.process && typeof g.process.pid === "number" ? g.process.pid : 0) || 0;
    } catch (e) {
      void e;
      return 0;
    }
  }
  function currentStartedAt() {
    try {
      return headerInfo && headerInfo.startedAt ? headerInfo.startedAt : (/* @__PURE__ */ new Date()).toISOString();
    } catch (e) {
      void e;
      return "";
    }
  }
  function later(fn, ms) {
    try {
      if (timer !== void 0 && timer !== null && typeof timer.timeout === "function") {
        return timer.timeout(fn, ms);
      }
    } catch (e) {
      void e;
    }
    return setTimeout(fn, ms);
  }
  function joinPath(a, b) {
    return String(a).replace(/\/+$/, "") + "/" + String(b).replace(/^\/+/, "");
  }
  async function joinLogPath(dir, name) {
    try {
      const platform = typeof getPlatform === "function" ? await getPlatform() : null;
      if (platform && platform.path && typeof platform.path.join === "function") {
        return platform.path.join(dir, name);
      }
    } catch (e) {
      void e;
    }
    return joinPath(dir, name);
  }
  async function resolveTarget(pathStr) {
    try {
      const platform = typeof getPlatform === "function" ? await getPlatform() : null;
      if (platform && platform.fs && typeof platform.fs.resolve === "function") {
        return await platform.fs.resolve(pathStr);
      }
    } catch (e) {
      void e;
    }
    try {
      if (fs !== void 0 && fs !== null && typeof fs.resolve === "function") {
        return await fs.resolve(pathStr);
      }
    } catch (e2) {
      void e2;
    }
    return pathStr;
  }
  async function readTarget(target) {
    if (fs !== void 0 && fs !== null && typeof fs.readText === "function") {
      return await fs.readText(target);
    }
    const platform = typeof getPlatform === "function" ? await getPlatform() : null;
    if (platform && platform.fs && typeof platform.fs.readText === "function") {
      return await platform.fs.readText(target);
    }
    throw new Error("\u6587\u4EF6\u670D\u52A1\u4E0D\u53EF\u8BFB");
  }
  async function writeTarget(target, text) {
    if (fs !== void 0 && fs !== null && typeof fs.writeText === "function") {
      return await fs.writeText(target, text);
    }
    const platform = typeof getPlatform === "function" ? await getPlatform() : null;
    if (platform && platform.fs && typeof platform.fs.writeText === "function") {
      return await platform.fs.writeText(target, text);
    }
    throw new Error("\u6587\u4EF6\u670D\u52A1\u4E0D\u53EF\u5199");
  }
  async function ensureLogDir(logDir) {
    try {
      const platform = typeof getPlatform === "function" ? await getPlatform() : null;
      if (platform && platform.fs && typeof platform.fs.mkdir === "function") {
        try {
          await platform.fs.mkdir(logDir);
        } catch (e) {
          void e;
        }
        return;
      }
    } catch (e) {
      void e;
    }
    try {
      if (fs !== void 0 && fs !== null && typeof fs.mkdir === "function") await fs.mkdir(logDir);
    } catch (e2) {
      void e2;
    }
  }
  const RESIDENT_EVENTS = /* @__PURE__ */ new Set([
    "snapshot.request",
    "snapshot.cache.miss",
    "repo.resolve.tier",
    "gh.exec",
    "gh.timeout",
    "gh.resolve.fail",
    "graphql.fallback",
    "issues.fallback",
    "snapshot.built",
    "panelSync.dirty",
    "registry.select",
    "detection.detect",
    "skill.probe",
    "skill.pending.cap",
    "host.call",
    "host.call.fail",
    "snapshot.hydrate",
    "backend.switch",
    "naming.guard",
    "naming.lock",
    "panel.open",
    "statusbar.fallback",
    "dock.rehydrate",
    "storage.fail",
    "chain.derive.error",
    "fallback.chain",
    "client.snapshot.miss",
    "host.start",
    "update.install.exec",
    "labelColors.write",
    "guide.inject",
    "healthCheck.inject",
    "choiceStore.file.bad",
    "choiceStore.write.fail",
    "issues.page",
    "sessionTickets.chain",
    "chain.backoff",
    "host.dispatch.empty",
    "naming.summary",
    "cwd.persisted",
    "update.install.manifestSync",
    "git.exec",
    "git.exec.fail"
  ]);
  function isEnabled(level, event) {
    if (level === "error" || level === "warn") return true;
    if (typeof event === "string" && RESIDENT_EVENTS.has(event)) return true;
    return switchEnabled === true;
  }
  function dropForRoom(level) {
    if (level === "error" || level === "warn") {
      for (let i = 0; i < queue.length; i++) {
        if (queue[i].level !== "error" && queue[i].level !== "warn") {
          queue.splice(i, 1);
          dropped += 1;
          return;
        }
      }
    }
    dropped += 1;
  }
  function log(level, event, fields) {
    if (!isEnabled(level, event)) return;
    if (queue.length >= config.maxQueue) {
      dropForRoom(level);
      if (queue.length >= config.maxQueue) return;
    }
    queue.push({
      ts: Date.now(),
      level,
      event: String(event || ""),
      fields: fields && typeof fields === "object" ? fields : {}
    });
    if (level === "error" || level === "warn") scheduleFlush(true);
    else scheduleFlush(false);
  }
  function scheduleFlush(immediate) {
    if (immediate) {
      if (flushTimer !== null) {
        try {
          clearTimeout(flushTimer);
        } catch (e) {
          void e;
        }
        flushTimer = null;
      }
      later(flushNow, 0);
      return;
    }
    if (flushTimer !== null) return;
    flushTimer = later(flushNow, LOG_DEBOUNCE_MS);
  }
  function flush() {
    if (flushTimer !== null) {
      try {
        clearTimeout(flushTimer);
      } catch (e) {
        void e;
      }
      flushTimer = null;
    }
    later(flushNow, 0);
    return { ok: true };
  }
  async function flushNow() {
    flushTimer = null;
    if (flushing) {
      flushQueued = true;
      return;
    }
    flushing = true;
    try {
      while (queue.length > 0) {
        const batch = queue.splice(0, queue.length);
        try {
          if (await writeBatch(batch)) persistFailOutstanding = false;
        } catch (e) {
          void e;
          dropped += batch.length;
        }
      }
    } finally {
      flushing = false;
      if (pendingPersistFail) {
        const f = pendingPersistFail;
        pendingPersistFail = null;
        if (!persistFailOutstanding) {
          persistFailOutstanding = true;
          try {
            log("warn", "log.persist.fail", { op: f.op, reason: f.reason, dirHash: hashText(f.dir) });
          } catch (e) {
            void e;
          }
        }
      }
      if (flushQueued) {
        flushQueued = false;
        if (queue.length > 0) scheduleFlush(false);
      }
    }
  }
  async function writeBatch(batch) {
    if (!batch || batch.length === 0) return true;
    const lines = [];
    for (let i = 0; i < batch.length; i++) {
      try {
        lines.push(
          JSON.stringify({ ts: batch[i].ts, level: batch[i].level, event: batch[i].event, fields: batch[i].fields })
        );
      } catch (e) {
        void e;
        dropped += 1;
      }
    }
    if (lines.length === 0) return true;
    const text = lines.join("\n") + "\n";
    let failDir = "";
    try {
      const dir = typeof getCacheDir === "function" ? await getCacheDir() : null;
      if (!dir) {
        dropped += lines.length;
        notePersistFail("writeBatch", "no-dir", "");
        return false;
      }
      const logDir = await joinLogPath(dir, config.logDirName);
      failDir = logDir;
      await ensureLogDir(logDir);
      const fileName = resolveLogFileName(config, /* @__PURE__ */ new Date(), currentPid(), currentStartedAt());
      const target = await resolveTarget(await joinLogPath(logDir, fileName));
      let existing = "";
      try {
        existing = await readTarget(target);
      } catch (eRead) {
        void eRead;
        existing = "";
      }
      await writeTarget(target, String(existing || "") + text);
      return true;
    } catch (eWrite) {
      void eWrite;
      dropped += lines.length;
      notePersistFail("writeBatch", "write-fail", failDir);
      return false;
    }
  }
  function getDroppedCount() {
    return dropped;
  }
  function getSwitchState() {
    return { enabled: switchEnabled, sampleRate: switchSampleRate };
  }
  async function loadSwitch() {
    if (switchLoaded) return getSwitchState();
    switchLoaded = true;
    try {
      const dir = typeof getCacheDir === "function" ? await getCacheDir() : null;
      if (!dir) return getSwitchState();
      const target = await resolveTarget(await joinLogPath(dir, config.switchFileName));
      const txt = await readTarget(target);
      if (!txt) return getSwitchState();
      const parsed = JSON.parse(txt);
      if (parsed && typeof parsed.enabled === "boolean") switchEnabled = parsed.enabled;
      if (parsed && typeof parsed.sampleRate === "number") switchSampleRate = parsed.sampleRate;
    } catch (e) {
      void e;
      notePersistFail("readBack", "read-fail", "");
    }
    return getSwitchState();
  }
  async function persistSwitch() {
    let failDir = "";
    try {
      const dir = typeof getCacheDir === "function" ? await getCacheDir() : null;
      if (!dir) {
        notePersistFail("persistSwitch", "no-dir", "");
        return;
      }
      failDir = String(dir || "");
      const target = await resolveTarget(await joinLogPath(dir, config.switchFileName));
      await writeTarget(target, JSON.stringify({ enabled: switchEnabled, sampleRate: switchSampleRate }));
    } catch (e) {
      void e;
      notePersistFail("persistSwitch", "write-fail", failDir);
    }
  }
  async function setSwitch(enabled, sampleRate) {
    switchEnabled = enabled === true;
    if (typeof sampleRate === "number" && isFinite(sampleRate)) switchSampleRate = sampleRate;
    await persistSwitch();
    return getSwitchState();
  }
  async function writeStartupHeader() {
    try {
      const dir = typeof getCacheDir === "function" ? await getCacheDir() : null;
      const pid = currentPid();
      headerInfo = { pid, startedAt: (/* @__PURE__ */ new Date()).toISOString(), dir: dir || defaultCwd || "" };
      log("info", "host.start", { pid: headerInfo.pid, startedAt: headerInfo.startedAt, dir: headerInfo.dir });
    } catch (e) {
      void e;
    }
    return headerInfo;
  }
  function getHeaderInfo() {
    return headerInfo;
  }
  async function handleLogBatch(args) {
    try {
      const entries = args && Array.isArray(args.entries) ? args.entries : [];
      for (let i = 0; i < entries.length; i++) {
        const item = entries[i] || {};
        try {
          log(item.level, item.event, item.fields);
        } catch (e) {
          void e;
          dropped += 1;
        }
      }
      return { ok: true, accepted: entries.length, dropped: getDroppedCount() };
    } catch (e) {
      void e;
      return { ok: true, accepted: 0, dropped: getDroppedCount() };
    }
  }
  const phones = createLogPhones({
    fs,
    getCacheDir,
    getPlatform,
    DEFAULT_CWD: defaultCwd,
    config,
    joinPath,
    joinLogPath,
    resolveTarget,
    readTarget,
    writeTarget,
    log,
    getSwitchState,
    getHeaderInfo,
    loadSwitch,
    setSwitch
  });
  async function handleLogExport(args) {
    return phones.handleLogExport(args);
  }
  async function handleLogClear(args) {
    return phones.handleLogClear(args);
  }
  async function handleLogGetSwitch() {
    return phones.handleLogGetSwitch();
  }
  async function handleLogSetSwitch(args) {
    return phones.handleLogSetSwitch(args);
  }
  return {
    config,
    isEnabled,
    log,
    flush,
    flushNow,
    getDroppedCount,
    loadSwitch,
    setSwitch,
    getSwitchState,
    writeStartupHeader,
    getHeaderInfo,
    handleLogBatch,
    handleLogExport,
    handleLogClear,
    handleLogGetSwitch,
    handleLogSetSwitch
  };
}
export {
  LOG_DEBOUNCE_MS,
  LOG_DIR_NAME,
  LOG_SWITCH_FILE,
  createLogStore,
  formatDailyFileName,
  formatLogFileName
};
