// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/attention.ts
export const ATTENTION_ACTIVE_CAP_FALLBACK = 2;
export const ATTENTION_SIGNAL_KINDS = [
  "focus",
  "panel-open",
  "session-switch",
  "heartbeat",
  "window-blur",
  "panel-hidden"
];
export const ATTENTION_HUMAN_SIGNALS = ["focus", "panel-open", "session-switch"];
export function createAttentionState() {
  return { windows: {}, seen: {} };
}
export function report(state, input, nowMs) {
  const s = cloneState(state);
  const windowId = String(input && input.windowId || "");
  const root = String(input && input.workspaceRoot || "").trim();
  const kind = kindOf(input && input.kind);
  const visible = !!(input && input.visible);
  const at = numOr(input && input.atMs, nowMs);
  const human = numOr(input && input.lastHumanInputMs, 0);
  if (!windowId) return { accepted: false, state: s };
  const prev = s.windows[windowId];
  const prevRoot = prev ? String(prev.root || "") : "";
  const keepRoot = root || prevRoot;
  if (!keepRoot) {
    s.windows[windowId] = { root: "", lastSeenMs: at, visible, lastHumanInputMs: human };
    return { accepted: false, state: s };
  }
  const isHuman = ATTENTION_HUMAN_SIGNALS.indexOf(kind) >= 0;
  const heartbeatOk = kind === "heartbeat" && !!prev && prevRoot !== "" && visible;
  const accepted = isHuman || heartbeatOk;
  const advance = accepted && (isHuman || visible);
  s.windows[windowId] = {
    root: keepRoot,
    lastSeenMs: advance ? at : prev ? prev.lastSeenMs : at,
    visible,
    lastHumanInputMs: human || (prev ? prev.lastHumanInputMs : 0)
  };
  const known = s.seen[keepRoot];
  if (advance) s.seen[keepRoot] = { at, visible };
  else if (!known) s.seen[keepRoot] = { at: prev ? prev.lastSeenMs : at, visible };
  return { accepted, state: s };
}
export function collect(state, nowMs, limits) {
  const maxActive = Math.max(1, Math.floor(numOr(limits && limits.maxActive, ATTENTION_ACTIVE_CAP_FALLBACK)));
  const lingerMs = Math.max(0, numOr(limits && limits.lingerMs, 0));
  const expiryMs = Math.max(0, numOr(limits && limits.expiryMs, 0));
  const probeMs = Math.max(0, numOr(limits && limits.probeIntervalMs, 0));
  const lingerProbeMs = Math.max(0, numOr(limits && limits.probeIntervalLingerMs, probeMs));
  const s = state || createAttentionState();
  const cand = candidatesOf(s);
  const tracked = trackedRoots(s);
  let newest = 0;
  for (let i = 0; i < cand.length; i++) if (cand[i].lastSeenMs > newest) newest = cand[i].lastSeenMs;
  pruneSeen(s);
  if (!newest || nowMs - newest > expiryMs) {
    const all = tracked.slice();
    for (let i = 0; i < cand.length; i++) if (all.indexOf(cand[i].root) < 0) all.push(cand[i].root);
    return { active: [], keep: [], cancel: all, lingerRoot: "", lingerDelayMs: 0, collaped: true, keepers: 0 };
  }
  cand.sort(compareCandidates);
  const active = [];
  const keep = {};
  for (let i = 0; i < cand.length; i++) {
    if (active.length >= maxActive) break;
    const c = cand[i];
    if (!c.visible) break;
    active.push({ root: c.root, audience: "probe", intervalMs: probeMs });
    keep[c.root] = true;
  }
  const keepers = active.length;
  const lingerCand = firstUnkept(cand, keep);
  let lingerRoot = "";
  let lingerDelayMs = 0;
  if (lingerCand) {
    const remaining = lingerMs - (nowMs - lingerCand.lastSeenMs);
    if (remaining > 0) {
      lingerRoot = lingerCand.root;
      lingerDelayMs = remaining;
    }
  }
  if (lingerRoot) {
    keep[lingerRoot] = true;
    active.push({ root: lingerRoot, audience: "linger", intervalMs: lingerProbeMs });
  }
  const cancel = [];
  for (let i = 0; i < tracked.length; i++) if (!keep[tracked[i]]) cancel.push(tracked[i]);
  return {
    active,
    keep: Object.keys(keep),
    cancel,
    lingerRoot,
    lingerDelayMs,
    collaped: false,
    keepers
  };
}
export function timerPlanFor(plan, root, nowMs) {
  const key = String(root || "");
  const list = plan && plan.active || [];
  for (let i = 0; i < list.length; i++) if (list[i].root === key) return { intervalMs: list[i].intervalMs };
  return null;
}
export function candidatesAt(state) {
  return candidatesOf(state || createAttentionState()).map(function(c) {
    return { root: c.root, lastSeenMs: c.lastSeenMs, visible: c.visible };
  });
}
export function lingerDelayAt(plan, root) {
  if (!plan || !plan.lingerRoot || plan.lingerRoot !== String(root || "")) return null;
  return plan.lingerDelayMs > 0 ? plan.lingerDelayMs : null;
}
export function heartbeatIntervalMs(limits) {
  return Math.max(0, numOr(limits && limits.heartbeatMs, 0));
}
export function hasAnyWindow(state) {
  const w = state && state.windows || {};
  for (const id of Object.keys(w)) if (w[id] && w[id].root) return true;
  const seen = state && state.seen || {};
  for (const r of Object.keys(seen)) if (r) return true;
  return false;
}
function firstUnkept(cand, keep) {
  for (let i = 0; i < cand.length; i++) if (!keep[cand[i].root]) return cand[i];
  return null;
}
function compareCandidates(a, b) {
  if (a.visible !== b.visible) return a.visible ? -1 : 1;
  if (a.lastSeenMs !== b.lastSeenMs) return b.lastSeenMs - a.lastSeenMs;
  if (a.lastHumanInputMs !== b.lastHumanInputMs) return b.lastHumanInputMs - a.lastHumanInputMs;
  return a.root < b.root ? -1 : a.root > b.root ? 1 : 0;
}
function candidatesOf(s) {
  const seen = s && s.seen || {};
  const liveWindows = {};
  const wins = s && s.windows || {};
  for (const id of Object.keys(wins)) {
    const w = wins[id];
    if (!w || !w.root) continue;
    const cur = liveWindows[w.root];
    const at = numOr(w.lastSeenMs, 0);
    if (!cur || at > cur.newest) {
      liveWindows[w.root] = { newest: at, visible: !!w.visible, human: numOr(w.lastHumanInputMs, 0) };
    }
  }
  const out = [];
  for (const root of Object.keys(seen)) {
    const hit = seen[root];
    if (!root || !hit) continue;
    const live = liveWindows[root];
    out.push({
      root,
      lastSeenMs: numOr(hit.at, 0),
      visible: !!(live && live.visible),
      lastHumanInputMs: live ? live.human : 0
    });
  }
  return out;
}
function trackedRoots(s) {
  const seen = {};
  const out = [];
  const add = function(r) {
    if (r && !seen[r]) {
      seen[r] = true;
      out.push(r);
    }
  };
  const wins = s && s.windows || {};
  for (const id of Object.keys(wins)) add(wins[id] && wins[id].root);
  const hist = s && s.seen || {};
  for (const r of Object.keys(hist)) add(r);
  return out;
}
function kindOf(kind) {
  const k = String(kind || "");
  return ATTENTION_SIGNAL_KINDS.indexOf(k) >= 0 ? k : "focus";
}
function numOr(v, fallback) {
  return typeof v === "number" && isFinite(v) ? v : fallback;
}
const SEEN_ROOTS_MAX = 64;
let pruneCounter = 0;
function pruneSeen(s) {
  const all = Object.keys(s.seen);
  if (all.length <= SEEN_ROOTS_MAX) return;
  pruneCounter += 1;
  if (pruneCounter % 128 !== 0) return;
  const rows = [];
  for (let i = 0; i < all.length; i++) rows.push({ root: all[i], at: numOr(s.seen[all[i]].at, 0) });
  rows.sort(function(a, b) {
    return b.at - a.at;
  });
  for (let i = SEEN_ROOTS_MAX; i < rows.length; i++) delete s.seen[rows[i].root];
}
function cloneState(s) {
  const out = { windows: {}, seen: {} };
  const wins = s && s.windows || {};
  for (const id of Object.keys(wins)) {
    const w = wins[id];
    if (!w) continue;
    out.windows[id] = {
      root: String(w.root || ""),
      lastSeenMs: numOr(w.lastSeenMs, 0),
      visible: !!w.visible,
      lastHumanInputMs: numOr(w.lastHumanInputMs, 0)
    };
  }
  const hist = s && s.seen || {};
  for (const r of Object.keys(hist)) {
    const h = hist[r];
    if (!h) continue;
    out.seen[r] = { at: numOr(h.at, 0), visible: !!h.visible };
  }
  return out;
}
