// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/backend-quota.ts
export const BACKEND_BUDGET_MODELS = Object.freeze([
  Object.freeze({
    backendId: "github",
    kind: "two-buckets",
    countsRequests: true,
    countsPoints: true,
    independentBuckets: true,
    summary: "GitHub\uFF1A\u4E24\u4E2A\u4E92\u76F8\u72EC\u7ACB\u7684\u6876\u2014\u2014REST \u6570\u51FA\u7AD9\u8BF7\u6C42\u6761\u6570\u3001GraphQL \u6570\u70B9\u6570\uFF0C\u4E24\u6876\u5404\u81EA\u4E00\u4EFD\u989D\u5EA6\u3001\u4E92\u4E0D\u6298\u7B97\uFF1B\u4E0A\u9650\u7531\u8D26\u672C\u6BCF\u5206\u949F\u4ECE\u670D\u52A1\u7AEF\u8BFB\u6570\u53D6\u56DE\u6765\u3002"
  }),
  Object.freeze({
    backendId: "gitlab",
    kind: "requests-only",
    countsRequests: true,
    countsPoints: false,
    independentBuckets: false,
    summary: "GitLab\uFF1A\u53EA\u6709\u51FA\u7AD9\u8BF7\u6C42\u6761\u6570\u8FD9\u4E00\u79CD\u53E3\u5F84\uFF0C\u6CA1\u6709\u70B9\u6570\u5236\uFF1B\u989D\u5EA6\u6570\u503C\u5F85\u5B9E\u6D4B\uFF0C\u6B64\u5904\u4E0D\u5199\u4E00\u4E2A\u7F16\u51FA\u6765\u7684\u6570\u3002"
  }),
  Object.freeze({
    backendId: "markdown",
    kind: "off-network",
    countsRequests: false,
    countsPoints: false,
    independentBuckets: false,
    summary: "\u672C\u5730 Markdown\uFF1A\u8BFB\u5199\u90FD\u5728\u672C\u673A\u6587\u4EF6\uFF0C\u4E0D\u51FA\u7AD9\uFF0C\u56E0\u6B64\u6CA1\u6709\u989D\u5EA6\u4E5F\u6CA1\u6709\u82B1\u8D39\u3002"
  }),
  Object.freeze({
    backendId: "",
    kind: "unknown",
    countsRequests: true,
    countsPoints: false,
    independentBuckets: false,
    summary: "\u8FD8\u6CA1\u8BA4\u51FA\u6765\u7684\u540E\u7AEF\uFF1A\u53EA\u6309\u51FA\u7AD9\u8BF7\u6C42\u6761\u6570\u8BB0\u8D26\uFF0C\u70B9\u6570\u53E3\u5F84\u7B49\u90A3\u4E2A\u540E\u7AEF\u5B9A\u4E0B\u6765\u518D\u8865\uFF08\u5C11\u82B1\u7684\u4E00\u4FA7\uFF0C\u4E0D\u662F\u591A\u82B1\u7684\u4E00\u4FA7\uFF09\u3002"
  })
]);
export function backendBudgetModel(backendId) {
  const id = String(backendId || "").trim().toLowerCase();
  for (const m of BACKEND_BUDGET_MODELS) {
    if (m.backendId !== "" && m.backendId === id) return m;
  }
  for (const m of BACKEND_BUDGET_MODELS) {
    if (m.backendId === "") return m;
  }
  return { backendId: "", kind: "unknown", countsRequests: true, countsPoints: false, independentBuckets: false, summary: "\u6CA1\u6709\u53EF\u7528\u7684\u989D\u5EA6\u6A21\u578B\uFF0C\u6309\u53EA\u8BB0\u8BF7\u6C42\u6570\u5904\u7406\u3002" };
}
function nonNegative(v) {
  const n = typeof v === "number" && isFinite(v) ? v : 0;
  return n > 0 ? n : 0;
}
export function priceSpend(backendId, spend) {
  const m = backendBudgetModel(backendId);
  const requests = m.countsRequests ? nonNegative(spend && spend.requests) : 0;
  const points = m.countsPoints ? nonNegative(spend && spend.points) : 0;
  const note = m.kind === "two-buckets" ? "\u4E24\u4E2A\u6876\u90FD\u8BB0\uFF1A\u8BF7\u6C42\u6761\u6570\u8FDB REST \u6876\u3001\u70B9\u6570\u8FDB GraphQL \u6876\uFF0C\u4E24\u6876\u4E92\u4E0D\u6298\u7B97\u3002" : m.kind === "requests-only" ? "\u53EA\u8BB0\u51FA\u7AD9\u8BF7\u6C42\u6761\u6570\uFF1A\u8FD9\u4E2A\u540E\u7AEF\u6CA1\u6709\u70B9\u6570\u5236\uFF08\u4E0E GitHub \u7684\u4E24\u6876\u4E0D\u540C\uFF0C\u989D\u5EA6\u6570\u503C\u5F85\u5B9E\u6D4B\uFF09\u3002" : m.kind === "off-network" ? "\u4E0D\u51FA\u7AD9\uFF0C\u8BB0 0\uFF1A\u672C\u5730 Markdown \u540E\u7AEF\u8BFB\u5199\u7684\u662F\u672C\u673A\u6587\u4EF6\uFF0C\u4E0D\u82B1\u4EFB\u4F55\u989D\u5EA6\u3002" : "\u53EA\u8BB0\u51FA\u7AD9\u8BF7\u6C42\u6761\u6570\uFF1A\u8FD8\u6CA1\u8BA4\u51FA\u6765\u8FD9\u4E2A\u540E\u7AEF\uFF0C\u70B9\u6570\u53E3\u5F84\u5F85\u5B9A\uFF0C\u5148\u6309\u66F4\u7701\u7684\u4E00\u4FA7\u8BB0\u3002";
  return { backendId: m.backendId === "" ? String(backendId || "") : m.backendId, kind: m.kind, requests, points, pointsCounted: m.countsPoints, note };
}
export function usesIndependentBuckets(backendId) {
  return backendBudgetModel(backendId).independentBuckets;
}
