// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/backoff.ts
export const MIN_BACKOFF_STEPS = 2;
export function initialChainBackoff() {
  return { step: 0, evaluatedAtMs: 0, allGreen: false };
}
function clampStep(step, limits) {
  const seq = limits.backoffMs;
  if (!seq || seq.length === 0) return 0;
  const n = Math.floor(step);
  if (!isFinite(n) || n <= 0) return 0;
  return Math.min(n, seq.length - 1);
}
export function backoffDelayMs(step, limits) {
  const seq = limits.backoffMs;
  if (!seq || seq.length === 0) return 0;
  return seq[clampStep(step, limits)];
}
export function advanceChainStep(step, progressed, limits) {
  if (progressed) return 0;
  return clampStep(step + 1, limits);
}
export function noteChainEvaluation(state, evaluatedAtMs, allGreen, progressed, limits) {
  return {
    step: advanceChainStep(state ? state.step : 0, progressed, limits),
    evaluatedAtMs,
    allGreen: !!allGreen
  };
}
export function chainCacheUsable(state, nowMs, limits) {
  if (!state || !state.allGreen) return false;
  const at = Number(state.evaluatedAtMs);
  if (!isFinite(at) || at <= 0) return false;
  const now = Number(nowMs);
  if (!isFinite(now) || now < at) return false;
  return now - at < limits.allGreenTtlMs;
}
export function chainRefreshVerdict(state, nowMs, limits) {
  if (chainCacheUsable(state, nowMs, limits)) {
    return { needed: false, reason: "all-green-cached", waitMs: 0 };
  }
  if (!state || !state.allGreen) {
    const delay = backoffDelayMs(state ? state.step : 0, limits);
    const at = state && isFinite(Number(state.evaluatedAtMs)) ? Number(state.evaluatedAtMs) : 0;
    const elapsed = at > 0 && Number(nowMs) >= at ? Number(nowMs) - at : limits.backoffMs[0];
    if (elapsed >= delay) return { needed: true, reason: "not-green-due", waitMs: 0 };
    return { needed: false, reason: "not-green-too-soon", waitMs: delay - elapsed };
  }
  return { needed: false, reason: "all-green-expired", waitMs: backoffDelayMs(limits.backoffMs.length - 1, limits) };
}
export function preflightUsable(ok, checkedAtMs, nowMs, limits) {
  if (!ok) return false;
  const at = Number(checkedAtMs);
  if (!isFinite(at) || at <= 0) return false;
  const now = Number(nowMs);
  if (!isFinite(now) || now < at) return false;
  return now - at < limits.preflightTtlMs;
}
export function preflightRetryAllowed(failuresThisEvaluation, limits) {
  const n = Math.floor(Number(failuresThisEvaluation));
  if (!isFinite(n) || n < 0) return false;
  return n <= limits.preflightRetryAfterFailure;
}
