// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/budget.ts
export const PROBE_INTERVAL_MS = 5e3;
export const PROBE_INTERVAL_YELLOW_MS = 12e4;
export const PROBE_INTERVAL_LINGER_MS = 15e3;
export const REBUILD_MIN_INTERVAL_YELLOW_MS = 3e5;
export const RECONCILE_INTERVAL_MS = 10 * 6e4;
export const PREFLIGHT_TTL_MS = 10 * 6e4;
export const PREFLIGHT_RETRY_AFTER_FAILURE = 1;
export const CHAIN_BACKOFF_MS = [8e3, 3e4, 2 * 6e4, 5 * 6e4];
export const CHAIN_ALL_GREEN_TTL_MS = 30 * 6e4;
export const PATCH_MERGE_WINDOW_MS = 1e4;
export const DEFER_EXPIRY_MS = 5 * 6e4;
export const ACTIVE_LINGER_MS = 3e4;
export const ATTENTION_HEARTBEAT_MS = 2e4;
export const ATTENTION_EXPIRY_MS = 9e4;
export const PLUGIN_SHARE_OF_REMAINING = 0.35;
export const PLUGIN_HOURLY_CAP = 1750;
export const READ_SHARE_OF_ALLOWANCE = 0.7;
export const READ_HOURLY_CAP = 1225;
export const WRITE_RESERVED_SHARE = 0.3;
export const WRITE_HOURLY_CAP = 525;
export const TIER_GREEN_BELOW = 0.6;
export const TIER_RED_AT = 0.85;
export const MAX_ACTIVE_WORKSPACES = 2;
export const MAX_PAGES = 10;
export const AI_TOOL_MAX_POINTS_PER_CALL = 600;
export const AI_TOOL_MAX_REQUESTS_PER_CALL = 400;
export const AI_TOOL_MAX_POINTS_PER_HOUR = 2e3;
export const AI_TOOL_MAX_REQUESTS_PER_HOUR = 1500;
export const AI_TOOL_MAX_CHILD_TICKETS_PER_CALL = 60;
export const AI_TOOL_SHARD_SIZE = AI_TOOL_MAX_CHILD_TICKETS_PER_CALL;
export function hourlyAllowance(remainingPoints) {
  const capped = Math.min(remainingPoints * PLUGIN_SHARE_OF_REMAINING, PLUGIN_HOURLY_CAP);
  return Math.max(0, Math.floor(capped));
}
export function readAllowance(allowancePoints) {
  return Math.max(0, Math.floor(allowancePoints * READ_SHARE_OF_ALLOWANCE));
}
export function writeReserve(allowancePoints) {
  return Math.max(0, Math.floor(allowancePoints * WRITE_RESERVED_SHARE));
}
export function usedRatio(usedPoints, allowancePoints) {
  if (!(allowancePoints > 0)) return 1;
  return usedPoints / allowancePoints;
}
export function tierFor(ratio) {
  if (ratio < TIER_GREEN_BELOW) return "green";
  if (ratio < TIER_RED_AT) return "yellow";
  return "red";
}
export function shardPlan(totalChildTickets) {
  const total = Math.max(0, Math.floor(totalChildTickets));
  const shards = Math.max(1, Math.ceil(total / AI_TOOL_SHARD_SIZE));
  return { shards, perShard: Math.max(1, Math.ceil(total / shards)) };
}
export function aiToolCallWithinCaps(points, requests) {
  return points <= AI_TOOL_MAX_POINTS_PER_CALL && requests <= AI_TOOL_MAX_REQUESTS_PER_CALL;
}
export function aiToolHourWithinCaps(points, requests) {
  return points <= AI_TOOL_MAX_POINTS_PER_HOUR && requests <= AI_TOOL_MAX_REQUESTS_PER_HOUR;
}
export const HOUR_MS = 36e5;
export const QUOTA_SYNC_INTERVAL_MS = 6e4;
export const QUOTA_READ_COST_REQUESTS = 1;
export const PROBE_COST_REQUESTS = 1;
export const PREFLIGHT_COST_REQUESTS = 2;
export const CHAIN_EVAL_COST_REQUESTS = 3;
export const PATCH_COST_POINTS_MIN = 1;
export const PATCH_COST_POINTS_MAX = 2;
export const PATCH_COST_REQUESTS = 1;
export const PAGE_COST_POINTS = 2;
export const PAGE_COST_POINTS_HALF = 1;
export const PR_PAGE_COST_POINTS = 2;
export const SUB_ISSUES_PAGE_COST_POINTS = 3;
export const COUNT_COST_POINTS = 1;
export const LIST_PAGE_COST_REQUESTS = 1;
export const PR_PAGE_COST_REQUESTS = 1;
export const COUNT_COST_REQUESTS = 1;
export const REBUILD_PAGE_COUNT = 5;
export const REBUILD_PR_PAGE_COUNT = 1;
export const REBUILD_COST_POINTS = REBUILD_PAGE_COUNT * PAGE_COST_POINTS + REBUILD_PR_PAGE_COUNT * PR_PAGE_COST_POINTS + COUNT_COST_POINTS;
export const REBUILD_COST_REQUESTS = REBUILD_PAGE_COUNT * LIST_PAGE_COST_REQUESTS + REBUILD_PR_PAGE_COUNT * PR_PAGE_COST_REQUESTS + COUNT_COST_REQUESTS;
export const WRITE_EVENT_COST_REQUESTS = 1;
export const SWITCH_COST_REQUESTS = PROBE_COST_REQUESTS;
export const FRESHNESS_YELLOW_MS = 5 * 6e4;
export const FRESHNESS_RED_MS = 30 * 6e4;
export function freshnessLevel(ageMs) {
  const age = typeof ageMs === "number" && isFinite(ageMs) && ageMs > 0 ? ageMs : 0;
  if (age > FRESHNESS_RED_MS) return "red";
  if (age > FRESHNESS_YELLOW_MS) return "yellow";
  return "fresh";
}
export function lagPromiseFor(tier) {
  if (tier === "red") return { paused: true, maxLagMs: null };
  if (tier === "yellow") return { paused: false, maxLagMs: PROBE_INTERVAL_YELLOW_MS };
  return { paused: false, maxLagMs: PROBE_INTERVAL_MS };
}
