// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/chain.ts
export const CHAIN_SESSION_CAP = 20;
export const CHAIN_BACKENDS = ["github", "gitlab", "markdown"];
export const CHAIN_ACTIONS = ["create", "plan", "comment", "edit", "state", "link", "report", "file-write", "other-write"];
export const CHAIN_REASONS = {
  "chain.record": "\u8FD9\u662F\u4E00\u6B21\u5199\uFF08\u6216\u660E\u786E\u7684\u5904\u7406\u52A8\u4F5C\uFF09\uFF0C\u4E14\u8BF4\u7684\u662F\u54EA\u4E00\u5F20\u7968\uFF1A\u8BB0\u8FDB\u94FE",
  "chain.read-excluded": "\u8FD9\u662F\u4E00\u6B21\u8BFB\uFF08\u987A\u624B\u770B\u4E00\u773C\uFF09\uFF1A\u4E0D\u8FDB\u94FE\uFF0C\u94FE\u4E0A\u53EA\u7559\u5199\u4E0E\u660E\u786E\u7684\u5904\u7406\u52A8\u4F5C",
  "chain.no-ticket": "\u8FD9\u6B21\u52A8\u4F5C\u662F\u5199\uFF0C\u4F46\u8BF4\u4E0D\u51FA\u662F\u54EA\u4E00\u5F20\u7968\uFF1A\u4E0D\u8BB0\uFF08\u8BB0\u4E86\u4E5F\u6CA1\u6CD5\u5728\u754C\u9762\u4E0A\u70B9\u540D\u662F\u54EA\u5F20\uFF09",
  "chain.not-succeeded": "\u8FD9\u6B21\u8C03\u7528\u6CA1\u6709\u6210\u529F\uFF1A\u4EC0\u4E48\u90FD\u6CA1\u6539\uFF0C\u4E0D\u8BB0",
  "chain.not-a-result": "\u8FD9\u4E0D\u662F\u4E00\u6B21\u8C03\u7528\u7684\u7ED3\u679C\uFF08\u8C03\u7528\u521A\u5F00\u59CB\u6216\u8BA4\u4E0D\u51FA\u7684\u5F62\u6001\uFF09\uFF1A\u4E0D\u8BB0",
  "chain.unknown-source": "\u8BF4\u4E0D\u6E05\u8FD9\u6761\u7EBF\u7D22\u662F\u4ECE\u54EA\u6765\u7684\uFF08\u4E0D\u662F\u5DE5\u5177\u53C2\u6570\u3001\u547D\u4EE4\u884C\u6216\u7968\u6587\u4EF6\u8DEF\u5F84\uFF09\uFF1A\u4E0D\u8BB0",
  "chain.bad-shard": "\u8FD9\u4E2A\u4F1A\u8BDD\u7684\u6563\u5217\u7B97\u4E0D\u51FA\u6765\uFF08\u4F1A\u8BDD id \u662F\u7A7A\u7684\uFF09\uFF1A\u4E0D\u8BB0\uFF0C\u514D\u5F97\u628A\u4E0D\u540C\u4F1A\u8BDD\u7684\u7968\u8BB0\u8FDB\u540C\u4E00\u683C",
  "chain.bad-root": "\u5DE5\u4F5C\u533A\u6839\u6563\u5217\u4E0D\u50CF\u6563\u5217\uFF08\u957F\u5EA6\u6216\u5B57\u7B26\u4E0D\u5BF9\uFF09\uFF1A\u4E0D\u8BB0\uFF0C\u5B81\u53EF\u6F0F\u4E00\u6B21\u4E5F\u4E0D\u628A\u539F\u6587\u5199\u8FDB\u952E\u91CC",
  "chain.bad-backend": "\u540E\u7AEF\u540D\u4E0D\u5728\u4E09\u4E2A\u540E\u7AEF\u91CC\uFF1A\u4E0D\u8BB0\uFF0C\u4E0D\u540C\u540E\u7AEF\u7684\u7968 key \u4E0D\u901A\u7528"
};
export function chainReasonText(code) {
  const key = String(code || "");
  return Object.prototype.hasOwnProperty.call(CHAIN_REASONS, key) ? CHAIN_REASONS[key] : key;
}
function hashDjb2(text) {
  let h = 5381;
  for (let i = 0; i < text.length; i++) h = (h << 5) + h + text.charCodeAt(i) >>> 0;
  return ("0000000" + h.toString(16)).slice(-8);
}
function hashFnv(text) {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h = (h ^ text.charCodeAt(i)) >>> 0;
    h = Math.imul(h, 16777619) >>> 0;
  }
  return ("0000000" + h.toString(16)).slice(-8);
}
export function chainRootHash(rootKey) {
  const text = rootKey === null || rootKey === void 0 ? "" : String(rootKey);
  if (!text) return "";
  return hashDjb2(text) + hashFnv(text);
}
export function chainSessionShardId(sessionId) {
  const text = sessionId === null || sessionId === void 0 ? "" : String(sessionId).trim();
  if (!text) return "";
  return hashDjb2(text) + hashFnv(text);
}
function isFingerprintLike(v) {
  return typeof v === "string" && /^[0-9a-f]{16}$/.test(v);
}
export function chainBackendId(raw) {
  const text = raw === null || raw === void 0 ? "" : String(raw).trim().toLowerCase();
  return CHAIN_BACKENDS.indexOf(text) >= 0 ? text : "";
}
export function chainTicketKey(raw) {
  if (typeof raw === "number" && isFinite(raw)) raw = String(Math.floor(raw));
  if (typeof raw !== "string") return "";
  const text = raw.trim().replace(/^#/, "");
  if (!/^\d{1,10}$/.test(text)) return "";
  const noZeros = text.replace(/^0+(?=\d)/, "");
  return noZeros;
}
export function chainTicketKeyFromPath(path) {
  return chainTicketAndEffortFromPath(path).ticketKey;
}
export function chainEffortId(raw) {
  if (raw === null || raw === void 0) return "";
  const text = String(raw).trim();
  if (!text) return "";
  if (text.indexOf("/") >= 0 || text.indexOf("\\") >= 0 || text.indexOf("|") >= 0 || text.indexOf("\0") >= 0) return "";
  if (text === "." || text === "..") return "";
  return text;
}
export function chainTicketAndEffortFromPath(path) {
  const raw = path === null || path === void 0 ? "" : String(path);
  if (!raw) return { ticketKey: "", effortId: "" };
  const text = raw.replace(/\\/g, "/");
  const base = text.slice(text.lastIndexOf("/") + 1);
  let ticketKey = "";
  const direct = /^(\d{1,10})(?:[-._][^/]*)?\.(?:md|markdown)$/i.exec(base);
  if (direct) ticketKey = chainTicketKey(direct[1]);
  else {
    const inDir = /(?:^|\/)(?:issues?|tickets?)\/(\d{1,10})(?:[-._/]|$)/i.exec(text);
    ticketKey = inDir ? chainTicketKey(inDir[1]) : "";
  }
  let effortId = "";
  const scratchHit = /(?:^|\/)\.scratch\/([^\/.][^\/]*)\/(?:issues\/|map\.md$|spec\.md$)/.exec(text);
  if (scratchHit) {
    const cand = scratchHit[1];
    if (cand !== "issues" && cand !== "tickets") effortId = chainEffortId(cand);
  }
  return { ticketKey, effortId };
}
export function chainEffortIdFromPath(path) {
  return chainTicketAndEffortFromPath(path).effortId;
}
export function looksLikeTicketFilePath(path) {
  return chainTicketKeyFromPath(path) !== "";
}
export function chainEntryKey(input) {
  const rootHash = input ? input.rootHash : "";
  const backend = chainBackendId(input ? input.backend : "");
  const effortId = chainEffortId(input && "effortId" in input ? input.effortId : "");
  const ticketKey = chainTicketKey(input ? input.ticketKey : "");
  const shardId = input ? input.shardId : "";
  if (!isFingerprintLike(rootHash) || !backend || !ticketKey || !isFingerprintLike(shardId)) return "";
  if (typeof effortId !== "string") return "";
  return "r:" + rootHash + "|b:" + backend + "|e:" + effortId + "|t:" + ticketKey + "|s:" + shardId;
}
const DECK_WRITE_ACTIONS = {
  deck_issue_create: "create",
  deck_issue_patch: "edit",
  deck_map_plan_create: "plan",
  deck_map_link: "link",
  deck_issue_report: "report"
};
const DECK_READ_TOOLS = ["deck_context", "deck_issue_get", "deck_map_snapshot"];
const FILE_WRITE_TOOLS = ["write", "edit", "multiedit", "multi_edit", "apply_patch", "create_file", "notebookedit", "notebook_edit", "str_replace_editor"];
const FILE_READ_TOOLS = ["read", "readfile", "read_file", "grep", "glob", "search", "ls", "list", "listfiles", "list_files"];
const VERB_ACTIONS = {
  create: "create",
  comment: "comment",
  note: "comment",
  edit: "edit",
  update: "edit",
  rename: "edit",
  close: "state",
  reopen: "state",
  link: "link",
  plan: "plan"
};
const WRITE_TIER = "write-confirmed";
const TICKET_ARG_FIELDS = ["issue", "number", "ticket", "key", "id", "child", "parent"];
function ticketFromArgs(args) {
  if (!args || typeof args !== "object") return "";
  const bag = args;
  for (const field of TICKET_ARG_FIELDS) {
    if (!Object.prototype.hasOwnProperty.call(bag, field)) continue;
    const t = chainTicketKey(bag[field]);
    if (t) return t;
  }
  return "";
}
const EFFORT_ARG_FIELDS = ["effortId", "effort", "effort_id"];
function effortFromArgs(args) {
  if (!args || typeof args !== "object") return "";
  const bag = args;
  for (const field of EFFORT_ARG_FIELDS) {
    if (!Object.prototype.hasOwnProperty.call(bag, field)) continue;
    const e = chainEffortId(bag[field]);
    if (e) return e;
  }
  return "";
}
function no(reason) {
  return { record: false, action: "", ticketKey: "", effortId: "", reason };
}
function yes(action, ticketKey, effortId) {
  return { record: true, action: CHAIN_ACTIONS.indexOf(action) >= 0 ? action : "other-write", ticketKey, effortId: chainEffortId(effortId), reason: "chain.record" };
}
export function chainVerdictOf(input) {
  if (!input || typeof input !== "object") return no("chain.unknown-source");
  const source = String(input.source || "");
  if (source !== "tool-args" && source !== "cli" && source !== "markdown-file") return no("chain.unknown-source");
  const tool = String(input.tool || "");
  const toolKey = tool.toLowerCase();
  const tier = String(input.tier == null ? "" : input.tier);
  const reason = String(input.reason || "");
  if (DECK_READ_TOOLS.indexOf(tool) >= 0 || DECK_READ_TOOLS.indexOf(toolKey) >= 0) return no("chain.read-excluded");
  if (FILE_READ_TOOLS.indexOf(toolKey) >= 0 && source === "markdown-file") return no("chain.read-excluded");
  if (reason === "tool.deck-read" || reason === "tool.local-read" || reason === "cmd.gh-read" || reason === "cmd.glab-read" || reason === "cmd.gh-help") {
    return no("chain.read-excluded");
  }
  if (reason === "not-succeeded") return no("chain.not-succeeded");
  if (reason === "shape.not-a-result") return no("chain.not-a-result");
  const parsedPath = chainTicketAndEffortFromPath(input.path);
  const fromFile = parsedPath.ticketKey;
  const effortFromPath = parsedPath.effortId;
  const isFileWriter = FILE_WRITE_TOOLS.indexOf(toolKey) >= 0;
  const isDeckWriter = Object.prototype.hasOwnProperty.call(DECK_WRITE_ACTIONS, tool);
  let wrote = false;
  let action = "";
  if (source === "markdown-file") {
    if (!isFileWriter && !isDeckWriter) return no("chain.read-excluded");
    wrote = true;
    action = "file-write";
  } else if (source === "tool-args") {
    if (!isDeckWriter && tier !== WRITE_TIER) return no("chain.read-excluded");
    wrote = true;
    action = isDeckWriter ? DECK_WRITE_ACTIONS[tool] : "other-write";
  } else {
    if (reason === "cmd.file-write" && fromFile) {
      wrote = true;
      action = "file-write";
    } else if (tier === WRITE_TIER) {
      wrote = true;
      const verb = String(input.verb || "").toLowerCase().replace(/^--?/, "");
      action = Object.prototype.hasOwnProperty.call(VERB_ACTIONS, verb) ? VERB_ACTIONS[verb] : "other-write";
    } else {
      return no("chain.read-excluded");
    }
  }
  if (!wrote) return no("chain.read-excluded");
  const ticketKey = chainTicketKey(input.ticketKey) || ticketFromArgs(input.args) || fromFile;
  if (!ticketKey) return no("chain.no-ticket");
  const effortId = chainEffortId(input.effortId) || effortFromArgs(input.args) || effortFromPath;
  return yes(action, ticketKey, effortId);
}
export function createChainState() {
  return { shards: {} };
}
export function chainRecord(state, input) {
  const shardId = chainSessionShardId(input ? input.sessionId : "");
  if (!shardId) return { state, recorded: false, shardId: "", reason: "chain.bad-shard" };
  if (!isFingerprintLike(input ? input.rootHash : "")) return { state, recorded: false, shardId, reason: "chain.bad-root" };
  const backend = chainBackendId(input ? input.backend : "");
  if (!backend) return { state, recorded: false, shardId, reason: "chain.bad-backend" };
  const ticketKey = chainTicketKey(input ? input.ticketKey : "");
  if (!ticketKey) return { state, recorded: false, shardId, reason: "chain.no-ticket" };
  const effortId = chainEffortId(input ? input.effortId : "");
  const rawAction = String(input && input.action ? input.action : "");
  const action = CHAIN_ACTIONS.indexOf(rawAction) >= 0 ? rawAction : "other-write";
  const at = typeof input.at === "number" && isFinite(input.at) ? input.at : 0;
  const src = state && state.shards ? state.shards : {};
  const key = chainEntryKey({ rootHash: input.rootHash, backend, effortId, ticketKey, shardId });
  if (!key) return { state, recorded: false, shardId, reason: "chain.bad-root" };
  const before = src[shardId];
  const entries = mergeEntries(before ? before.entries : [], { ticketKey, effortId, at, action });
  const shard = {
    shardId,
    sessionId: String(input.sessionId == null ? "" : input.sessionId).trim(),
    rootHash: String(input.rootHash),
    backend,
    entries
  };
  const shards = {};
  for (const k of Object.keys(src)) shards[k] = src[k];
  shards[shardId] = shard;
  return { state: { shards }, recorded: true, shardId, reason: "chain.record" };
}
export function mergeEntries(entries, incoming) {
  const out = [];
  const seen = {};
  const push = (e) => {
    const key = chainTicketKey(e ? e.ticketKey : "");
    const effort = chainEffortId(e ? e.effortId : "");
    const id = effort + "\0" + key;
    if (!key || seen[id]) return;
    seen[id] = true;
    out.push({ ticketKey: key, effortId: effort, at: typeof e.at === "number" && isFinite(e.at) ? e.at : 0, action: CHAIN_ACTIONS.indexOf(String(e.action)) >= 0 ? String(e.action) : "other-write" });
  };
  if (incoming) push(incoming);
  const list = Array.isArray(entries) ? entries : [];
  for (const e of list) push(e);
  out.sort((a, b) => b.at - a.at);
  return out.slice(0, CHAIN_SESSION_CAP);
}
export function chainEntriesOf(state, sessionId) {
  const shardId = chainSessionShardId(sessionId);
  const shard = shardId && state && state.shards ? state.shards[shardId] : null;
  if (!shard || !Array.isArray(shard.entries)) return [];
  return shard.entries.map((e) => ({ ticketKey: e.ticketKey, effortId: chainEffortId(e.effortId), at: e.at, action: e.action }));
}
export const CHAIN_DISK_VERSION = 2;
export function chainPrivacyViolations(value) {
  const out = [];
  const walk = (v, at) => {
    if (typeof v === "string") {
      if (/[A-Za-z]:[\\/]|(^|[\s"'])~[\\/]|\.{1,2}[\\/]|\\\\[^\\]/.test(v)) out.push(at + "\uFF1A\u50CF\u8DEF\u5F84\u539F\u6587");
      else if (/\s/.test(v) || /(^|\s)(gh|glab|git|pwsh|bash|node|Set-Content|Out-File)(\s|$)/.test(v)) out.push(at + "\uFF1A\u50CF\u547D\u4EE4\u539F\u6587");
      return;
    }
    if (Array.isArray(v)) {
      v.forEach((x, i) => walk(x, at + "[" + i + "]"));
      return;
    }
    if (v && typeof v === "object") {
      for (const k of Object.keys(v)) walk(v[k], at + "." + k);
    }
  };
  walk(value, "$");
  return out;
}
export function chainToDisk(state, opts) {
  const shards = [];
  const src = state && state.shards ? state.shards : {};
  for (const k of Object.keys(src)) {
    const shard = src[k];
    if (!shard || !isFingerprintLike(shard.shardId) || !isFingerprintLike(shard.rootHash) || !chainBackendId(shard.backend)) continue;
    const entries = [];
    for (const e of Array.isArray(shard.entries) ? shard.entries : []) {
      const key = chainTicketKey(e ? e.ticketKey : "");
      if (!key) continue;
      const effort = chainEffortId(e.effortId);
      const action = String(e.action || "");
      entries.push([key, effort, typeof e.at === "number" && isFinite(e.at) ? Math.floor(e.at) : 0, CHAIN_ACTIONS.indexOf(action) >= 0 ? action : "other-write"]);
    }
    if (entries.length === 0) continue;
    shards.push({ s: shard.shardId, r: shard.rootHash, b: shard.backend, e: entries.slice(0, CHAIN_SESSION_CAP) });
  }
  return { v: CHAIN_DISK_VERSION, at: opts && typeof opts.at === "number" && isFinite(opts.at) ? Math.floor(opts.at) : 0, shards };
}
export function chainFromDisk(payload) {
  const state = createChainState();
  const raw = payload;
  if (!raw || typeof raw !== "object" || !Array.isArray(raw.shards)) return { state, shards: 0, entries: 0, dropped: 0, reason: "chain.disk-shape" };
  const v = Number(raw.v);
  if (v !== 1 && v !== CHAIN_DISK_VERSION) return { state, shards: 0, entries: 0, dropped: 0, reason: "chain.disk-version" };
  let kept = 0;
  let entries = 0;
  let dropped = 0;
  for (const s of raw.shards) {
    if (!s || typeof s !== "object" || !isFingerprintLike(s.s) || !isFingerprintLike(s.r) || !chainBackendId(s.b) || !Array.isArray(s.e)) {
      dropped += 1;
      continue;
    }
    let acc = [];
    for (const row of s.e) {
      const arr = Array.isArray(row) ? row : [];
      if (v === 1) {
        const key = chainTicketKey(arr[0]);
        const action = String(arr[2] || "");
        if (!key || CHAIN_ACTIONS.indexOf(action) < 0) {
          dropped += 1;
          continue;
        }
        const at = typeof arr[1] === "number" && isFinite(arr[1]) ? Math.floor(arr[1]) : 0;
        acc = mergeEntries(acc, { ticketKey: key, effortId: "", at, action });
      } else {
        const key = chainTicketKey(arr[0]);
        const effort = chainEffortId(arr[1]);
        const action = String(arr[3] || "");
        if (!key || CHAIN_ACTIONS.indexOf(action) < 0) {
          dropped += 1;
          continue;
        }
        if (typeof arr[1] !== "string" || arr[1] !== "" && effort !== arr[1]) {
          dropped += 1;
          continue;
        }
        const at = typeof arr[2] === "number" && isFinite(arr[2]) ? Math.floor(arr[2]) : 0;
        acc = mergeEntries(acc, { ticketKey: key, effortId: effort, at, action });
      }
    }
    if (acc.length === 0) {
      dropped += 1;
      continue;
    }
    state.shards[String(s.s)] = { shardId: String(s.s), sessionId: "", rootHash: String(s.r), backend: chainBackendId(s.b), entries: acc };
    kept += 1;
    entries += acc.length;
  }
  return { state, shards: kept, entries, dropped, reason: kept > 0 ? "chain.disk-ok" : "chain.disk-empty" };
}
