// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/create-write.ts
const NEVER_STARTED_RE = /['"]?glab['"]? (?:command not found|is not recognized as an internal or external command)|command not found: glab|which: no glab|glab not found in path|cannot find glab|spawn (?:[^\s]*[\\/])?glab(?:\.exe|\.cmd|\.bat)? (?:enoent|eacces|eperm)|platform unavailable|exec unavailable/i;
const ENDPOINT_ABSENT_RE = /\b40[45]\b|method not allowed|404 not found/i;
function firstLine(text) {
  const s = String(text || "").replace(/\s+/g, " ").trim();
  return s.length > 200 ? s.slice(0, 200) + "\uFF08\u5DF2\u622A\u65AD\uFF09" : s;
}
function issueOf(stdout) {
  const t = String(stdout || "").trim();
  if (!t) return null;
  try {
    const parsed = JSON.parse(t);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return null;
    const bag = parsed;
    const iid = bag.iid;
    if (iid === void 0 || iid === null || iid === "") return null;
    return bag;
  } catch {
    return null;
  }
}
export function classifyCreateWriteAttempt(res) {
  const code = res && typeof res.code === "number" && isFinite(res.code) ? res.code : 1;
  const stdout = res && typeof res.stdout === "string" ? res.stdout : "";
  const stderr = res && typeof res.stderr === "string" ? res.stderr : "";
  const issue = issueOf(stdout);
  if (code === 0 && issue) {
    return { verdict: "created", issue, reason: "\u56DE\u5305\u91CC\u5E26\u7740\u8FD9\u5F20\u7968\u7684 iid\uFF0C\u7968\u786E\u5B9E\u5EFA\u51FA\u6765\u4E86" };
  }
  const text = firstLine((stdout ? stdout + " " : "") + stderr);
  if (code === 127 || NEVER_STARTED_RE.test(text)) {
    return { verdict: "never-sent", issue: null, reason: "\u8FD9\u53F0\u673A\u5668\u4E0A glab \u6CA1\u80FD\u8DD1\u8D77\u6765\uFF08" + text + "\uFF09\uFF0C\u8FD9\u4E00\u6B21\u8BF7\u6C42\u4E00\u4E2A\u5B57\u8282\u90FD\u6CA1\u53D1\u51FA\u53BB" };
  }
  if (ENDPOINT_ABSENT_RE.test(text)) {
    return { verdict: "endpoint-absent", issue: null, reason: "\u8FDC\u7AEF\u56DE\u7684\u662F\u300C\u8FD9\u4E2A\u7AEF\u70B9\u4E0D\u5B58\u5728\u300D\uFF08" + text + "\uFF09\uFF0C\u8FD9\u4E00\u6B21\u786E\u5B9A\u6CA1\u6709\u5EFA\u51FA\u7968" };
  }
  const head = code === 0 ? "\u56DE\u5305\u4E0D\u662F\u4E00\u4E2A\u5E26 iid \u7684\u7968\u9762\uFF08" : "\u8FD9\u4E00\u6B21\u6CA1\u6709\u62FF\u5230\u786E\u5B9A\u7684\u56DE\u7B54\uFF08";
  return { verdict: "maybe-written", issue: null, reason: head + text + "\uFF09\uFF0C\u7968\u6709\u53EF\u80FD\u5DF2\u7ECF\u5EFA\u51FA\u6765\u4E86" };
}
export function decideCreateWriteRetry(verdict, writeAttemptsMade) {
  const made = typeof writeAttemptsMade === "number" && isFinite(writeAttemptsMade) ? writeAttemptsMade : 0;
  if (verdict === "never-sent") {
    if (made <= 1) return { retry: true, reason: "\u4E0A\u4E00\u6B21\u8BF7\u6C42\u786E\u5B9A\u4E00\u4E2A\u5B57\u8282\u90FD\u6CA1\u53D1\u51FA\u53BB\uFF08glab \u6CA1\u8DD1\u8D77\u6765\uFF09\uFF0C\u8FDC\u7AEF\u4E0D\u53EF\u80FD\u6709\u8FD9\u5F20\u7968\uFF0C\u518D\u53D1\u4E00\u6B21\u662F\u540C\u4E00\u6761\u8BF7\u6C42\u7684\u7B2C\u4E00\u6B21\u771F\u6B63\u51FA\u7AD9" };
    return { retry: false, reason: "\u8FD9\u4E2A\u8C03\u7528\u5DF2\u7ECF\u91CD\u53D1\u8FC7\u4E00\u6B21\u4E86\uFF0C\u4E0D\u8BBA\u518D\u8BD5\u51E0\u6B21\u90FD\u4E0D\u4F1A\u6709\u7B2C\u4E09\u6B21" };
  }
  if (verdict === "maybe-written") return { retry: false, reason: "\u8FD9\u4E00\u6B21\u5199\u6709\u53EF\u80FD\u5DF2\u7ECF\u843D\u5230\u8FDC\u7AEF\u4E86\uFF1A\u518D\u53D1\u4E00\u6B21\u5C31\u53EF\u80FD\u591A\u51FA\u4E00\u5F20\u91CD\u590D\u7684\u7968\uFF0C\u6240\u4EE5\u4E0D\u53D1" };
  if (verdict === "endpoint-absent") return { retry: false, reason: "\u8FDC\u7AEF\u660E\u786E\u8BF4\u8FD9\u4E2A\u7AEF\u70B9\u4E0D\u5B58\u5728\uFF1A\u540C\u4E00\u6761\u8BF7\u6C42\u518D\u53D1\u4E00\u6B21\u4E5F\u662F\u540C\u6837\u7684\u56DE\u7B54\uFF0C\u628A\u8FD9\u4E2A\u4FE1\u53F7\u539F\u6837\u4EA4\u7ED9\u8C03\u7528\u65B9" };
  return { retry: false, reason: "\u7968\u5DF2\u7ECF\u5EFA\u51FA\u6765\u4E86\uFF0C\u6CA1\u6709\u8981\u91CD\u53D1\u7684\u4E1C\u897F" };
}
