// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/delta.ts
export const PATCH_MAX_ROWS = 6;
function sortedKeys(o) {
  const out = [];
  if (o && typeof o === "object") for (const k of Object.keys(o)) out.push(k);
  out.sort();
  return out;
}
export function planDelta(baseline, incoming, opts) {
  const before = baseline && typeof baseline === "object" ? baseline : {};
  const delta = incoming && typeof incoming === "object" ? incoming : {};
  const full = !!(opts && opts.full);
  const merged = {};
  if (full) for (const k of Object.keys(delta)) merged[k] = delta[k];
  else {
    for (const k of Object.keys(before)) merged[k] = before[k];
    for (const k of Object.keys(delta)) merged[k] = delta[k];
  }
  const changed = [];
  const added = [];
  const removed = [];
  if (!baseline || typeof baseline !== "object") {
    return { mode: "rebuild", reason: "no-baseline", merged, changed, added: sortedKeys(merged), removed };
  }
  const bk = sortedKeys(before);
  const mk = sortedKeys(merged);
  for (const k of bk) if (!(k in merged)) removed.push(k);
  for (const k of mk) {
    if (!(k in before)) added.push(k);
    else if (before[k] !== merged[k]) changed.push(k);
  }
  if (added.length > 0 || removed.length > 0) {
    return { mode: "rebuild", reason: "ticket-set-changed", merged, changed, added, removed };
  }
  if (changed.length > 0) {
    return { mode: "patch", reason: "rows-changed", merged, changed, added, removed };
  }
  return { mode: "nothing", reason: "nothing-changed", merged, changed, added, removed };
}
export function watermarkAfter(input) {
  const prev = Number(input && input.previousMs) || 0;
  const started = Number(input && input.scanStartedMs) || 0;
  const outcome = input && input.outcome || "failed";
  if (outcome === "merged" || outcome === "not-need") {
    return {
      watermarkMs: started > 0 ? started : prev,
      advanced: started > 0,
      toPending: false,
      reason: outcome === "merged" ? "merged" : "no-change"
    };
  }
  const reason = outcome === "deferred" ? "deferred-kept-watermark" : outcome === "dropped" ? "dropped-kept-watermark" : "failed-kept-watermark";
  return { watermarkMs: prev, advanced: false, toPending: true, reason };
}
export function admitResult(currentGeneration, startedGeneration) {
  const cur = Number(currentGeneration) || 0;
  const started = Number(startedGeneration) || 0;
  if (started < cur) return { accept: false, generation: cur, reason: "stale-result" };
  return { accept: true, generation: started + 1, reason: started > cur ? "ahead" : "fresh" };
}
export function derivedAfter(mode) {
  if (mode === "rebuild") {
    return { progressAction: "recompute", countsAction: "recompute", markPartial: false, reason: "rebuild-has-whole-repo-counts" };
  }
  return { progressAction: "recompute", countsAction: "keep-old-and-mark-pending", markPartial: true, reason: "patch-keeps-whole-repo-counts" };
}
export function rowKey(row) {
  if (!row || typeof row !== "object") return "";
  const n = row.number;
  if (n !== void 0 && n !== null && String(n) !== "") return String(n);
  const k = row.key;
  if (k !== void 0 && k !== null && String(k) !== "") return String(k);
  return "";
}
function fnv1a(s) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = (h >>> 0) * 16777619;
    h = h >>> 0;
  }
  return ("00000000" + h.toString(16)).slice(-8);
}
export function nextVersion(prevVersion, seeds) {
  const prev = String(prevVersion || "");
  const list = (seeds || []).map((s) => String(s)).sort();
  const v = "p" + fnv1a(list.join("|") + "#" + prev);
  return v === prev ? v + "-1" : v;
}
export function mergeRows(rows, patched, prevVersion) {
  const src = Array.isArray(rows) ? rows : [];
  const byKey = {};
  for (const p of Array.isArray(patched) ? patched : []) {
    const k = rowKey(p);
    if (k) byKey[k] = p;
  }
  const out = [];
  const replaced = [];
  const seen = {};
  for (const row of src) {
    const k = rowKey(row);
    if (k && Object.prototype.hasOwnProperty.call(byKey, k)) {
      out.push(byKey[k]);
      replaced.push(k);
      seen[k] = true;
    } else {
      out.push(row);
    }
  }
  const missing = [];
  for (const k of Object.keys(byKey).sort()) if (!seen[k]) missing.push(k);
  const seeds = [];
  for (const k of replaced.sort()) seeds.push(k + "=" + String(byKey[k].state || "") + "|" + String(byKey[k].updatedAt || ""));
  return { rows: out, replaced, missing, version: nextVersion(prevVersion, seeds) };
}
export const DELTA_STRUCTURE_VERSION = 1;
export function checkStructure(stamped) {
  const v = stamped && typeof stamped === "object" ? stamped.structureVersion : void 0;
  if (typeof v !== "number" || !isFinite(v)) return { action: "rebuild", reason: "legacy-structure" };
  if (v === DELTA_STRUCTURE_VERSION) return { action: "use", reason: "current" };
  if (v > DELTA_STRUCTURE_VERSION) return { action: "rebuild", reason: "future-structure" };
  return { action: "rebuild", reason: "legacy-structure" };
}
