// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/idempotency.ts
export const IDEMPOTENCY_MARKER_PREFIX = "<!-- DSH-IDEMPOTENCY-KEY:";
export const IDEMPOTENCY_KEY_MAX_LENGTH = 200;
const ALLOWED_KEY_RE = /^[A-Za-z0-9._:/-]+$/;
export function checkIdempotencyKey(raw) {
  const key = raw === null || raw === void 0 ? "" : String(raw).trim();
  if (!key) return { ok: false, key: "", reason: "\u5E42\u7B49\u952E\u662F\u7A7A\u7684" };
  if (key.length > IDEMPOTENCY_KEY_MAX_LENGTH) {
    return { ok: false, key: "", reason: "\u5E42\u7B49\u952E\u6709 " + key.length + " \u4E2A\u5B57\u7B26\uFF0C\u8D85\u8FC7\u4E0A\u9650 " + IDEMPOTENCY_KEY_MAX_LENGTH + "\uFF0C\u8BF7\u6362\u4E00\u4E2A\u77ED\u4E00\u70B9\u7684\u952E" };
  }
  if (!ALLOWED_KEY_RE.test(key)) {
    return { ok: false, key: "", reason: "\u5E42\u7B49\u952E\u91CC\u53EA\u80FD\u6709\u5B57\u6BCD\u3001\u6570\u5B57\u3001\u70B9\u3001\u4E0B\u5212\u7EBF\u3001\u8FDE\u5B57\u7B26\u3001\u5192\u53F7\u4E0E\u659C\u6760\uFF08\u952E\u4F1A\u539F\u6837\u5199\u8FDB\u7968\u9762\uFF0C\u6362\u884C\u4E0E\u6CE8\u91CA\u6536\u5C3E\u7B26\u4F1A\u628A\u6B63\u6587\u5199\u574F\uFF09" };
  }
  return { ok: true, key, reason: "" };
}
export function anchorLineFor(key) {
  return IDEMPOTENCY_MARKER_PREFIX + " " + key + " -->\n";
}
export function idempotencyKeyOf(text) {
  const body = String(text === null || text === void 0 ? "" : text);
  if (!body || body.indexOf(IDEMPOTENCY_MARKER_PREFIX) < 0) return "";
  const lines = body.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].replace(/^[ \t]+/, "").replace(/[ \t]+$/, "");
    if (trimmed.indexOf(IDEMPOTENCY_MARKER_PREFIX) !== 0) continue;
    if (!/-->$/.test(trimmed)) continue;
    const key = trimmed.slice(IDEMPOTENCY_MARKER_PREFIX.length, trimmed.length - 3).trim();
    if (key) return key;
  }
  return "";
}
export function anchorMiss(reason) {
  return { status: "miss", reason: reason || "\u6309\u951A\u627E\u904D\u4E86\uFF0C\u6CA1\u6709\u627E\u5230\u5199\u8FC7\u8FD9\u4E2A\u951A\u7684\u7968" };
}
export function anchorUnsupported(reason) {
  return { status: "unsupported", reason };
}
export function anchorMismatch(reason) {
  return { status: "mismatch", reason };
}
export function anchorHit(key) {
  return { status: "hit", reason: "\u8FD9\u5F20\u7968\u7684\u7968\u9762\u4E0A\u5199\u7740\u540C\u4E00\u4E2A\u951A\uFF0C\u590D\u7528\u5B83\uFF08\u4E0D\u518D\u65B0\u5EFA\uFF09", key: String(key) };
}
export function matchAnchor(candidates, refId, key) {
  const list = Array.isArray(candidates) ? candidates : [];
  const wanted = String(key === null || key === void 0 ? "" : key).trim();
  if (!wanted) return anchorUnsupported("\u6CA1\u6709\u7ED9\u951A\uFF0C\u65E0\u4ECE\u56DE\u67E5");
  if (list.length === 0) return anchorMiss();
  const mismatches = [];
  for (let i = 0; i < list.length; i++) {
    const c = list[i];
    if (!c || typeof c !== "object") {
      mismatches.push("\u7B2C " + (i + 1) + " \u4E2A\u5019\u9009\u4E0D\u662F\u4E00\u5F20\u7968\uFF0C\u5FFD\u7565");
      continue;
    }
    const found = idempotencyKeyOf(c.body);
    if (!found) {
      mismatches.push("\u5019\u9009 " + String(c.key) + " \u7684\u7968\u9762\u4E0A\u6CA1\u6709\u951A\u90A3\u4E00\u884C");
      continue;
    }
    if (found !== wanted) {
      mismatches.push("\u5019\u9009 " + String(c.key) + " \u7684\u7968\u9762\u4E0A\u5199\u7684\u662F\u53E6\u4E00\u4E2A\u951A\uFF08" + found + "\uFF09");
      continue;
    }
    if (refId !== void 0 && c.refId !== void 0 && String(c.refId) !== String(refId)) {
      mismatches.push("\u5019\u9009 " + String(c.key) + " \u5728\u53E6\u4E00\u4E2A\u4ED3\u5E93\uFF08" + String(c.refId) + "\uFF09\u91CC");
      continue;
    }
    if (c.state === "closed") {
      mismatches.push("\u5019\u9009 " + String(c.key) + " \u5DF2\u7ECF\u5173\u95ED\u4E86\uFF0C\u4E0D\u7B97\u547D\u4E2D\uFF08\u8BE5\u5EFA\u4E00\u5F20\u65B0\u7684\uFF09");
      continue;
    }
    return anchorHit(String(c.key));
  }
  return anchorMismatch(mismatches.join("\uFF1B"));
}
export function isAnchorHit(m) {
  return !!(m && m.status === "hit");
}
export function isAnchorUnsupported(m) {
  return !!(m && m.status === "unsupported");
}
export function describeAnchorFailure(m) {
  const why = m && typeof m.reason === "string" && m.reason ? m.reason : "\u56DE\u67E5\u6CA1\u6709\u505A\u6210";
  return "\u8FD9\u6B21\u5E26\u951A\u521B\u5EFA\u6CA1\u80FD\u505A\u6210\u56DE\u67E5\uFF0C\u6240\u4EE5\u6CA1\u6709\u5EFA\u7968\uFF1A" + why + "\u3002\u8FD9\u4E0D\u662F\u300C\u5DF2\u7ECF\u5EFA\u8FC7\u300D\u7684\u610F\u601D \u2014\u2014 \u8BF7\u6362\u7528\u4E0D\u5E26\u951A\u7684\u521B\u5EFA\uFF0C\u6216\u8005\u5148\u628A\u951A\u56DE\u67E5\u8FD9\u4E00\u6761\u4FEE\u597D\u518D\u6765\u3002";
}
