// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/page-budget.ts
function nonNegativeInt(v) {
  const n = typeof v === "number" && isFinite(v) ? Math.floor(v) : 0;
  return n > 0 ? n : 0;
}
export function issuesPagesFor(measuredPages) {
  const p = nonNegativeInt(measuredPages);
  return p > 0 ? p : 1;
}
export function worstPagesFor(measuredPages, maxPages) {
  const measured = issuesPagesFor(measuredPages);
  const upper = nonNegativeInt(maxPages);
  return measured > upper ? measured : upper;
}
export function rebuildCost(issuePages, prices) {
  const pages = issuesPagesFor(issuePages);
  const prPages = nonNegativeInt(prices.prPageCount);
  return {
    issuePages: pages,
    requests: pages * nonNegativeInt(prices.listPageRequests) + prPages * nonNegativeInt(prices.prPageRequests) + nonNegativeInt(prices.countRequests),
    points: pages * nonNegativeInt(prices.listPagePoints) + prPages * nonNegativeInt(prices.prPagePoints) + nonNegativeInt(prices.countPoints)
  };
}
export function worstCaseRebuildCost(measuredPages, maxPages, prices) {
  return rebuildCost(worstPagesFor(measuredPages, maxPages), prices);
}
export function pageCountReport(measuredPages, maxPages) {
  const measured = issuesPagesFor(measuredPages);
  const upper = nonNegativeInt(maxPages);
  const worst = worstPagesFor(measured, upper);
  return {
    measuredPages: measured,
    upperBoundPages: upper,
    worstPages: worst,
    beyondUpperBound: upper > 0 && measured > upper
  };
}
