// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/policy.ts
export const POLICY_SOURCE = "refresh-core/src/policy.ts";
export const REQUEST_KINDS = [
  "quota-read",
  "probe",
  "patch",
  "rebuild",
  "reconcile",
  "preflight",
  "chain",
  "naming",
  "detail",
  "write",
  "tool-batch"
];
export const FAILURE_DEFER_AT = 3;
export const REASONS = {
  "quota-read-free": "\u8BFB\u670D\u52A1\u7AEF\u5269\u4F59\u989D\u5EA6\uFF1A\u8FD9\u4E2A\u63A5\u53E3\u4E0D\u6263\u914D\u989D\uFF0C\u6C38\u8FDC\u653E\u884C",
  "user-action-always": "\u4EBA\u5728\u754C\u9762\u4E0A\u4EB2\u624B\u505A\u7684\u52A8\u4F5C\uFF1A\u6C38\u4E0D\u964D\u6863\uFF0C\u7EA2\u6863\u4E5F\u7167\u505A",
  "user-action-rate-limited": "\u649E\u4E0A\u9650\u6D41\u65F6\u4EBA\u4EB2\u624B\u505A\u7684\u52A8\u4F5C\uFF1A\u7167\u6837\u505A\uFF0C\u4F46\u754C\u9762\u8981\u8BF4\u6E05\u662F\u989D\u5EA6\u88AB\u522B\u4EBA\u7528\u6389\u4E86",
  "rate-limited": "\u649E\u4E0A\u9650\u6D41\uFF08\u542B\u4E8C\u7EA7\u9650\u6D41\u7684 Retry-After\uFF09\uFF1A\u8FD9\u4E00\u8F6E\u505C\uFF0C\u7B49\u95F8\u7684\u6863\u4F4D\u6062\u590D",
  "failure-backoff": "\u8FDE\u7EED\u5931\u8D25\u5230\u4E86\u9000\u907F\u95E8\u69DB\uFF1A\u62C9\u5F00\u95F4\u9694\u518D\u8BD5\uFF0C\u6210\u529F\u4E00\u6B21\u7ACB\u523B\u5F52\u96F6",
  "background-fits": "\u540E\u53F0\u6863\uFF1A\u989D\u5EA6\u591F\uFF0C\u6309\u8282\u62CD\u8DD1",
  "background-inactive": "\u4E0D\u5728\u6D3B\u8DC3\u96C6\u5408\u91CC\uFF1A\u540E\u53F0\u6863\u4E00\u6B21\u90FD\u4E0D\u53D1\uFF0C\u5207\u56DE\u6765\u65F6\u6309\u751F\u547D\u5468\u671F\u90A3\u4E00\u6B21\u53D6",
  "background-tier-yellow": "\u540E\u53F0\u6863\u8FDB\u4E86\u9EC4\u6863\uFF1A\u540E\u53F0\u5237\u65B0\u5168\u505C\uFF08\u5148\u727A\u7272\u7684\u4ECE\u6765\u4E0D\u662F\u4EBA\u7684\u52A8\u4F5C\uFF09",
  "background-tier-red": "\u540E\u53F0\u6863\u8FDB\u4E86\u7EA2\u6863\uFF1A\u81EA\u52A8\u5237\u65B0\u5168\u505C\uFF0C\u53EA\u7559\u4EBA\u7684\u52A8\u4F5C",
  "reserve-kept-for-writes": "\u8BFB\u7684\u989D\u5EA6\u5DF2\u7528\u5B8C\uFF0C\u53EA\u5269\u7ED9\u5199\u7559\u7684\u4FDD\u5E95\uFF1A\u8BFB\u8BA9\u8DEF\uFF0C\u5199\u4FDD\u4F4F",
  "lifecycle-fits": "\u5207\u8FDB\u5DE5\u4F5C\u533A\u90A3\u4E00\u6B21\uFF1A\u989D\u5EA6\u591F\uFF0C\u7167\u5E38\u53D6\u6570\uFF08\u5148\u4ECE\u7F13\u5B58\u94FA\u6EE1\uFF0C\u518D\u63A2\u6D4B\u8865\u9F50\uFF09",
  "lifecycle-cache-only": "\u5207\u8FDB\u5DE5\u4F5C\u533A\u90A3\u4E00\u6B21\uFF1A\u989D\u5EA6\u4E0D\u591F\uFF0C\u964D\u7EA7\u4E3A\u53EA\u51FA\u7F13\u5B58\u52A0\u53EA\u63A2\u6D4B\u4E0D\u91CD\u5EFA",
  "ai-tool-within-caps": "AI \u5DE5\u5177\u8C03\u7528\uFF1A\u5355\u6B21\u4E0E\u6BCF\u5C0F\u65F6\u7684\u786C\u9876\u90FD\u8FD8\u591F",
  "ai-tool-over-call-cap": "AI \u5DE5\u5177\u8C03\u7528\u8D85\u4E86\u5355\u6B21\u786C\u9876\uFF1A\u62D2\u7EDD\uFF0C\u5E76\u8BF4\u660E\u7528\u4E86\u591A\u5C11\u3001\u9876\u5728\u54EA",
  "ai-tool-over-hour-cap": "AI \u5DE5\u5177\u8FD9\u4E00\u5C0F\u65F6\u8D85\u4E86\u786C\u9876\uFF1A\u62D2\u7EDD\uFF0C\u5E76\u8BF4\u660E\u7528\u4E86\u591A\u5C11\u3001\u9876\u5728\u54EA",
  "ai-tool-below-remaining": "\u5269\u4F59\u989D\u5EA6\u5DF2\u5230\u4FDD\u5E95\u7EBF\uFF1A\u5148\u62D2 AI \u5DE5\u5177\uFF0C\u7EDD\u4E0D\u6324\u6389\u63D2\u4EF6\u5237\u65B0\u4E0E\u4EBA\u7684\u52A8\u4F5C"
};
function verdict(v, reason) {
  return { verdict: v, reason };
}
export const DEGRADE_ORDER = ["probe-sensitivity", "reconcile-frequency", "local-write-latency"];
export function degradePlanFor(tier, limits) {
  if (tier === "green") {
    return {
      probeIntervalMs: limits.probeIntervalMs,
      reconcileIntervalMs: limits.reconcileIntervalMs,
      rebuildMinGapMs: 0,
      localWriteImmediate: true,
      sacrificed: "none"
    };
  }
  if (tier === "yellow") {
    return {
      probeIntervalMs: limits.probeIntervalYellowMs,
      reconcileIntervalMs: null,
      rebuildMinGapMs: limits.rebuildMinIntervalYellowMs,
      localWriteImmediate: true,
      sacrificed: "probe-sensitivity"
    };
  }
  return {
    probeIntervalMs: null,
    reconcileIntervalMs: null,
    rebuildMinGapMs: 0,
    localWriteImmediate: true,
    sacrificed: "probe-sensitivity"
  };
}
const READ_KINDS = ["probe", "patch", "rebuild", "reconcile", "preflight", "chain", "naming", "detail"];
function isReadKind(kind) {
  return READ_KINDS.indexOf(kind) >= 0;
}
export function decide(input) {
  const { category, kind, tier, quota, workspace } = input;
  if (kind === "quota-read") return verdict("allow", "quota-read-free");
  if (category === "user-action") {
    return verdict("allow", workspace.rateLimited ? "user-action-rate-limited" : "user-action-always");
  }
  if (workspace.rateLimited) {
    return category === "lifecycle" ? verdict("degrade", "rate-limited") : verdict("defer", "rate-limited");
  }
  const failures = workspace.failuresSinceSuccess || 0;
  if (failures >= FAILURE_DEFER_AT) {
    return category === "lifecycle" ? verdict("degrade", "lifecycle-cache-only") : verdict("defer", "failure-backoff");
  }
  if (isReadKind(kind) && quota.remaining <= quota.reserve) {
    return category === "lifecycle" ? verdict("degrade", "lifecycle-cache-only") : verdict("defer", "reserve-kept-for-writes");
  }
  if (tier === "red") {
    if (category === "lifecycle") return verdict("degrade", "lifecycle-cache-only");
    if (category === "ai-tool") return verdict("defer", "ai-tool-below-remaining");
    return verdict("defer", "background-tier-red");
  }
  if (category === "background") {
    if (kind === "rebuild" || kind === "reconcile") {
      return tier === "yellow" ? verdict("defer", "background-tier-yellow") : verdict("allow", "background-fits");
    }
    const watched = kind === "probe" || kind === "patch";
    if (watched && !workspace.active) return verdict("defer", "background-inactive");
    return verdict("allow", "background-fits");
  }
  if (category === "lifecycle") {
    return tier === "yellow" ? verdict("degrade", "lifecycle-cache-only") : verdict("allow", "lifecycle-fits");
  }
  return verdict("allow", "ai-tool-within-caps");
}
export function aiToolAdmission(call, hour, quota, limits) {
  const points = call.points;
  const requests = call.requests;
  const base = { points, requests };
  if (!(points <= limits.aiToolMaxPointsPerCall) || !(requests <= limits.aiToolMaxRequestsPerCall)) {
    return { admitted: false, reason: "ai-tool-over-call-cap", ...base };
  }
  if (!(hour.points + points <= limits.aiToolMaxPointsPerHour) || !(hour.requests + requests <= limits.aiToolMaxRequestsPerHour)) {
    return { admitted: false, reason: "ai-tool-over-hour-cap", ...base };
  }
  if (quota.remaining <= quota.reserve) {
    return { admitted: false, reason: "ai-tool-below-remaining", ...base };
  }
  return { admitted: true, reason: "ai-tool-within-caps", ...base };
}
export function nextAttemptDelayMs(failuresSinceSuccess, limits) {
  const n = Math.max(0, Math.floor(failuresSinceSuccess || 0));
  if (n <= 0) return 0;
  const seq = limits.failureBackoffMs;
  if (!seq || seq.length === 0) return 0;
  return seq[Math.min(n - 1, seq.length - 1)];
}
