// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/tool-cost.ts
export const TOOL_COST_PRICES = Object.freeze({
  /** 固定开销：选后端那一次探测 + 收尾的计数校验。 */
  fixedPoints: 3,
  fixedRequests: 2,
  /** 建一张票。 */
  ticketPoints: 4,
  ticketRequests: 2,
  /** 一条边。 */
  edgePoints: 2,
  edgeRequests: 1,
  /** 改一张票。 */
  patchPoints: 2,
  patchRequests: 1,
  /** 读回一张票。 */
  readPoints: 3,
  readRequests: 1
});
function count(v) {
  const n = typeof v === "number" && isFinite(v) ? Math.floor(v) : 0;
  return n > 0 ? n : 0;
}
export function estimateToolCost(input, limits) {
  const p = TOOL_COST_PRICES;
  const tickets = count(input.tickets);
  const edges = count(input.edges);
  const patches = count(input.patches);
  const reads = count(input.reads);
  const points = p.fixedPoints + tickets * p.ticketPoints + edges * p.edgePoints + patches * p.patchPoints + reads * p.readPoints;
  const requests = p.fixedRequests + tickets * p.ticketRequests + edges * p.edgeRequests + patches * p.patchRequests + reads * p.readRequests;
  const overPoints = points > limits.maxPointsPerCall;
  const overRequests = requests > limits.maxRequestsPerCall;
  const overCallCap = overPoints && overRequests ? "both" : overPoints ? "points" : overRequests ? "requests" : "";
  const withinCallCap = overCallCap === "";
  const cap = count(limits.maxChildTicketsPerCall) || 1;
  const shards = Math.max(1, Math.ceil(tickets / cap));
  const perShard = Math.max(1, Math.ceil(tickets / shards));
  const usedPoints = count(limits.usedPointsThisHour);
  const usedRequests = count(limits.usedRequestsThisHour);
  const withinHourCap = usedPoints + points <= limits.maxPointsPerHour && usedRequests + requests <= limits.maxRequestsPerHour;
  return {
    tool: String(input.tool || ""),
    tickets,
    edges,
    patches,
    reads,
    points,
    requests,
    withinCallCap: withinCallCap && withinHourCap,
    overCallCap: withinCallCap ? withinHourCap ? "" : "hour" : overCallCap,
    withinHourCap,
    shards,
    perShard,
    text: estimateText(input.tool, points, requests, withinCallCap && withinHourCap, overCallCap, withinHourCap, shards, perShard, tickets)
  };
}
function estimateText(tool, points, requests, ok, over, hourOk, shards, perShard, tickets) {
  const head = "\u8FD9\u6B21 " + tool + " \u9884\u8BA1\u82B1 " + points + " \u70B9\u3001" + requests + " \u6761\u51FA\u7AD9\u8BF7\u6C42";
  if (!ok) {
    const which = over === "points" ? "\u70B9\u6570\u8D85\u4E86\u5355\u6B21\u786C\u9876" : over === "requests" ? "\u51FA\u7AD9\u8BF7\u6C42\u6761\u6570\u8D85\u4E86\u5355\u6B21\u786C\u9876" : over === "hour" ? "\u52A0\u4E0A\u672C\u5C0F\u65F6\u5DF2\u7528\uFF0C\u8D85\u4E86\u6BCF\u5C0F\u65F6\u786C\u9876" : "\u540C\u65F6\u8D85\u4E86\u70B9\u6570\u4E0E\u8BF7\u6C42\u6570\u4E24\u6761\u5355\u6B21\u786C\u9876";
    const tail = tickets > 0 ? "\u3002\u5EFA\u8BAE\u5206 " + shards + " \u6B21\u8C03\u7528\uFF0C\u6BCF\u7247\u4E0D\u8D85\u8FC7 " + perShard + " \u5F20\u7968" : "\u3002\u8BF7\u628A\u8FD9\u4E00\u7B14\u62C6\u5C0F\u4E4B\u540E\u518D\u8C03";
    return head + "\uFF0C" + which + tail + "\u3002";
  }
  if (tickets > 0 && shards > 1) return head + "\uFF0C\u5728\u786C\u9876\u4E4B\u5185\uFF1B\u4E0D\u8FC7\u8FD9\u6B21\u8981\u5EFA " + tickets + " \u5F20\u7968\uFF0C\u5EFA\u8BAE\u5206 " + shards + " \u7247\u3001\u6BCF\u7247 " + perShard + " \u5F20\u3002";
  if (!hourOk) return head + "\uFF0C\u5355\u6B21\u6CA1\u8D85\u9876\uFF0C\u4F46\u672C\u5C0F\u65F6 AI \u5DE5\u5177\u5DF2\u7ECF\u5FEB\u7528\u6EE1\u4E86\uFF08\u6BCF\u5C0F\u65F6\u786C\u9876\u89C1 deck_context \u7684\u8FD4\u56DE\u503C\uFF09\u3002";
  return head + "\uFF0C\u5728\u786C\u9876\u4E4B\u5185\u3002";
}
export function toolCostInputFrom(tool, args) {
  const a = args || {};
  const list = (v) => Array.isArray(v) ? v.length : 0;
  const one = (v) => v === void 0 || v === null || v === "" ? 0 : 1;
  const base = { tool: String(tool || "") };
  switch (tool) {
    case "deck_context":
      return Object.assign(base, { reads: 1 });
    case "deck_issue_get":
      return Object.assign(base, { reads: 1 });
    case "deck_map_snapshot":
      return Object.assign(base, { reads: 1 });
    case "deck_issue_list":
      return Object.assign(base, { reads: 1 });
    case "deck_issue_create":
      return Object.assign(base, { tickets: 1, edges: one(a.parentKey) + list(a.blockedBy) });
    case "deck_map_plan_create":
      return Object.assign(base, { tickets: list(a.children) + (a.title ? 1 : 0), edges: list(a.edges) + list(a.children) });
    case "deck_map_link":
      return Object.assign(base, { edges: list(a.edges) + (a.parentKey ? 1 : 0), reads: 1 });
    case "deck_issue_patch":
      return Object.assign(base, { patches: 1, reads: 1, edges: one(a.parentKey) });
    case "deck_issue_report":
      return Object.assign(base, { reads: 1 });
    default:
      return Object.assign(base, {
        tickets: count(a.tickets),
        edges: count(a.edges),
        patches: count(a.patches),
        reads: count(a.reads)
      });
  }
}
