// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/write-detect.ts
export const WRITE_DETECT_SOURCE = "refresh-core/src/write-detect.ts";
export const TIERS = ["write-confirmed", "probe-now", "default-tick"];
export const DETECT_REASONS = {
  "shape.not-a-result": "\u8FD9\u4E0D\u662F\u4E00\u6B21\u8C03\u7528\u7684\u7ED3\u679C\uFF08\u8C03\u7528\u521A\u5F00\u59CB\uFF0C\u6216\u8BA4\u4E0D\u51FA\u7684\u5F62\u6001\uFF09\uFF1A\u6309\u515C\u5E95\u8282\u62CD\u8D70\uFF0C\u4E0D\u636E\u5B83\u89E6\u53D1\u53D6\u6570",
  "not-succeeded": "\u8FD9\u6B21\u8C03\u7528\u6CA1\u6709\u6210\u529F\uFF1A\u5931\u8D25\u7684\u547D\u4EE4\u4EC0\u4E48\u90FD\u6CA1\u6539\uFF0C\u4E0D\u89E6\u53D1\u53D6\u6570",
  "tool.deck-write": "\u6211\u4EEC\u81EA\u5DF1\u7684\u5199\u5DE5\u5177\u88AB\u8C03\u7528\u4E86\uFF1A\u53C2\u6570\u91CC\u76F4\u63A5\u5E26\u7968\u53F7\uFF0C\u7ACB\u523B\u8865\u90A3\u4E00\u884C",
  "tool.deck-write-unknown-ticket": "\u6211\u4EEC\u81EA\u5DF1\u7684\u5199\u5DE5\u5177\u6210\u529F\u4E86\uFF0C\u4F46\u53C2\u6570\u91CC\u6CA1\u6709\u53EF\u7528\u7684\u7968\u53F7\uFF1A\u7ACB\u523B\u63A2\u4E00\u6B21\uFF0C\u53D8\u4E86\u624D\u8865\u884C",
  "tool.deck-read": "\u6211\u4EEC\u81EA\u5DF1\u7684\u8BFB\u5DE5\u5177\uFF1A\u53EA\u770B\u4E0D\u5199\uFF0C\u4E0D\u89E6\u53D1\u53D6\u6570",
  "tool.web-fetch": "\u8054\u7F51\u6293\u53D6\u5DE5\u5177\uFF08WebFetch \u8FD9\u4E00\u7C7B\uFF09\uFF1A\u53EF\u80FD\u5E26\u7740\u5199\u610F\u56FE\uFF0C\u7ACB\u523B\u63A2\u4E00\u6B21",
  "tool.local-read": "\u5DF2\u77E5\u53EA\u8BFB\u7684\u672C\u5730\u5DE5\u5177\uFF1A\u4E0D\u89E6\u53D1\u53D6\u6570",
  "tool.unknown": "\u8BA4\u4E0D\u51FA\u7684\u5DE5\u5177\uFF1A\u9ED8\u8BA4\u7ACB\u523B\u63A2\u4E00\u6B21\uFF08\u5B81\u53EF\u591A\u63A2\uFF0C\u4E0D\u8BB8\u6F0F\uFF09",
  "cmd.unparsed": "\u547D\u4EE4\u5DE5\u5177\u6210\u529F\u4E86\u5374\u62FF\u4E0D\u5230\u547D\u4EE4\u884C\uFF1A\u8BA4\u4E0D\u51FA\u5B83\u505A\u4E86\u4EC0\u4E48\uFF0C\u7ACB\u523B\u63A2\u4E00\u6B21",
  "cmd.cli-write": "gh / glab \u7684\u5199\u5B50\u547D\u4EE4\uFF1A\u7ACB\u523B\u8865\u90A3\u4E00\u884C",
  "cmd.cli-write-unknown-ticket": "gh / glab \u7684\u5199\u5B50\u547D\u4EE4\u6210\u529F\u4E86\uFF0C\u4F46\u547D\u4EE4\u884C\u91CC\u6CA1\u6709\u7968\u53F7\uFF1A\u7ACB\u523B\u63A2\u4E00\u6B21\uFF0C\u53D8\u4E86\u624D\u8865\u884C",
  "cmd.cli-read": "gh / glab \u7684\u8BFB\u5B50\u547D\u4EE4\uFF1A\u53EA\u770B\u4E0D\u5199\uFF0C\u4E0D\u89E6\u53D1\u53D6\u6570",
  "cmd.cli-help": "gh \u7684\u6C42\u52A9\u6216\u7248\u672C\u8F93\u51FA\uFF1A\u4EC0\u4E48\u90FD\u6CA1\u505A\uFF0C\u4E0D\u89E6\u53D1\u53D6\u6570",
  "cmd.api-write": "gh api \u5E26\u5199\u65B9\u6CD5\uFF08-X POST/PATCH/PUT/DELETE\u3001-f\u3001--input\uFF09\uFF1A\u7ACB\u523B\u8865\u90A3\u4E00\u884C",
  "cmd.api-graphql-mutation": "gh api graphql \u91CC\u51FA\u73B0 mutation\uFF1A\u90A3\u662F\u5199\uFF0C\u4F46\u7968\u53F7\u8BA4\u4E0D\u51FA\uFF0C\u7ACB\u523B\u63A2\u4E00\u6B21",
  "cmd.api-graphql-unknown": "gh api graphql \u91CC\u6CA1\u6709 mutation \u5B57\u6837\uFF1A\u8BA4\u4E0D\u51FA\u662F\u8BFB\u662F\u5199\uFF0C\u7ACB\u523B\u63A2\u4E00\u6B21\uFF08\u4E0D\u4E22\u5F03\uFF09",
  "cmd.api-read": "gh api \u662F GET \u8BFB\uFF1A\u4E0D\u89E6\u53D1\u53D6\u6570",
  "cmd.cli-unknown": "gh / glab \u7684\u5B50\u547D\u4EE4\u8BA4\u4E0D\u51FA\u5728\u8BFB\u8FD8\u662F\u5199\uFF1A\u7ACB\u523B\u63A2\u4E00\u6B21",
  "cmd.git-push": "git push\uFF1A\u628A\u672C\u5730\u63D0\u4EA4\u9001\u51FA\u53BB\u4E86\uFF0C\u8FDC\u7AEF\u53EF\u80FD\u521A\u53D8\uFF0C\u7ACB\u523B\u63A2\u4E00\u6B21",
  "cmd.git-local": "git \u7684\u672C\u5730\u5B50\u547D\u4EE4\uFF08\u4E0D\u662F push\uFF09\uFF1A\u4E0D\u89E6\u53D1\u53D6\u6570",
  "cmd.script": "\u811A\u672C\u6216\u89E3\u91CA\u5668\uFF08node / python / npm run \u8FD9\u4E00\u7C7B\uFF09\uFF1A\u91CC\u9762\u5E72\u4E86\u4EC0\u4E48\u770B\u4E0D\u51FA\u6765\uFF0C\u7ACB\u523B\u63A2\u4E00\u6B21",
  "cmd.remote-client": "\u8FDC\u7AEF\u5BA2\u6237\u7AEF\uFF08curl / wget / ssh \u8FD9\u4E00\u7C7B\uFF09\uFF1A\u53EF\u80FD\u76F4\u63A5\u6253\u4E86\u63A5\u53E3\uFF0C\u7ACB\u523B\u63A2\u4E00\u6B21",
  "cmd.file-write": "\u8FD9\u4E00\u884C\u91CC\u6709\u91CD\u5B9A\u5411\u6216\u5199\u6587\u4EF6\uFF08> / >> / Out-File / Set-Content\uFF09\uFF1A\u53EF\u80FD\u6539\u5230\u4E86\u7968\u6587\u4EF6\uFF0C\u7ACB\u523B\u63A2\u4E00\u6B21",
  "cmd.local-read": "\u5DF2\u77E5\u53EA\u8BFB\u7684\u672C\u5730\u547D\u4EE4\uFF1A\u4E0D\u89E6\u53D1\u53D6\u6570",
  "cmd.unknown": "\u8BA4\u4E0D\u51FA\u7684\u547D\u4EE4\uFF1A\u9ED8\u8BA4\u7ACB\u523B\u63A2\u4E00\u6B21\uFF08\u5B81\u53EF\u591A\u63A2\uFF0C\u4E0D\u8BB8\u6F0F\uFF09"
};
function LIST(s) {
  return s.split(",");
}
const RESULT_SHAPES = LIST("tools/result,tool/result,tool/ptc-dispatch,tool/code-dispatch");
const START_SHAPES = LIST("tool/call,tool/ptc-dispatch-start,tool/code-dispatch-start");
export function isResultShape(shape) {
  return RESULT_SHAPES.indexOf(String(shape)) >= 0;
}
const DECK_WRITE_TOOLS = LIST("deck_issue_create,deck_issue_patch,deck_map_plan_create,deck_map_link,deck_issue_report");
const DECK_READ_TOOLS = LIST("deck_context,deck_issue_get,deck_map_snapshot");
const TICKET_ARG_FIELDS = LIST("issue,number,ticket,key,id,child,parent");
const WEB_FETCH_TOOLS = LIST("webfetch,web_fetch,fetch,webfetchtool,fetchurl");
const SHELL_TOOLS = LIST("pwsh,powershell,bash,sh,zsh,cmd,shell");
const LOCAL_READ_TOOLS = LIST("read,readfile,glob,grep,search,ls,list,listfiles,askuserquestion,ask_user_question,todowrite,todo_write,websearch,web_search,skill,vision_describe,vision_ocr,vision_crop");
const SEGMENT_SPLIT_RE = /&&|\|\||[;|\n\r]|(?<![&>])&(?![&>])/g;
const LOCAL_READ_HEADS = LIST("ls,dir,pwd,cd,cat,type,get-content,get-childitem,head,tail,wc,grep,rg,select-string,find,test-path,which,get-command,echo,write-output,write-host,date,get-date,whoami,tree,stat,du,df,printenv,get-item,resolve-path");
const SCRIPT_HEADS = LIST("node,deno,bun,npx,npm,pnpm,yarn,python,python3,py,ruby,perl,php,make,just,cargo,go,dotnet,java,mvn,gradle,docker,kubectl,terraform,ansible,pwsh,powershell,bash,sh,zsh,cmd");
const REMOTE_HEADS = LIST("curl,wget,irm,iwr,invoke-restmethod,invoke-webrequest,http,https,httpie,ssh,scp,sftp,rsync,nc,telnet");
const FILE_WRITE_RE = /(^|[\s;|&])(>>?|out-file|set-content|add-content|tee)([\s;|&]|$)/i;
const CLI_SCOPES = {
  issue: { create: "w", close: "w", reopen: "w", comment: "w", edit: "w", delete: "w", lock: "w", unlock: "w", transfer: "w", pin: "w", unpin: "w", develop: "w", list: "r", view: "r", status: "r" },
  pr: { create: "w", close: "w", reopen: "w", merge: "w", comment: "w", edit: "w", review: "w", ready: "w", lock: "w", unlock: "w", revert: "w", list: "r", view: "r", status: "r", diff: "r", checks: "r", checkout: "x" },
  mr: { create: "w", close: "w", reopen: "w", merge: "w", comment: "w", note: "w", edit: "w", update: "w", approve: "w", revoke: "w", delete: "w", list: "r", view: "r", diff: "r", checkout: "x" },
  label: { create: "w", edit: "w", delete: "w", clone: "w", list: "r" },
  milestone: { create: "w", edit: "w", delete: "w", close: "w", reopen: "w", list: "r", view: "r" },
  release: { create: "w", edit: "w", delete: "w", upload: "w", download: "r", list: "r", view: "r" },
  repo: { create: "w", edit: "w", delete: "w", rename: "w", archive: "w", unarchive: "w", fork: "w", sync: "w", list: "r", view: "r" },
  gist: { create: "w", edit: "w", delete: "w", list: "r", view: "r" },
  project: { create: "w", edit: "w", delete: "w", close: "w", copy: "w", link: "w", unlink: "w", "item-add": "w", "item-edit": "w", "item-archive": "w", "field-create": "w", "field-delete": "w", list: "r", view: "r" },
  run: { cancel: "w", rerun: "w", delete: "w", list: "r", view: "r", watch: "r" },
  workflow: { enable: "w", disable: "w", list: "r", view: "r" },
  secret: { set: "w", delete: "w", list: "r" },
  variable: { set: "w", delete: "w", list: "r" },
  "ssh-key": { add: "w", delete: "w", list: "r" },
  config: { set: "w", unset: "w", get: "r", list: "r" },
  alias: { set: "w", delete: "w", list: "r" },
  auth: { login: "w", logout: "w", switch: "w", refresh: "w", "setup-git": "w", status: "r", token: "r" },
  extension: { install: "w", remove: "w", upgrade: "w", list: "r" }
};
const CLI_HELP_WORDS = LIST("help,version,--help,-h,--version,completion");
const OPTION_TAKES_VALUE = LIST("-b,--body,-t,--title,-l,--label,--add-label,--remove-label,-m,--message,-F,--body-file,-R,--repo,-q,--jq,--template,-f,--field,--raw-field,--input,-X,--method,-H,--header,-a,--assignee,--add-assignee,--remove-assignee,-r,--reason,-c,--comment,--state,--milestone,--project,--type,-e,--editor,-d,--description,-p,--path,-n,--name,--color,--due-date,--query,--search,--limit,--sort,--order,--json,--interval,--timeout,--closes,--match-head-commit,-C,--git-dir,--work-tree,--namespace,--exec-path");
function unquote(tok) {
  const s = String(tok || "");
  const q = s.charAt(0);
  return s.length >= 2 && (q === '"' || q === "'" || q === "`") && s.charAt(s.length - 1) === q ? s.slice(1, -1) : s;
}
function tokenize(segment) {
  const out = [];
  let cur = "";
  let quote = "";
  for (let i = 0; i < segment.length; i++) {
    const c = segment.charAt(i);
    if (quote) {
      if (c === quote) quote = "";
      else cur += c;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") {
      quote = c;
      continue;
    }
    if (c === " " || c === "	") {
      if (cur) {
        out.push(cur);
        cur = "";
      }
      continue;
    }
    if (c === "(" || c === "{" || c === ")" || c === "}") {
      if (cur) {
        out.push(cur);
        cur = "";
      }
      continue;
    }
    cur += c;
  }
  return cur ? out.concat(cur) : out;
}
function headWord(tok) {
  let s = unquote(tok || "");
  const cut = Math.max(s.lastIndexOf("/"), s.lastIndexOf("\\"));
  if (cut >= 0) s = s.slice(cut + 1);
  s = s.toLowerCase();
  for (const ext of [".exe", ".cmd", ".bat", ".ps1", ".com"]) if (s.length > ext.length && s.endsWith(ext)) {
    s = s.slice(0, -ext.length);
    break;
  }
  return s;
}
function positionalsOf(tokens) {
  const out = [];
  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i];
    if (t.charAt(0) === "-") {
      const eq = t.indexOf("=");
      if (eq < 0 && OPTION_TAKES_VALUE.indexOf(t) >= 0) i += 1;
      continue;
    }
    if (OPTION_TAKES_VALUE.indexOf(t) >= 0) {
      i += 1;
      continue;
    }
    out.push(t);
  }
  return out;
}
function ticketLike(tok) {
  const s = unquote(String(tok || "")).trim();
  if (/^#?\d{1,10}$/.test(s)) return s.replace(/^#/, "");
  const url = /^https?:\/\/[^\s]+\/(?:issues|pulls|pull|merge_requests)\/(\d{1,10})(?:[/?#].*)?$/i.exec(s);
  return url ? url[1] : null;
}
function ticketFromCommand(tokens) {
  const pos = positionalsOf(tokens);
  return pos.length > 0 ? ticketLike(pos[0]) : null;
}
function readSegment(segment) {
  const tokens = tokenize(segment);
  if (tokens.length === 0) return { tier: "default-tick", ticket: null, reason: "cmd.local-read" };
  if (FILE_WRITE_RE.test(" " + segment + " ")) return { tier: "probe-now", ticket: null, reason: "cmd.file-write" };
  const head = headWord(tokens[0]);
  const rest = tokens.slice(1);
  if (head === "gh" || head === "glab") return readCli(head, rest);
  if (head === "git") {
    const pos = positionalsOf(rest);
    if (pos.length > 0 && unquote(pos[0]).toLowerCase() === "push") return { tier: "probe-now", ticket: null, reason: "cmd.git-push" };
    return { tier: "default-tick", ticket: null, reason: "cmd.git-local" };
  }
  if (SCRIPT_HEADS.indexOf(head) >= 0) return { tier: "probe-now", ticket: null, reason: "cmd.script" };
  if (REMOTE_HEADS.indexOf(head) >= 0) return { tier: "probe-now", ticket: null, reason: "cmd.remote-client" };
  if (LOCAL_READ_HEADS.indexOf(head) >= 0) return { tier: "default-tick", ticket: null, reason: "cmd.local-read" };
  return { tier: "probe-now", ticket: null, reason: "cmd.unknown" };
}
function readCli(head, rest) {
  const scopeRaw = rest.length > 0 ? unquote(rest[0]).toLowerCase() : "";
  if (scopeRaw === "api") return readApi(rest.slice(1));
  if (CLI_HELP_WORDS.indexOf(scopeRaw) >= 0 || rest.some((t) => t === "--help" || t === "-h")) {
    return { tier: "default-tick", ticket: null, reason: "cmd.cli-help" };
  }
  const verbRaw = rest.length > 1 ? unquote(rest[1]).toLowerCase() : "";
  const scope = CLI_SCOPES[scopeRaw];
  if (!scope || !verbRaw) return { tier: "probe-now", ticket: null, reason: "cmd.cli-unknown" };
  const kind = scope[verbRaw.replace(/^--?/, "")];
  if (kind === "r") return { tier: "default-tick", ticket: null, reason: "cmd.cli-read" };
  if (kind !== "w") return { tier: "probe-now", ticket: null, reason: "cmd.cli-unknown" };
  const ticket = ticketFromCommand(rest.slice(2));
  return { tier: "write-confirmed", ticket, reason: ticket ? "cmd.cli-write" : "cmd.cli-write-unknown-ticket" };
}
function readApi(rest) {
  if (rest.some((t) => unquote(t).toLowerCase() === "graphql")) {
    const text = rest.join(" ").toLowerCase();
    if (/(^|[^a-z])mutation([^a-z]|$)/.test(text)) return { tier: "write-confirmed", ticket: null, reason: "cmd.api-graphql-mutation" };
    return { tier: "probe-now", ticket: null, reason: "cmd.api-graphql-unknown" };
  }
  const method = methodOf(rest);
  const pos = positionalsOf(rest);
  if (pos.length === 0) return { tier: "probe-now", ticket: null, reason: "cmd.cli-unknown" };
  const hit = /(?:issues|pulls|merge_requests)\/(\d{1,10})(?:[/?#]|$)/i.exec(unquote(pos[0]));
  const ticket = hit ? hit[1] : null;
  if (method === "POST" || method === "PATCH" || method === "PUT" || method === "DELETE") {
    return { tier: "write-confirmed", ticket, reason: "cmd.api-write" };
  }
  if (method === "") return { tier: "probe-now", ticket: null, reason: "cmd.cli-unknown" };
  return { tier: "default-tick", ticket: null, reason: "cmd.api-read" };
}
function methodOf(rest) {
  for (let i = 0; i < rest.length; i++) {
    const t = unquote(rest[i]);
    const eq = /^--method=(.*)$/.exec(t) || /^-X(.*)$/.exec(t);
    if (eq && eq[1]) return eq[1].toUpperCase();
    if (t === "--method" || t === "-X") return rest[i + 1] ? unquote(rest[i + 1]).toUpperCase() : "GET";
  }
  if (rest.some((t) => ["-f", "--field", "-F", "--raw-field", "--input"].indexOf(t) >= 0)) return "POST";
  return "GET";
}
export function detectWrite(input) {
  const shape = String(input && input.shape || "");
  if (START_SHAPES.indexOf(shape) >= 0 || !isResultShape(shape)) return { tier: "default-tick", ticket: null, reason: "shape.not-a-result" };
  if (!input || input.succeeded !== true) return { tier: "default-tick", ticket: null, reason: "not-succeeded" };
  const tool = String(input.tool || "");
  const toolKey = tool.toLowerCase();
  if (DECK_WRITE_TOOLS.indexOf(tool) >= 0 || DECK_WRITE_TOOLS.indexOf(toolKey) >= 0) {
    const ticket = ticketFromArgs(input.args);
    return { tier: "write-confirmed", ticket, reason: ticket ? "tool.deck-write" : "tool.deck-write-unknown-ticket" };
  }
  if (DECK_READ_TOOLS.indexOf(tool) >= 0 || DECK_READ_TOOLS.indexOf(toolKey) >= 0) return { tier: "default-tick", ticket: null, reason: "tool.deck-read" };
  if (WEB_FETCH_TOOLS.indexOf(toolKey) >= 0) return { tier: "probe-now", ticket: null, reason: "tool.web-fetch" };
  if (LOCAL_READ_TOOLS.indexOf(toolKey) >= 0) return { tier: "default-tick", ticket: null, reason: "tool.local-read" };
  const command = input.command == null ? "" : String(input.command);
  if (SHELL_TOOLS.indexOf(toolKey) >= 0) {
    if (!command.trim()) return { tier: "probe-now", ticket: null, reason: "cmd.unparsed" };
    return readCommand(command);
  }
  if (command.trim()) return readCommand(command);
  return { tier: "probe-now", ticket: null, reason: "tool.unknown" };
}
export function readCommand(command) {
  const segments = String(command || "").split(SEGMENT_SPLIT_RE);
  let best = null;
  let ticket = null;
  for (const seg of segments) {
    if (!seg || !seg.trim()) continue;
    const v = readSegment(seg);
    if (v.ticket && !ticket) ticket = v.ticket;
    if (!best || TIERS.indexOf(v.tier) < TIERS.indexOf(best.tier)) best = v;
  }
  if (!best) return { tier: "default-tick", ticket: null, reason: "cmd.local-read" };
  return { tier: best.tier, ticket, reason: best.reason };
}
function ticketFromArgs(args) {
  if (!args || typeof args !== "object") return null;
  const bag = args;
  for (const field of TICKET_ARG_FIELDS) {
    if (!Object.prototype.hasOwnProperty.call(bag, field)) continue;
    const v = bag[field];
    if (typeof v === "number" && isFinite(v)) return String(Math.floor(v));
    const t = typeof v === "string" ? ticketLike(v) : null;
    if (t) return t;
  }
  return null;
}
export function actionFor(result, limits) {
  const mergeWindowMs = limits && isFinite(limits.mergeWindowMs) ? limits.mergeWindowMs : 0;
  const probeIntervalMs = limits && isFinite(limits.probeIntervalMs) ? limits.probeIntervalMs : 0;
  const tier = result && result.tier ? result.tier : "default-tick";
  if (tier === "write-confirmed" && result.ticket) return { action: "patch-now", ticket: result.ticket, waitMs: mergeWindowMs, mergeWindowMs };
  if (tier === "write-confirmed" || tier === "probe-now") return { action: "probe-now", ticket: null, waitMs: mergeWindowMs, mergeWindowMs };
  return { action: "wait-tick", ticket: null, waitMs: probeIntervalMs, mergeWindowMs };
}
