/**
 * label-color-core/build.mjs —— 配色核心的编译脚本
 *
 * 只转译不打包：用仓库现成的 esbuild 把 label-color-core/src/ 下每个 TS 文件
 * 一对一转成 src/shared/label-color/ 下的同名 JS；另跑 tsc --noEmit 只做类型检查。
 * 生成的 JS 提交到 git；改了 TS 没重新生成，tests/verify-label-color-freshness.js 会变红。
 *
 * 与 update-core/build.mjs 有三处差别，都是这份形态的要求，不是随手改的：
 * 1. 本文件导出 transpileUnit、runTypeCheck、buildAll 三个函数。update-core 的脚本
 *    只导出了 transpileUnit，转译入口是文件内的私有函数，外面调不到；这里要让
 *    scripts/build.mjs 在一条命令里带上它，所以三个都导出。
 * 2. buildAll 先判断源码目录与 tsconfig 在不在。npm 发布包里没有这棵源码树
 *    （package/package.json 的 files 白名单里没有它），在那种子树里跑构建时，
 *    这里要跳过转译并打印一行提示，而不是把整个构建打断。
 * 3. 转译结果要把 esbuild 收在文件末尾的 `export { ... };` 改写成声明前的行首 export
 *    （见下面 inlineExportDeclarations 的说明）。
 *
 * 用法：node label-color-core/build.mjs（在仓库根目录；日常更常用 node scripts/build.mjs，
 * 那条命令会把本脚本带进去一起跑）。
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import * as esbuild from 'esbuild'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC_DIR = resolve(ROOT, 'label-color-core/src')
const OUT_DIR = resolve(ROOT, 'src/shared/label-color')
const TSCONFIG = resolve(ROOT, 'label-color-core/tsconfig.json')

const UNITS = [
  { ts: 'ports.ts', js: 'ports.js' },
  { ts: 'colors.ts', js: 'colors.js' },
  { ts: 'prompt.ts', js: 'prompt.js' },
]

function headerFor(tsName) {
  return `// AUTO-GENERATED by node label-color-core/build.mjs — DO NOT EDIT. Source: label-color-core/src/${tsName}\n`
}

/**
 * 把 esbuild 收在文件末尾的导出块改写成声明前的行首 export。
 *
 * 为什么必须改写：三个产物里有两个（colors.js 与 prompt.js）要被 scripts/build.mjs
 * 拼进客户端闭包，拼法是去掉每行行首的 `export `（见 scripts/build.mjs 的 extractModuleBlock）。
 * esbuild 的转译结果不是 `export function x() {}` 这种行首形式，而是把声明照常写在前面、
 * 末尾收一个 `export { x, y };` 块。那种块去掉行首 export 之后只剩一个 `{ x, y };` 语句块：
 * 名字虽然还在（函数声明本来就会被提升），但形态与仓库里其它拼进闭包的共享文件完全不一样，
 * 读代码的人会看不懂，以后的构建步骤也可能把它当成别的东西。所以这里统一改回行首形式。
 *
 * 只认「名字能在同一份文件里找到 function / const / let / var / class 声明」这一种情形；
 * 找不到就抛错，绝不静默产出一个少了一个导出的产物。
 */
function inlineExportDeclarations(code) {
  const clause = /(^|\n)export \{\n([\s\S]*?)\n\};\n?$/.exec(code)
  if (!clause) {
    if (/(^|\n)export \{/.test(code)) {
      throw new Error('[label-color-core] 转译结果里出现了没有预料到的导出块写法，拒绝改写：\n' + code.slice(-300))
    }
    return code
  }
  const names = clause[2]
    .split(',')
    .map((s) => s.trim())
    .filter((s) => s !== '')
  let body = code.slice(0, clause.index) + (clause[1] === '\n' ? '\n' : '')
  for (const name of names) {
    if (!/^[A-Za-z_$][\w$]*$/.test(name)) {
      throw new Error(`[label-color-core] 导出块里有改不了名的条目「${name}」：本脚本只支持原样导出，不支持 as 改名`)
    }
    const decl = new RegExp('^(?:async )?function ' + name + '\\b|^(?:const|let|var) ' + name + '\\b|^class ' + name + '\\b', 'm')
    const hit = decl.exec(body)
    if (!hit) {
      throw new Error(`[label-color-core] 导出块里的名字「${name}」在这份文件里找不到声明，拒绝生成少一个导出的产物`)
    }
    body = body.slice(0, hit.index) + 'export ' + body.slice(hit.index)
  }
  return body
}

/** 与新鲜度门禁同一口径：转译加包头，换行归一，末尾恰好一个换行。 */
export function transpileUnit(tsName) {
  const tsPath = resolve(SRC_DIR, tsName)
  const source = readFileSync(tsPath, 'utf8')
  const out = esbuild.transformSync(source, {
    loader: 'ts',
    format: 'esm',
    // 保守目标：Node 宿主与浏览器闭包两边都跑得动。
    target: 'es2020',
  })
  const normalized = out.code.replace(/\r\n/g, '\n').replace(/\s+$/, '') + '\n'
  return headerFor(tsName) + inlineExportDeclarations(normalized)
}

/** 跑一次 `tsc --noEmit`。typescript 没装（没跑过 pnpm install）时明确报错，不静默跳过。 */
export function runTypeCheck() {
  const require = createRequire(resolve(ROOT, 'package.json'))
  let tscBin
  try {
    tscBin = resolve(dirname(require.resolve('typescript/package.json')), 'bin/tsc')
  } catch {
    throw new Error('[label-color-core] 找不到 typescript：请先运行 pnpm install（devDependencies 含 typescript）')
  }
  const r = spawnSync(process.execPath, [tscBin, '-p', TSCONFIG], { encoding: 'utf8' })
  if (r.status !== 0) {
    throw new Error(`[label-color-core] tsc --noEmit 未通过：\n${r.stdout || ''}${r.stderr || ''}`)
  }
  console.log('[label-color-core] tsc --noEmit 通过')
}

/**
 * 类型检查加转译，全部产物写进 src/shared/label-color/。
 * 源码目录或 tsconfig 不在时就跳过：发布包与 package/ 子树里本来就没有这棵源码树，
 * 那种情况下构建立刻中断会挡住别的步骤，而这里要的只是「这一步没法做，跳过它」。
 * 返回 { skipped, files }，调用方（scripts/build.mjs）可以据此打印自己的日志。
 */
export function buildAll() {
  if (!existsSync(SRC_DIR) || !existsSync(TSCONFIG)) {
    console.log('[label-color-core] 没找到源码目录或 tsconfig（' + SRC_DIR + ' / ' + TSCONFIG + '），本次跳过配色核心的转译与类型检查。发布包与 package/ 子树里本来就没有这棵源码树，这是预期情况；要重新生成产物请在仓库根目录跑 node scripts/build.mjs。')
    return { skipped: true, files: [] }
  }
  runTypeCheck()
  mkdirSync(OUT_DIR, { recursive: true })
  const files = []
  for (const u of UNITS) {
    const text = transpileUnit(u.ts)
    const outPath = resolve(OUT_DIR, u.js)
    writeFileSync(outPath, text, 'utf8')
    console.log(`[label-color-core] ${u.ts} -> src/shared/label-color/${u.js}（${text.split('\n').length} 行）`)
    files.push('src/shared/label-color/' + u.js)
  }
  return { skipped: false, files }
}

const invoked = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (invoked) {
  try {
    buildAll()
  } catch (e) {
    console.error((e && e.message) || e)
    process.exit(1)
  }
}
